// Auto-generated by scripts/generate-api-routes.mjs — do not edit by hand.
// Every handler under api/_handlers/ is imported here so the single
// api/[[...path]].js dispatcher function bundles them all.

import h0 from "./vendor/marketplace/inquiries/[id]/respond.js";
import h1 from "./internal/scf/requests/[id]/approve.js";
import h2 from "./internal/scf/requests/[id]/fund.js";
import h3 from "./vendor/rfqs/[id]/quotes/submit.js";
import h4 from "./vendor/marketplace/listing/publish.js";
import h5 from "./internal/vendors/[id]/preferred/[pref_id].js";
import h6 from "./internal/workspaces/[id]/tasks/[task_id].js";
import h7 from "./internal/workspaces/[id]/pins/[pin_id].js";
import h8 from "./vendor/workspaces/[id]/tasks/[task_id].js";
import h9 from "./internal/vendors/[id]/flags/[flag_id].js";
import h10 from "./internal/rfqs/[id]/award/[vendor_id].js";
import h11 from "./vendor/workspaces/[id]/pins/[pin_id].js";
import h12 from "./internal/compliance/automation-rules/[id].js";
import h13 from "./internal/workflow-executions/[id]/approve.js";
import h14 from "./internal/workflow-executions/[id]/reject.js";
import h15 from "./internal/scorecards/[vendor_id]/history.js";
import h16 from "./vendor/virtual-cards/[id]/confirm-spent.js";
import h17 from "./internal/diversity/[vendor_id]/verify.js";
import h18 from "./internal/sustainability/[id]/review.js";
import h19 from "./vendor/onboarding/steps/[step_name].js";
import h20 from "./internal/virtual-cards/[id]/cancel.js";
import h21 from "./vendor/discount-offers/[id]/accept.js";
import h22 from "./vendor/discount-offers/[id]/reject.js";
import h23 from "./internal/edi/[vendor_id]/messages.js";
import h24 from "./internal/contracts/[id]/versions.js";
import h25 from "./internal/payments/[id]/fx-detail.js";
import h26 from "./internal/workspaces/[id]/archive.js";
import h27 from "./vendor/virtual-cards/[id]/reveal.js";
import h28 from "./internal/compliance/[id]/review.js";
import h29 from "./internal/disputes/[id]/messages.js";
import h30 from "./internal/entities/[id]/branding.js";
import h31 from "./internal/vendors/[id]/anomalies.js";
import h32 from "./internal/vendors/[id]/preferred/index.js";
import h33 from "./internal/entities/[id]/vendors.js";
import h34 from "./internal/workspaces/[id]/tasks/index.js";
import h35 from "./vendor/contracts/[id]/versions.js";
import h36 from "./internal/edi/[vendor_id]/send.js";
import h37 from "./internal/workspaces/[id]/pins/index.js";
import h38 from "./vendor/disputes/[id]/messages.js";
import h39 from "./vendor/workspaces/[id]/tasks/index.js";
import h40 from "./internal/vendors/[id]/flags/index.js";
import h41 from "./internal/vendors/[id]/notes/index.js";
import h42 from "./vendor/workspaces/[id]/pins/index.js";
import h43 from "./internal/pos/[id]/messages.js";
import h44 from "./internal/rfqs/[id]/publish.js";
import h45 from "./vendor/contracts/[id]/sign.js";
import h46 from "./internal/rfqs/[id]/quotes.js";
import h47 from "./vendor/api-keys/[id]/logs.js";
import h48 from "./internal/rfqs/[id]/close.js";
import h49 from "./vendor/pos/[id]/messages.js";
import h50 from "./vendor/rfqs/[id]/decline.js";
import h51 from "./internal/tax/rules/[id].js";
import h52 from "./vendor/rfqs/[id]/quotes/index.js";
import h53 from "./internal/analytics/sustainability-trend.js";
import h54 from "./internal/compliance/automation-report.js";
import h55 from "./internal/compliance/automation-rules/index.js";
import h56 from "./internal/marketplace/convert-to-rfq.js";
import h57 from "./internal/analytics/diversity-spend.js";
import h58 from "./internal/compliance/document-types.js";
import h59 from "./internal/discount-offers/analytics.js";
import h60 from "./internal/discount-offers/generate.js";
import h61 from "./xoro/writeback/create-buy-request.js";
import h62 from "./internal/analytics/health-scores.js";
import h63 from "./internal/compliance/audit-trail.js";
import h64 from "./vendor/mobile/deregister-device.js";
import h65 from "./internal/marketplace/benchmark.js";
import h66 from "./internal/marketplace/inquiries.js";
import h67 from "./internal/messages/unread-count.js";
import h68 from "./internal/payments/virtual-card.js";
import h69 from "./internal/tax/remittance-report.js";
import h70 from "./internal/analytics/categories.js";
import h71 from "./vendor/compliance/audit-trail.js";
import h72 from "./vendor/mobile/register-device.js";
import h73 from "./xoro/writeback/cancel-po-line.js";
import h74 from "./xoro/writeback/reserve-update.js";
import h75 from "./internal/analytics/financial.js";
import h76 from "./internal/marketplace/inquire.js";
import h77 from "./internal/scorecards/generate.js";
import h78 from "./vendor/marketplace/inquiries/index.js";
import h79 from "./vendor/messages/unread-count.js";
import h80 from "./vendor/scf/eligible-invoices.js";
import h81 from "./internal/analytics/forecast.js";
import h82 from "./internal/vendors/diversity.js";
import h83 from "./vendor/marketplace/listing/index.js";
import h84 from "./xoro/writeback/expedite-po.js";
import h85 from "./internal/insights/summary.js";
import h86 from "./internal/tax/calculations.js";
import h87 from "./vendor/compliance/summary.js";
import h88 from "./internal/analytics/spend.js";
import h89 from "./internal/reports/vendors.js";
import h90 from "./internal/tax/remittances.js";
import h91 from "./internal/vendors/suggest.js";
import h92 from "./vendor/onboarding/submit.js";
import h93 from "./xoro/writeback/update-po.js";
import h94 from "./internal/messages/inbox.js";
import h95 from "./vendor/analytics/health.js";
import h96 from "./vendor/disputes/summary.js";
import h97 from "./vendor/mobile/dashboard.js";
import h98 from "./vendor/mobile/push-test.js";
import h99 from "./vendor/reports/invoices.js";
import h100 from "./internal/reports/spend.js";
import h101 from "./vendor/reports/summary.js";
import h102 from "./vendor/tax/withholding.js";
import h103 from "./internal/analytics/fx.js";
import h104 from "./internal/bulk/process.js";
import h105 from "./internal/scf/requests/index.js";
import h106 from "./edi/outbound/payment.js";
import h107 from "./vendor/scf/requests.js";
import h108 from "./internal/tax/rules/index.js";
import h109 from "./vendor/bulk/upload.js";
import h110 from "./vendor/mobile/feed.js";
import h111 from "./vendor/reports/pos.js";
import h112 from "./vendor/scf/request.js";
import h113 from "./internal/fx/rates.js";
import h114 from "./vendor/edi/status.js";
import h115 from "./edi/outbound/po.js";
import h116 from "./internal/workflow-executions/[id]/index.js";
import h117 from "./internal/onboarding/[vendor_id]/index.js";
import h118 from "./internal/workflow-rules/[id].js";
import h119 from "./internal/scf-programs/[id].js";
import h120 from "./vendor/sustainability/[id].js";
import h121 from "./marketplace/listings/[id].js";
import h122 from "./internal/workspaces/[id]/index.js";
import h123 from "./edi/inbound/[vendor_id].js";
import h124 from "./internal/anomalies/[id].js";
import h125 from "./internal/contracts/[id]/index.js";
import h126 from "./internal/disputes/[id]/index.js";
import h127 from "./internal/insights/[id].js";
import h128 from "./internal/payments/[id]/index.js";
import h129 from "./vendor/workspaces/[id]/index.js";
import h130 from "./internal/vendors/[id]/index.js";
import h131 from "./vendor/contracts/[id]/index.js";
import h132 from "./vendor/api-keys/[id]/index.js";
import h133 from "./vendor/disputes/[id]/index.js";
import h134 from "./internal/rfqs/[id]/index.js";
import h135 from "./vendor/bulk/[id]/index.js";
import h136 from "./vendor/rfqs/[id]/index.js";
import h137 from "./cron/workspace-tasks-due-soon.js";
import h138 from "./internal/workflow-executions/index.js";
import h139 from "./cron/compliance-automation.js";
import h140 from "./cron/discount-offers-daily.js";
import h141 from "./cron/health-scores-monthly.js";
import h142 from "./cron/insights-digest-daily.js";
import h143 from "./internal/preferred-vendors/index.js";
import h144 from "./vendor/payment-preferences/index.js";
import h145 from "./vendor/payment-preference/index.js";
import h146 from "./internal/discount-offers/index.js";
import h147 from "./vendor/diversity-profile/index.js";
import h148 from "./cron/scorecards-monthly.js";
import h149 from "./internal/sustainability/index.js";
import h150 from "./internal/workflow-rules/index.js";
import h151 from "./xoro/inventory-snapshot.js";
import h152 from "./cron/anomalies-nightly.js";
import h153 from "./cron/benchmark-compute.js";
import h154 from "./internal/virtual-cards/index.js";
import h155 from "./vendor/discount-offers/index.js";
import h156 from "./cron/compliance-daily.js";
import h157 from "./internal/scf-programs/index.js";
import h158 from "./vendor/sustainability/index.js";
import h159 from "./cron/contracts-daily.js";
import h160 from "./cron/insights-weekly.js";
import h161 from "./marketplace/listings/index.js";
import h162 from "./vendor/virtual-cards/index.js";
import h163 from "./internal/compliance/index.js";
import h164 from "./internal/esg-scores/index.js";
import h165 from "./internal/onboarding/index.js";
import h166 from "./internal/scorecards/index.js";
import h167 from "./internal/workspaces/index.js";
import h168 from "./shopify/collections.js";
import h169 from "./cron/push-delivery.js";
import h170 from "./internal/anomalies/index.js";
import h171 from "./internal/contracts/index.js";
import h172 from "./xoro/sales-history.js";
import h173 from "./cron/fx-rate-sync.js";
import h174 from "./internal/disputes/index.js";
import h175 from "./internal/entities/index.js";
import h176 from "./internal/insights/index.js";
import h177 from "./internal/payments/index.js";
import h178 from "./shopify/inventory.js";
import h179 from "./vendor/compliance/index.js";
import h180 from "./vendor/onboarding/index.js";
import h181 from "./vendor/workspaces/index.js";
import h182 from "./internal/vendors/index.js";
import h183 from "./shopify/products.js";
import h184 from "./vendor/contracts/index.js";
import h185 from "./vendor/esg-score/index.js";
import h186 from "./vendor/scorecard.js";
import h187 from "./vendor/shipments.js";
import h188 from "./shopify/returns.js";
import h189 from "./vendor/api-keys/index.js";
import h190 from "./vendor/disputes/index.js";
import h191 from "./vendor/entities.js";
import h192 from "./vendor/invoices.js";
import h193 from "./vendor/payments/index.js";
import h194 from "./shopify/orders.js";
import h195 from "./vendor/banking.js";
import h196 from "./internal/rfqs/index.js";
import h197 from "./xoro/open-pos.js";
import h198 from "./xoro/receipts.js";
import h199 from "./edi/inbound/index.js";
import h200 from "./vendor/bulk/index.js";
import h201 from "./vendor/rfqs/index.js";
import h202 from "./vendor/erp.js";
import h203 from "./xoro/items.js";
import h204 from "./xoro-receipts-sync.js";
import h205 from "./send-notification.js";
import h206 from "./searates-proxy.js";
import h207 from "./dropbox-proxy.js";
import h208 from "./vendor-invite.js";
import h209 from "./xoro-ap-sync.js";
import h210 from "./parse-excel.js";
import h211 from "./xoro-proxy.js";
import h212 from "./vendor/invoices/[id].js";
import h213 from "./vendor/ai-extract-invoice.js";
import h214 from "./vendor/shipments/[id].js";
import h215 from "./vendor/change-requests.js";
import h216 from "./internal/phase-change-requests/index.js";
import h217 from "./internal/phase-change-requests/[id]/approve.js";
import h218 from "./internal/phase-change-requests/[id]/reject.js";
import h219 from "./internal/phase-notes/index.js";
import h220 from "./internal/phase-change-requests/[id]/set-status.js";

export const ROUTES = [
  { pattern: "/api/vendor/marketplace/inquiries/:id/respond", handler: h0 },
  { pattern: "/api/internal/scf/requests/:id/approve", handler: h1 },
  { pattern: "/api/internal/scf/requests/:id/fund", handler: h2 },
  { pattern: "/api/vendor/rfqs/:id/quotes/submit", handler: h3 },
  { pattern: "/api/vendor/marketplace/listing/publish", handler: h4 },
  { pattern: "/api/internal/vendors/:id/preferred/:pref_id", handler: h5 },
  { pattern: "/api/internal/workspaces/:id/tasks/:task_id", handler: h6 },
  { pattern: "/api/internal/workspaces/:id/pins/:pin_id", handler: h7 },
  { pattern: "/api/vendor/workspaces/:id/tasks/:task_id", handler: h8 },
  { pattern: "/api/internal/vendors/:id/flags/:flag_id", handler: h9 },
  { pattern: "/api/internal/rfqs/:id/award/:vendor_id", handler: h10 },
  { pattern: "/api/vendor/workspaces/:id/pins/:pin_id", handler: h11 },
  { pattern: "/api/internal/compliance/automation-rules/:id", handler: h12 },
  { pattern: "/api/internal/workflow-executions/:id/approve", handler: h13 },
  { pattern: "/api/internal/workflow-executions/:id/reject", handler: h14 },
  { pattern: "/api/internal/scorecards/:vendor_id/history", handler: h15 },
  { pattern: "/api/vendor/virtual-cards/:id/confirm-spent", handler: h16 },
  { pattern: "/api/internal/diversity/:vendor_id/verify", handler: h17 },
  { pattern: "/api/internal/sustainability/:id/review", handler: h18 },
  { pattern: "/api/vendor/onboarding/steps/:step_name", handler: h19 },
  { pattern: "/api/internal/virtual-cards/:id/cancel", handler: h20 },
  { pattern: "/api/vendor/discount-offers/:id/accept", handler: h21 },
  { pattern: "/api/vendor/discount-offers/:id/reject", handler: h22 },
  { pattern: "/api/internal/edi/:vendor_id/messages", handler: h23 },
  { pattern: "/api/internal/contracts/:id/versions", handler: h24 },
  { pattern: "/api/internal/payments/:id/fx-detail", handler: h25 },
  { pattern: "/api/internal/workspaces/:id/archive", handler: h26 },
  { pattern: "/api/vendor/virtual-cards/:id/reveal", handler: h27 },
  { pattern: "/api/internal/compliance/:id/review", handler: h28 },
  { pattern: "/api/internal/disputes/:id/messages", handler: h29 },
  { pattern: "/api/internal/entities/:id/branding", handler: h30 },
  { pattern: "/api/internal/vendors/:id/anomalies", handler: h31 },
  { pattern: "/api/internal/vendors/:id/preferred", handler: h32 },
  { pattern: "/api/internal/entities/:id/vendors", handler: h33 },
  { pattern: "/api/internal/workspaces/:id/tasks", handler: h34 },
  { pattern: "/api/vendor/contracts/:id/versions", handler: h35 },
  { pattern: "/api/internal/edi/:vendor_id/send", handler: h36 },
  { pattern: "/api/internal/workspaces/:id/pins", handler: h37 },
  { pattern: "/api/vendor/disputes/:id/messages", handler: h38 },
  { pattern: "/api/vendor/workspaces/:id/tasks", handler: h39 },
  { pattern: "/api/internal/vendors/:id/flags", handler: h40 },
  { pattern: "/api/internal/vendors/:id/notes", handler: h41 },
  { pattern: "/api/vendor/workspaces/:id/pins", handler: h42 },
  { pattern: "/api/internal/pos/:id/messages", handler: h43 },
  { pattern: "/api/internal/rfqs/:id/publish", handler: h44 },
  { pattern: "/api/vendor/contracts/:id/sign", handler: h45 },
  { pattern: "/api/internal/rfqs/:id/quotes", handler: h46 },
  { pattern: "/api/vendor/api-keys/:id/logs", handler: h47 },
  { pattern: "/api/internal/rfqs/:id/close", handler: h48 },
  { pattern: "/api/vendor/pos/:id/messages", handler: h49 },
  { pattern: "/api/vendor/rfqs/:id/decline", handler: h50 },
  { pattern: "/api/internal/tax/rules/:id", handler: h51 },
  { pattern: "/api/vendor/rfqs/:id/quotes", handler: h52 },
  { pattern: "/api/internal/analytics/sustainability-trend", handler: h53 },
  { pattern: "/api/internal/compliance/automation-report", handler: h54 },
  { pattern: "/api/internal/compliance/automation-rules", handler: h55 },
  { pattern: "/api/internal/marketplace/convert-to-rfq", handler: h56 },
  { pattern: "/api/internal/analytics/diversity-spend", handler: h57 },
  { pattern: "/api/internal/compliance/document-types", handler: h58 },
  { pattern: "/api/internal/discount-offers/analytics", handler: h59 },
  { pattern: "/api/internal/discount-offers/generate", handler: h60 },
  { pattern: "/api/xoro/writeback/create-buy-request", handler: h61 },
  { pattern: "/api/internal/analytics/health-scores", handler: h62 },
  { pattern: "/api/internal/compliance/audit-trail", handler: h63 },
  { pattern: "/api/vendor/mobile/deregister-device", handler: h64 },
  { pattern: "/api/internal/marketplace/benchmark", handler: h65 },
  { pattern: "/api/internal/marketplace/inquiries", handler: h66 },
  { pattern: "/api/internal/messages/unread-count", handler: h67 },
  { pattern: "/api/internal/payments/virtual-card", handler: h68 },
  { pattern: "/api/internal/tax/remittance-report", handler: h69 },
  { pattern: "/api/internal/analytics/categories", handler: h70 },
  { pattern: "/api/vendor/compliance/audit-trail", handler: h71 },
  { pattern: "/api/vendor/mobile/register-device", handler: h72 },
  { pattern: "/api/xoro/writeback/cancel-po-line", handler: h73 },
  { pattern: "/api/xoro/writeback/reserve-update", handler: h74 },
  { pattern: "/api/internal/analytics/financial", handler: h75 },
  { pattern: "/api/internal/marketplace/inquire", handler: h76 },
  { pattern: "/api/internal/scorecards/generate", handler: h77 },
  { pattern: "/api/vendor/marketplace/inquiries", handler: h78 },
  { pattern: "/api/vendor/messages/unread-count", handler: h79 },
  { pattern: "/api/vendor/scf/eligible-invoices", handler: h80 },
  { pattern: "/api/internal/analytics/forecast", handler: h81 },
  { pattern: "/api/internal/vendors/diversity", handler: h82 },
  { pattern: "/api/vendor/marketplace/listing", handler: h83 },
  { pattern: "/api/xoro/writeback/expedite-po", handler: h84 },
  { pattern: "/api/internal/insights/summary", handler: h85 },
  { pattern: "/api/internal/tax/calculations", handler: h86 },
  { pattern: "/api/vendor/compliance/summary", handler: h87 },
  { pattern: "/api/internal/analytics/spend", handler: h88 },
  { pattern: "/api/internal/reports/vendors", handler: h89 },
  { pattern: "/api/internal/tax/remittances", handler: h90 },
  { pattern: "/api/internal/vendors/suggest", handler: h91 },
  { pattern: "/api/vendor/onboarding/submit", handler: h92 },
  { pattern: "/api/xoro/writeback/update-po", handler: h93 },
  { pattern: "/api/internal/messages/inbox", handler: h94 },
  { pattern: "/api/vendor/analytics/health", handler: h95 },
  { pattern: "/api/vendor/disputes/summary", handler: h96 },
  { pattern: "/api/vendor/mobile/dashboard", handler: h97 },
  { pattern: "/api/vendor/mobile/push-test", handler: h98 },
  { pattern: "/api/vendor/reports/invoices", handler: h99 },
  { pattern: "/api/internal/reports/spend", handler: h100 },
  { pattern: "/api/vendor/reports/summary", handler: h101 },
  { pattern: "/api/vendor/tax/withholding", handler: h102 },
  { pattern: "/api/internal/analytics/fx", handler: h103 },
  { pattern: "/api/internal/bulk/process", handler: h104 },
  { pattern: "/api/internal/scf/requests", handler: h105 },
  { pattern: "/api/edi/outbound/payment", handler: h106 },
  { pattern: "/api/vendor/scf/requests", handler: h107 },
  { pattern: "/api/internal/tax/rules", handler: h108 },
  { pattern: "/api/vendor/bulk/upload", handler: h109 },
  { pattern: "/api/vendor/mobile/feed", handler: h110 },
  { pattern: "/api/vendor/reports/pos", handler: h111 },
  { pattern: "/api/vendor/scf/request", handler: h112 },
  { pattern: "/api/internal/fx/rates", handler: h113 },
  { pattern: "/api/vendor/edi/status", handler: h114 },
  { pattern: "/api/edi/outbound/po", handler: h115 },
  { pattern: "/api/internal/workflow-executions/:id", handler: h116 },
  { pattern: "/api/internal/onboarding/:vendor_id", handler: h117 },
  { pattern: "/api/internal/workflow-rules/:id", handler: h118 },
  { pattern: "/api/internal/scf-programs/:id", handler: h119 },
  { pattern: "/api/vendor/sustainability/:id", handler: h120 },
  { pattern: "/api/marketplace/listings/:id", handler: h121 },
  { pattern: "/api/internal/workspaces/:id", handler: h122 },
  { pattern: "/api/edi/inbound/:vendor_id", handler: h123 },
  { pattern: "/api/internal/anomalies/:id", handler: h124 },
  { pattern: "/api/internal/contracts/:id", handler: h125 },
  { pattern: "/api/internal/disputes/:id", handler: h126 },
  { pattern: "/api/internal/insights/:id", handler: h127 },
  { pattern: "/api/internal/payments/:id", handler: h128 },
  { pattern: "/api/vendor/workspaces/:id", handler: h129 },
  { pattern: "/api/internal/vendors/:id", handler: h130 },
  { pattern: "/api/vendor/contracts/:id", handler: h131 },
  { pattern: "/api/vendor/api-keys/:id", handler: h132 },
  { pattern: "/api/vendor/disputes/:id", handler: h133 },
  { pattern: "/api/internal/rfqs/:id", handler: h134 },
  { pattern: "/api/vendor/bulk/:id", handler: h135 },
  { pattern: "/api/vendor/rfqs/:id", handler: h136 },
  { pattern: "/api/cron/workspace-tasks-due-soon", handler: h137 },
  { pattern: "/api/internal/workflow-executions", handler: h138 },
  { pattern: "/api/cron/compliance-automation", handler: h139 },
  { pattern: "/api/cron/discount-offers-daily", handler: h140 },
  { pattern: "/api/cron/health-scores-monthly", handler: h141 },
  { pattern: "/api/cron/insights-digest-daily", handler: h142 },
  { pattern: "/api/internal/preferred-vendors", handler: h143 },
  { pattern: "/api/vendor/payment-preferences", handler: h144 },
  { pattern: "/api/vendor/payment-preference", handler: h145 },
  { pattern: "/api/internal/discount-offers", handler: h146 },
  { pattern: "/api/vendor/diversity-profile", handler: h147 },
  { pattern: "/api/cron/scorecards-monthly", handler: h148 },
  { pattern: "/api/internal/sustainability", handler: h149 },
  { pattern: "/api/internal/workflow-rules", handler: h150 },
  { pattern: "/api/xoro/inventory-snapshot", handler: h151 },
  { pattern: "/api/cron/anomalies-nightly", handler: h152 },
  { pattern: "/api/cron/benchmark-compute", handler: h153 },
  { pattern: "/api/internal/virtual-cards", handler: h154 },
  { pattern: "/api/vendor/discount-offers", handler: h155 },
  { pattern: "/api/cron/compliance-daily", handler: h156 },
  { pattern: "/api/internal/scf-programs", handler: h157 },
  { pattern: "/api/vendor/sustainability", handler: h158 },
  { pattern: "/api/cron/contracts-daily", handler: h159 },
  { pattern: "/api/cron/insights-weekly", handler: h160 },
  { pattern: "/api/marketplace/listings", handler: h161 },
  { pattern: "/api/vendor/virtual-cards", handler: h162 },
  { pattern: "/api/internal/compliance", handler: h163 },
  { pattern: "/api/internal/esg-scores", handler: h164 },
  { pattern: "/api/internal/onboarding", handler: h165 },
  { pattern: "/api/internal/scorecards", handler: h166 },
  { pattern: "/api/internal/workspaces", handler: h167 },
  { pattern: "/api/shopify/collections", handler: h168 },
  { pattern: "/api/cron/push-delivery", handler: h169 },
  { pattern: "/api/internal/anomalies", handler: h170 },
  { pattern: "/api/internal/contracts", handler: h171 },
  { pattern: "/api/xoro/sales-history", handler: h172 },
  { pattern: "/api/cron/fx-rate-sync", handler: h173 },
  { pattern: "/api/internal/disputes", handler: h174 },
  { pattern: "/api/internal/entities", handler: h175 },
  { pattern: "/api/internal/insights", handler: h176 },
  { pattern: "/api/internal/payments", handler: h177 },
  { pattern: "/api/shopify/inventory", handler: h178 },
  { pattern: "/api/vendor/compliance", handler: h179 },
  { pattern: "/api/vendor/onboarding", handler: h180 },
  { pattern: "/api/vendor/workspaces", handler: h181 },
  { pattern: "/api/internal/vendors", handler: h182 },
  { pattern: "/api/shopify/products", handler: h183 },
  { pattern: "/api/vendor/contracts", handler: h184 },
  { pattern: "/api/vendor/esg-score", handler: h185 },
  { pattern: "/api/vendor/scorecard", handler: h186 },
  { pattern: "/api/vendor/shipments/:id", handler: h214 },
  { pattern: "/api/vendor/shipments", handler: h187 },
  { pattern: "/api/shopify/returns", handler: h188 },
  { pattern: "/api/vendor/api-keys", handler: h189 },
  { pattern: "/api/vendor/disputes", handler: h190 },
  { pattern: "/api/vendor/entities", handler: h191 },
  { pattern: "/api/vendor/ai-extract-invoice", handler: h213 },
  { pattern: "/api/vendor/change-requests", handler: h215 },
  { pattern: "/api/internal/phase-change-requests/:id/approve", handler: h217 },
  { pattern: "/api/internal/phase-change-requests/:id/reject", handler: h218 },
  { pattern: "/api/internal/phase-change-requests/:id/set-status", handler: h220 },
  { pattern: "/api/internal/phase-change-requests", handler: h216 },
  { pattern: "/api/internal/phase-notes", handler: h219 },
  { pattern: "/api/vendor/invoices/:id", handler: h212 },
  { pattern: "/api/vendor/invoices", handler: h192 },
  { pattern: "/api/vendor/payments", handler: h193 },
  { pattern: "/api/shopify/orders", handler: h194 },
  { pattern: "/api/vendor/banking", handler: h195 },
  { pattern: "/api/internal/rfqs", handler: h196 },
  { pattern: "/api/xoro/open-pos", handler: h197 },
  { pattern: "/api/xoro/receipts", handler: h198 },
  { pattern: "/api/edi/inbound", handler: h199 },
  { pattern: "/api/vendor/bulk", handler: h200 },
  { pattern: "/api/vendor/rfqs", handler: h201 },
  { pattern: "/api/vendor/erp", handler: h202 },
  { pattern: "/api/xoro/items", handler: h203 },
  { pattern: "/api/xoro-receipts-sync", handler: h204 },
  { pattern: "/api/send-notification", handler: h205 },
  { pattern: "/api/searates-proxy", handler: h206 },
  { pattern: "/api/dropbox-proxy", handler: h207 },
  { pattern: "/api/vendor-invite", handler: h208 },
  { pattern: "/api/xoro-ap-sync", handler: h209 },
  { pattern: "/api/parse-excel", handler: h210 },
  { pattern: "/api/xoro-proxy", handler: h211 },
];

export function compileRoutes(routes) {
  return routes.map((r) => {
    const segs = r.pattern.split("/").filter(Boolean);
    const params = [];
    const regexParts = segs.map((seg) => {
      if (seg.startsWith(":")) { params.push(seg.slice(1)); return "([^/]+)"; }
      if (seg.startsWith("*")) { params.push(seg.slice(1)); return "(.+)"; }
      return seg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    });
    const regex = new RegExp("^/" + regexParts.join("/") + "/?$");
    return { ...r, regex, params };
  });
}
