// Auto-generated by scripts/generate-api-routes.mjs — do not edit by hand.
// Every handler under api/_handlers/ is imported here so the single
// api/[[...path]].js dispatcher function bundles them all.

import h0 from "./vendor/marketplace/inquiries/[id]/respond.js";
import h1 from "./internal/scf/requests/[id]/approve.js";
import h2 from "./internal/scf/requests/[id]/fund.js";
import h3 from "./vendor/rfqs/[id]/quotes/submit.js";
import h4 from "./internal/design/trend-brief/synthesize.js";
import h5 from "./vendor/marketplace/listing/publish.js";
import h6 from "./internal/design/trend-brief/list.js";
import h7 from "./internal/vendors/[id]/preferred/[pref_id].js";
import h8 from "./internal/workspaces/[id]/tasks/[task_id].js";
import h9 from "./internal/workspaces/[id]/pins/[pin_id].js";
import h10 from "./vendor/workspaces/[id]/tasks/[task_id].js";
import h11 from "./internal/vendors/[id]/flags/[flag_id].js";
import h12 from "./internal/rfqs/[id]/award/[vendor_id].js";
import h13 from "./vendor/workspaces/[id]/pins/[pin_id].js";
import h14 from "./internal/phase-change-requests/[id]/set-status.js";
import h15 from "./internal/phase-change-requests/[id]/approve.js";
import h16 from "./internal/phase-change-requests/[id]/reject.js";
import h17 from "./internal/compliance/automation-rules/[id].js";
import h18 from "./internal/workflow-executions/[id]/approve.js";
import h19 from "./internal/workflow-executions/[id]/reject.js";
import h20 from "./internal/scorecards/[vendor_id]/history.js";
import h21 from "./vendor/virtual-cards/[id]/confirm-spent.js";
import h22 from "./internal/diversity/[vendor_id]/verify.js";
import h23 from "./internal/sustainability/[id]/review.js";
import h24 from "./vendor/onboarding/steps/[step_name].js";
import h25 from "./internal/virtual-cards/[id]/cancel.js";
import h26 from "./vendor/discount-offers/[id]/accept.js";
import h27 from "./vendor/discount-offers/[id]/reject.js";
import h28 from "./internal/edi/[vendor_id]/messages.js";
import h29 from "./internal/contracts/[id]/versions.js";
import h30 from "./internal/payments/[id]/fx-detail.js";
import h31 from "./internal/workspaces/[id]/archive.js";
import h32 from "./vendor/virtual-cards/[id]/reveal.js";
import h33 from "./internal/compliance/[id]/review.js";
import h34 from "./internal/disputes/[id]/messages.js";
import h35 from "./internal/entities/[id]/branding.js";
import h36 from "./internal/vendors/[id]/anomalies.js";
import h37 from "./internal/vendors/[id]/preferred/index.js";
import h38 from "./internal/entities/[id]/vendors.js";
import h39 from "./internal/workspaces/[id]/tasks/index.js";
import h40 from "./vendor/contracts/[id]/versions.js";
import h41 from "./internal/edi/[vendor_id]/send.js";
import h42 from "./internal/workspaces/[id]/pins/index.js";
import h43 from "./vendor/disputes/[id]/messages.js";
import h44 from "./vendor/workspaces/[id]/tasks/index.js";
import h45 from "./internal/vendors/[id]/flags/index.js";
import h46 from "./internal/vendors/[id]/notes/index.js";
import h47 from "./vendor/workspaces/[id]/pins/index.js";
import h48 from "./internal/pos/[id]/messages.js";
import h49 from "./internal/rfqs/[id]/publish.js";
import h50 from "./vendor/contracts/[id]/sign.js";
import h51 from "./internal/rfqs/[id]/quotes.js";
import h52 from "./vendor/api-keys/[id]/logs.js";
import h53 from "./internal/rfqs/[id]/close.js";
import h54 from "./vendor/pos/[id]/messages.js";
import h55 from "./vendor/rfqs/[id]/decline.js";
import h56 from "./internal/tax/rules/[id].js";
import h57 from "./vendor/rfqs/[id]/quotes/index.js";
import h58 from "./internal/analytics/sustainability-trend.js";
import h59 from "./internal/compliance/automation-report.js";
import h60 from "./internal/compliance/automation-rules/index.js";
import h61 from "./internal/marketplace/convert-to-rfq.js";
import h62 from "./internal/analytics/diversity-spend.js";
import h63 from "./internal/compliance/document-types.js";
import h64 from "./internal/discount-offers/analytics.js";
import h65 from "./internal/discount-offers/generate.js";
import h66 from "./xoro/writeback/create-buy-request.js";
import h67 from "./internal/analytics/early-payment.js";
import h68 from "./internal/analytics/health-scores.js";
import h69 from "./internal/compliance/audit-trail.js";
import h70 from "./vendor/mobile/deregister-device.js";
import h71 from "./internal/marketplace/benchmark.js";
import h72 from "./internal/marketplace/inquiries.js";
import h73 from "./internal/messages/unread-count.js";
import h74 from "./internal/payments/virtual-card.js";
import h75 from "./internal/tax/remittance-report.js";
import h76 from "./internal/analytics/categories.js";
import h77 from "./vendor/compliance/audit-trail.js";
import h78 from "./vendor/mobile/register-device.js";
import h79 from "./xoro/writeback/cancel-po-line.js";
import h80 from "./xoro/writeback/reserve-update.js";
import h81 from "./internal/analytics/financial.js";
import h82 from "./internal/marketplace/inquire.js";
import h83 from "./internal/scorecards/generate.js";
import h84 from "./vendor/marketplace/inquiries/index.js";
import h85 from "./vendor/messages/unread-count.js";
import h86 from "./vendor/scf/eligible-invoices.js";
import h87 from "./internal/ai/mention-suggest.js";
import h88 from "./internal/analytics/forecast.js";
import h89 from "./internal/vendors/diversity.js";
import h90 from "./vendor/marketplace/listing/index.js";
import h91 from "./xoro/writeback/expedite-po.js";
import h92 from "./internal/insights/summary.js";
import h93 from "./internal/tax/calculations.js";
import h94 from "./vendor/compliance/summary.js";
import h95 from "./internal/analytics/spend.js";
import h96 from "./internal/reports/vendors.js";
import h97 from "./internal/tax/remittances.js";
import h98 from "./internal/vendors/suggest.js";
import h99 from "./vendor/onboarding/submit.js";
import h100 from "./xoro/writeback/update-po.js";
import h101 from "./internal/ai/ops-summary.js";
import h102 from "./internal/messages/inbox.js";
import h103 from "./vendor/analytics/health.js";
import h104 from "./vendor/disputes/summary.js";
import h105 from "./vendor/mobile/dashboard.js";
import h106 from "./vendor/mobile/push-test.js";
import h107 from "./vendor/reports/invoices.js";
import h108 from "./internal/ai/user-facts.js";
import h109 from "./internal/reports/spend.js";
import h110 from "./vendor/reports/summary.js";
import h111 from "./vendor/tax/withholding.js";
import h112 from "./internal/ai/documents.js";
import h113 from "./internal/analytics/fx.js";
import h114 from "./internal/bulk/process.js";
import h115 from "./internal/scf/requests/index.js";
import h116 from "./edi/outbound/payment.js";
import h117 from "./internal/ai/insights.js";
import h118 from "./vendor/scf/requests.js";
import h119 from "./internal/tax/rules/index.js";
import h120 from "./vendor/bulk/upload.js";
import h121 from "./vendor/mobile/feed.js";
import h122 from "./vendor/reports/pos.js";
import h123 from "./vendor/scf/request.js";
import h124 from "./internal/fx/rates.js";
import h125 from "./vendor/edi/status.js";
import h126 from "./edi/outbound/po.js";
import h127 from "./internal/workflow-executions/[id]/index.js";
import h128 from "./internal/onboarding/[vendor_id]/index.js";
import h129 from "./internal/workflow-rules/[id].js";
import h130 from "./internal/scf-programs/[id].js";
import h131 from "./vendor/sustainability/[id].js";
import h132 from "./marketplace/listings/[id].js";
import h133 from "./internal/workspaces/[id]/index.js";
import h134 from "./edi/inbound/[vendor_id].js";
import h135 from "./internal/anomalies/[id].js";
import h136 from "./internal/contracts/[id]/index.js";
import h137 from "./vendor/attachments/[id].js";
import h138 from "./internal/disputes/[id]/index.js";
import h139 from "./internal/insights/[id].js";
import h140 from "./internal/payments/[id]/index.js";
import h141 from "./vendor/workspaces/[id]/index.js";
import h142 from "./internal/vendors/[id]/index.js";
import h143 from "./vendor/contracts/[id]/index.js";
import h144 from "./vendor/shipments/[id].js";
import h145 from "./vendor/api-keys/[id]/index.js";
import h146 from "./vendor/disputes/[id]/index.js";
import h147 from "./vendor/invoices/[id].js";
import h148 from "./internal/rfqs/[id]/index.js";
import h149 from "./vendor/bulk/[id]/index.js";
import h150 from "./vendor/rfqs/[id]/index.js";
import h151 from "./cron/notification-digest-flush.js";
import h152 from "./internal/phase-change-requests/index.js";
import h153 from "./cron/workspace-tasks-due-soon.js";
import h154 from "./cron/early-payment-analytics.js";
import h155 from "./internal/workflow-executions/index.js";
import h156 from "./cron/ai-proactive-insights.js";
import h157 from "./cron/compliance-automation.js";
import h158 from "./cron/discount-offers-daily.js";
import h159 from "./cron/health-scores-monthly.js";
import h160 from "./cron/insights-digest-daily.js";
import h161 from "./internal/preferred-vendors/index.js";
import h162 from "./vendor/payment-preferences/index.js";
import h163 from "./vendor/ai-extract-invoice.js";
import h164 from "./vendor/payment-preference/index.js";
import h165 from "./internal/discount-offers/index.js";
import h166 from "./vendor/diversity-profile/index.js";
import h167 from "./cron/scorecards-monthly.js";
import h168 from "./internal/sustainability/index.js";
import h169 from "./internal/workflow-rules/index.js";
import h170 from "./xoro/inventory-snapshot.js";
import h171 from "./cron/anomalies-nightly.js";
import h172 from "./cron/benchmark-compute.js";
import h173 from "./internal/virtual-cards/index.js";
import h174 from "./planning/sync-open-pos.js";
import h175 from "./vendor/change-requests.js";
import h176 from "./vendor/discount-offers/index.js";
import h177 from "./xoro/sync-item-costing.js";
import h178 from "./cron/compliance-daily.js";
import h179 from "./cron/po-issued-notify.js";
import h180 from "./internal/ip-ai-demand/index.js";
import h181 from "./internal/scf-programs/index.js";
import h182 from "./planning/sync-on-hand.js";
import h183 from "./vendor/sustainability/index.js";
import h184 from "./cron/contracts-daily.js";
import h185 from "./cron/insights-weekly.js";
import h186 from "./internal/phase-notes/index.js";
import h187 from "./marketplace/listings/index.js";
import h188 from "./tanda/sync-from-xoro.js";
import h189 from "./vendor/virtual-cards/index.js";
import h190 from "./internal/compliance/index.js";
import h191 from "./internal/esg-scores/index.js";
import h192 from "./internal/onboarding/index.js";
import h193 from "./internal/scorecards/index.js";
import h194 from "./internal/workspaces/index.js";
import h195 from "./sales/sync-invoices.js";
import h196 from "./shopify/collections.js";
import h197 from "./cron/push-delivery.js";
import h198 from "./internal/anomalies/index.js";
import h199 from "./internal/contracts/index.js";
import h200 from "./vendor/attachments/index.js";
import h201 from "./xoro/probe-filters.js";
import h202 from "./xoro/sales-history.js";
import h203 from "./cron/fx-rate-sync.js";
import h204 from "./internal/disputes/index.js";
import h205 from "./internal/entities/index.js";
import h206 from "./internal/insights/index.js";
import h207 from "./internal/payments/index.js";
import h208 from "./shopify/inventory.js";
import h209 from "./vendor/compliance/index.js";
import h210 from "./vendor/onboarding/index.js";
import h211 from "./vendor/workspaces/index.js";
import h212 from "./internal/vendors/index.js";
import h213 from "./shopify/products.js";
import h214 from "./vendor/contracts/index.js";
import h215 from "./vendor/esg-score/index.js";
import h216 from "./vendor/scorecard.js";
import h217 from "./vendor/shipments.js";
import h218 from "./shopify/returns.js";
import h219 from "./vendor/api-keys/index.js";
import h220 from "./vendor/disputes/index.js";
import h221 from "./vendor/entities.js";
import h222 from "./vendor/invoices.js";
import h223 from "./vendor/payments/index.js";
import h224 from "./shopify/orders.js";
import h225 from "./vendor/banking.js";
import h226 from "./internal/rfqs/index.js";
import h227 from "./xoro/open-pos.js";
import h229 from "./xoro/receipts.js";
import h230 from "./ai/ask-grid.js";
import h231 from "./edi/inbound/index.js";
import h232 from "./master/sync.js";
import h233 from "./vendor/bulk/index.js";
import h234 from "./vendor/rfqs/index.js";
import h235 from "./ats/upload.js";
import h236 from "./vendor/erp.js";
import h237 from "./xoro/items.js";
import h238 from "./xoro-items-missing-sync.js";
import h239 from "./xoro-receipts-sync.js";
import h240 from "./send-notification.js";
import h241 from "./ats-supply-sync.js";
import h242 from "./xoro-sales-sync.js";
import h243 from "./searates-proxy.js";
import h244 from "./tanda-pos-sync.js";
import h245 from "./dropbox-proxy.js";
import h246 from "./vendor-invite.js";
import h247 from "./xoro-ap-sync.js";
import h248 from "./parse-excel.js";
import h249 from "./xoro-proxy.js";
import h250 from "./sales/backfill-grain.js";
import h251 from "./internal/style-master/index.js";
import h252 from "./internal/style-master/[id].js";
import h253 from "./internal/vendor-master/index.js";
import h254 from "./internal/vendor-master/[id].js";
import h255 from "./internal/customer-master/index.js";
import h256 from "./internal/customer-master/[id].js";
import h257 from "./internal/gl-accounts/index.js";
import h258 from "./internal/gl-accounts/[id].js";
import h259 from "./internal/gl-periods/index.js";
import h260 from "./internal/gl-periods/[id].js";
import h261 from "./internal/journal-entries/index.js";
import h262 from "./internal/journal-entries/[id].js";
import h263 from "./internal/journal-entries/reverse.js";
import h264 from "./internal/approval-rules/index.js";
import h265 from "./internal/approval-rules/[id].js";
import h266 from "./internal/approval-requests/index.js";
import h267 from "./internal/approval-requests/[id].js";
import h268 from "./internal/approval-requests/decide.js";
import h269 from "./internal/approval-requests/cancel.js";
import h270 from "./internal/notifications/index.js";
import h271 from "./internal/notifications/mark-read.js";
import h272 from "./internal/notification-preferences/index.js";
import h273 from "./internal/documents/index.js";
import h274 from "./internal/documents/signed-url.js";
import h275 from "./internal/documents/archive.js";
import h276 from "./internal/employees/index.js";
import h277 from "./internal/employees/[id].js";
import h278 from "./internal/auth/provision.js";
import h279 from "./internal/inventory-transfers/index.js";
import h280 from "./internal/scanner/events/batch.js";
import h281 from "./internal/scanner/sessions/submit.js";
import h282 from "./internal/scanner/sessions/cancel.js";
import h283 from "./internal/scanner/sessions/[id].js";
import h284 from "./internal/scanner/sessions/index.js";
import h285 from "./internal/ap-invoices/index.js";
import h286 from "./internal/ap-invoices/[id].js";
import h287 from "./internal/ap-invoices/post.js";
import h288 from "./internal/ap-invoices/pay.js";
import h289 from "./internal/ap-invoices/void.js";
import h290 from "./internal/ap-payments/index.js";
import h291 from "./internal/fabric-codes/index.js";
import h292 from "./internal/fabric-codes/[id].js";
import h293 from "./internal/style-fabric-codes/index.js";
import h294 from "./internal/style-fabric-codes/[id].js";
import h295 from "./internal/inventory-adjustments/index.js";
import h296 from "./internal/inventory-adjustments/[id].js";
import h297 from "./internal/inventory-adjustments/post.js";
import h298 from "./internal/inventory-cycle-counts/index.js";
import h299 from "./internal/inventory-cycle-counts/[id].js";
import h300 from "./internal/inventory-cycle-counts/lines.js";
import h301 from "./internal/inventory-cycle-counts/finalize.js";
import h302 from "./internal/payment-terms/index.js";
import h303 from "./internal/payment-terms/[id].js";
// P4-4 — AR Invoices admin (h304..h307).
import h304 from "./internal/ar-invoices/index.js";
import h305 from "./internal/ar-invoices/[id].js";
import h306 from "./internal/ar-invoices/post.js";
import h307 from "./internal/ar-invoices/void.js";
// P4-5 — AR Receipts admin (h308..h312). Both chunks APPEND here.
import h308 from "./internal/ar-receipts/index.js";
import h309 from "./internal/ar-receipts/[id].js";
import h310 from "./internal/ar-receipts/post.js";
import h311 from "./internal/ar-receipts/void.js";
import h312 from "./internal/ar-receipt-applications/[id].js";
// P4-6 — AR Aging GET (h313). APPEND ONLY.
import h313 from "./internal/ar-aging/index.js";
// P4-8 — AR historical backfill runner (h314) + status (h315). APPEND ONLY.
import h314 from "./internal/ar-backfill/run.js";
import h315 from "./internal/ar-backfill/status.js";
// P5-1 — Period close mechanics (h316 close + h317 reopen). APPEND ONLY.
import h316 from "./internal/gl-periods/close.js";
import h317 from "./internal/gl-periods/reopen.js";
// P5-2 — Trial Balance GET (h318). APPEND ONLY.
import h318 from "./internal/trial-balance/index.js";
// P5-3 — Income Statement GET (h319). APPEND ONLY.
import h319 from "./internal/income-statement/index.js";
// P5-4 — Balance Sheet GET (h320). APPEND ONLY.
import h320 from "./internal/balance-sheet/index.js";
// P5-5 — Cash Flow Statement GET (h321). APPEND ONLY.
import h321 from "./internal/cash-flow/index.js";
// P5-6 — Year-End Close runner (h322 POST). APPEND ONLY.
import h322 from "./internal/year-end-close/run.js";
// P5-7 — Period-close pre-flight check (h323 GET). APPEND ONLY.
import h323 from "./internal/gl-periods/preflight.js";
// P6-2 — Plaid link-token (h324) + exchange (h325) + sync cron (h326) + webhook (h327). APPEND ONLY.
import h324 from "./internal/bank-feeds/link-token.js";
import h325 from "./internal/bank-feeds/exchange.js";
import h326 from "../cron/bank-feed-sync.js";
import h327 from "../webhooks/plaid.js";
// P6-3 — Bank CSV upload (h328 POST). APPEND ONLY.
import h328 from "./internal/bank-feeds/csv-upload.js";
// P6-5 — Bank reconciliation admin handlers (h329-h335). APPEND ONLY.
import h329 from "./internal/bank-accounts/index.js";
import h330 from "./internal/bank-transactions/index.js";
import h331 from "./internal/bank-transactions/match-candidates.js";
import h332 from "./internal/bank-transactions/apply-match.js";
import h333 from "./internal/bank-transactions/unmatch.js";
import h334 from "./internal/bank-transactions/create-je.js";
import h335 from "./internal/bank-transactions/ignore.js";
// P6-7 — Auto-post fee rules (h339 PATCH bank_account + h340 cron). APPEND ONLY.
import h339 from "./internal/bank-accounts/[id].js";
import h340 from "../cron/bank-auto-post-fees.js";
// P7-5 — Commission accrue/reverse/settle RPCs + list endpoints (h341-h345). APPEND ONLY.
import h341 from "./internal/commissions/accrue.js";
import h342 from "./internal/commissions/reverse.js";
import h343 from "./internal/commissions/settle.js";
import h344 from "./internal/commissions/accruals.js";
import h345 from "./internal/commissions/payouts.js";
// P7-7 — M9-subset operational reports (h346-h349 GET). APPEND ONLY.
import h346 from "./internal/ap-aging/index.js";
import h347 from "./internal/sales-by-rep/index.js";
import h348 from "./internal/sales-by-customer/index.js";
import h349 from "./internal/gl-detail/index.js";
// P7-9 — Cases UI + Resend inbound webhook (h350-h353). APPEND ONLY.
import h350 from "./internal/cases/index.js";
import h351 from "./internal/cases/[id].js";
import h352 from "./internal/cases/[id]/comments.js";
import h353 from "./webhooks/resend-inbound.js";
// P8-2 — CRM handlers + stage-change RPC (h360-h367). APPEND ONLY.
import h360 from "./internal/crm/opportunities/index.js";
import h361 from "./internal/crm/opportunities/[id].js";
import h362 from "./internal/crm/opportunities/[id]/stage.js";
import h363 from "./internal/crm/activities/index.js";
import h364 from "./internal/crm/activities/[id].js";
import h365 from "./internal/crm/tasks/index.js";
import h366 from "./internal/crm/tasks/[id].js";
import h367 from "./internal/crm/pipeline-report/index.js";
// P8-6 — PIM handlers (non-image: categories + attribute-defs + style composite + attributes + descriptions). APPEND ONLY.
import h370 from "./internal/pim/categories/index.js";
import h371 from "./internal/pim/categories/[id].js";
import h372 from "./internal/pim/attribute-defs/index.js";
import h373 from "./internal/pim/attribute-defs/[id].js";
import h374 from "./internal/pim/styles/[style_id].js";
import h375 from "./internal/pim/styles/[style_id]/attributes.js";
import h376 from "./internal/pim/styles/[style_id]/description/index.js";
import h377 from "./internal/pim/styles/[style_id]/description/publish.js";
// P8-7 — PIM image upload + Sharp pipeline (h380-h383). APPEND ONLY.
import h380 from "./internal/pim/styles/[style_id]/images/index.js";
import h381 from "./internal/pim/styles/[style_id]/images/[id].js";
import h382 from "./internal/pim/styles/[style_id]/images/[id]/delete.js";
import h383 from "./internal/pim/styles/[style_id]/images/[id]/signed-url.js";
// T10 cross-cutter Xoro shadow mirror handlers. APPEND ONLY.
//   h400 = T10-2 AR mirror
//   h401 = T10-3 AP mirror (this PR)
//   h402 = T10-4 inventory rebuild
//   h403 = T10-5 daily summary JE poster
import h400 from "./internal/xoro-mirror/ar.js";
import h401 from "./internal/xoro-mirror/ap.js";
import h403 from "./internal/xoro-mirror/summary-je.js";
// T10-6 — Nightly Xoro mirror orchestrator cron.
import h404 from "../cron/xoro-mirror-nightly.js";
// T6-2 — Global search RPC handler. Numbered h426 to reserve h405-h425
// for the T4-2 personalization batch landing concurrently on main.
import h426 from "./internal/search/index.js";
// T4-1 — Cross-cutter Personalization nightly click-decay cron.
import h420 from "../cron/menu-usage-decay.js";
// T4-2 — Cross-cutter Personalization registry + me/preferences + menu-click API.
//   h421 = GET  /api/internal/users/me/preferences
//   h422 = PUT  /api/internal/users/me/preferences/favorites
//   h423 = PUT  /api/internal/users/me/preferences/home-route
//   h424 = POST /api/internal/users/me/menu-click
//   h425 = GET  /api/internal/users/me/menu-usage/top
import h421 from "./internal/users/me/preferences/index.js";
import h422 from "./internal/users/me/preferences/favorites.js";
import h423 from "./internal/users/me/preferences/home-route.js";
import h424 from "./internal/users/me/menu-click/index.js";
import h425 from "./internal/users/me/menu-usage/top.js";
// P10-2b — Entity-switcher API (deferred from P10-2).
//   h430 = PUT /api/internal/users/me/entity-switch  (validate membership)
//   h431 = PUT /api/internal/users/me/entity-default (toggle is_default)
//   h432 = GET /api/internal/users/me/entities       (list + current_entity_id)
import h430 from "./internal/users/me/entity-switch.js";
import h431 from "./internal/users/me/entity-default.js";
import h432 from "./internal/users/me/entities/index.js";
// P12b-2 — Walmart Marketplace orders ingest (manual + cron).
//   h452 = POST /api/internal/walmart/sync-orders
//   h453 = POST /api/cron/walmart-orders-nightly
import h452 from "./internal/walmart/sync-orders.js";
import h453 from "../cron/walmart-orders-nightly.js";
// P12c-2 — Faire wholesale marketplace ingest (manual triggers + crons).
import h454 from "./internal/faire/sync-orders.js";
import h455 from "../cron/faire-orders-nightly.js";
import h456 from "./internal/faire/sync-payouts.js";
import h457 from "../cron/faire-payouts-monthly.js";
// P11-3 — Shopify AR JE posting manual backfill handler.
// h441 = POST /api/internal/shopify/post-order/:id
import h441 from "./internal/shopify/post-order/[id].js";
// P11-2 — Shopify webhook intake (orders/create + orders/updated).
import h440 from "./internal/shopify/webhooks/orders.js";
// P11-9 — Shopify Payments payout reconciliation (manual + daily cron).
// h444 = POST /api/internal/shopify/sync-payouts  (manual trigger)
// h445 = GET  /api/cron/shopify-payouts-daily     (06:00 UTC daily)
import h444 from "./internal/shopify/sync-payouts.js";
import h445 from "../cron/shopify-payouts-daily.js";
// P11-4 — Shopify backfill cron (catches webhook drops every 6h) +
// manual backfill trigger.
// h442 = POST /api/internal/shopify/backfill
// h443 = GET/POST /api/cron/shopify-backfill
import h442 from "./internal/shopify/backfill.js";
import h443 from "../cron/shopify-backfill.js";
// P12a-2 — Amazon FBA SP-API client + orders ingest cron.
//   h450 = POST /api/internal/fba/sync-orders  (manual single-account trigger)
//   h451 = GET/POST /api/cron/fba-orders-nightly (Vercel cron, 03:00 UTC)
import h450 from "./internal/fba/sync-orders.js";
import h451 from "../cron/fba-orders-nightly.js";
// P12a-3 — Amazon FBA AR invoice JE posting (manual backfill).
//   h458 = POST /api/internal/fba/post-order/:id (manual JE post for one order)
import h458 from "./internal/fba/post-order/[id].js";
// P12b-3 — Walmart AR JE posting manual backfill handler.
//   h459 = POST /api/internal/walmart/post-order/:id
import h459 from "./internal/walmart/post-order/[id].js";
// P12b-4 — Walmart Marketplace settlement reconciliation (weekly cron + manual).
//   h464 = POST /api/internal/walmart/sync-settlements (manual trigger)
//   h465 = GET/POST /api/cron/walmart-settlements-weekly (Vercel cron, Wed 06:30 UTC)
import h464 from "./internal/walmart/sync-settlements.js";
import h465 from "../cron/walmart-settlements-weekly.js";
// P12b-5 — Walmart returns sync (credit memo + restock + restocking fee).
//   h471 = POST /api/internal/walmart/sync-returns  (manual single-account trigger)
//   h472 = GET/POST /api/cron/walmart-returns-daily (Vercel cron, 05:00 UTC)
import h471 from "./internal/walmart/sync-returns.js";
import h472 from "../cron/walmart-returns-daily.js";
// P11-8 — Shopify dispute (chargeback) webhook intake.
//   h466 = POST /api/internal/shopify/webhooks/disputes
import h466 from "./internal/shopify/webhooks/disputes.js";

// P12c-4 — Faire wholesale returns ingest (credit memo + restock).
//   h473 = POST /api/internal/faire/sync-returns      (manual trigger)
//   h474 = GET  /api/cron/faire-returns-weekly        (Mon 05:30 UTC)
import h473 from "./internal/faire/sync-returns.js";
import h474 from "../cron/faire-returns-weekly.js";

// Cross-cutter T11-3 — Universal audit log read API.
//   h485 = GET /api/internal/audit/row-history (per-row timeline for detail modals)
//   h486 = GET /api/internal/audit/log         (full filtered ledger for admin panel)
import h485 from "./internal/audit/row-history.js";
import h486 from "./internal/audit/log.js";

// Costing Module — Chunk 2 (CRUD + autocompletes + select-quote stub).
// Handler vars shifted past audit's h485/h486 — search/sales-reps onwards
// use h493-h496 instead of h485-h488 to avoid collision.
import h475 from "./internal/costing/projects/index.js";
import h476 from "./internal/costing/projects/[id]/index.js";
import h477 from "./internal/costing/projects/[id]/lines.js";
import h478 from "./internal/costing/lines/[line_id]/index.js";
import h479 from "./internal/costing/lines/[line_id]/quotes/index.js";
import h480 from "./internal/costing/lines/[line_id]/quotes/[quote_id].js";
import h481 from "./internal/costing/lines/[line_id]/select-quote.js";
import h482 from "./internal/costing/search/styles.js";
import h483 from "./internal/costing/search/vendors.js";
import h484 from "./internal/costing/search/customers.js";
import h493 from "./internal/costing/search/sales-reps.js";
import h494 from "./internal/costing/search/fabrics.js";
import h495 from "./internal/costing/search/categories.js";
import h496 from "./internal/costing/search/scales.js";

// Costing Module — Chunk 5 (LY + trailing-3-month comp aggregation).
//   h489 = POST /api/internal/costing/comp/ly         (last-year per-style aggregates)
//   h490 = POST /api/internal/costing/comp/t3         (trailing-3-month per-style aggregates)
// PPK guard: qty_grain='unit' filter; comp_grain_warning when window was all
// pack-grain (per project_ppk_grain_rule_CANONICAL).
import h489 from "./internal/costing/comp/ly.js";
import h490 from "./internal/costing/comp/t3.js";

// Costing Module — Chunk 7 (compliance checklist handlers).
//   h491 GET/POST   /api/internal/costing/lines/:line_id/compliance
//   h492 PUT/DELETE /api/internal/costing/lines/:line_id/compliance/:req_id
import h491 from "./internal/costing/lines/[line_id]/compliance/index.js";
import h492 from "./internal/costing/lines/[line_id]/compliance/[req_id].js";

export const ROUTES = [
  { pattern: "/api/vendor/marketplace/inquiries/:id/respond", handler: h0 },
  { pattern: "/api/internal/scf/requests/:id/approve", handler: h1 },
  { pattern: "/api/internal/scf/requests/:id/fund", handler: h2 },
  { pattern: "/api/vendor/rfqs/:id/quotes/submit", handler: h3 },
  { pattern: "/api/internal/design/trend-brief/synthesize", handler: h4 },
  { pattern: "/api/vendor/marketplace/listing/publish", handler: h5 },
  { pattern: "/api/internal/design/trend-brief/list", handler: h6 },
  { pattern: "/api/internal/vendors/:id/preferred/:pref_id", handler: h7 },
  { pattern: "/api/internal/workspaces/:id/tasks/:task_id", handler: h8 },
  { pattern: "/api/internal/workspaces/:id/pins/:pin_id", handler: h9 },
  { pattern: "/api/vendor/workspaces/:id/tasks/:task_id", handler: h10 },
  { pattern: "/api/internal/vendors/:id/flags/:flag_id", handler: h11 },
  { pattern: "/api/internal/rfqs/:id/award/:vendor_id", handler: h12 },
  { pattern: "/api/vendor/workspaces/:id/pins/:pin_id", handler: h13 },
  { pattern: "/api/internal/phase-change-requests/:id/set-status", handler: h14 },
  { pattern: "/api/internal/phase-change-requests/:id/approve", handler: h15 },
  { pattern: "/api/internal/phase-change-requests/:id/reject", handler: h16 },
  { pattern: "/api/internal/compliance/automation-rules/:id", handler: h17 },
  { pattern: "/api/internal/workflow-executions/:id/approve", handler: h18 },
  { pattern: "/api/internal/workflow-executions/:id/reject", handler: h19 },
  { pattern: "/api/internal/scorecards/:vendor_id/history", handler: h20 },
  { pattern: "/api/vendor/virtual-cards/:id/confirm-spent", handler: h21 },
  { pattern: "/api/internal/diversity/:vendor_id/verify", handler: h22 },
  { pattern: "/api/internal/sustainability/:id/review", handler: h23 },
  { pattern: "/api/vendor/onboarding/steps/:step_name", handler: h24 },
  { pattern: "/api/internal/virtual-cards/:id/cancel", handler: h25 },
  { pattern: "/api/vendor/discount-offers/:id/accept", handler: h26 },
  { pattern: "/api/vendor/discount-offers/:id/reject", handler: h27 },
  { pattern: "/api/internal/edi/:vendor_id/messages", handler: h28 },
  { pattern: "/api/internal/contracts/:id/versions", handler: h29 },
  { pattern: "/api/internal/payments/:id/fx-detail", handler: h30 },
  { pattern: "/api/internal/workspaces/:id/archive", handler: h31 },
  { pattern: "/api/vendor/virtual-cards/:id/reveal", handler: h32 },
  { pattern: "/api/internal/compliance/:id/review", handler: h33 },
  { pattern: "/api/internal/disputes/:id/messages", handler: h34 },
  { pattern: "/api/internal/entities/:id/branding", handler: h35 },
  { pattern: "/api/internal/vendors/:id/anomalies", handler: h36 },
  { pattern: "/api/internal/vendors/:id/preferred", handler: h37 },
  { pattern: "/api/internal/entities/:id/vendors", handler: h38 },
  { pattern: "/api/internal/workspaces/:id/tasks", handler: h39 },
  { pattern: "/api/vendor/contracts/:id/versions", handler: h40 },
  { pattern: "/api/internal/edi/:vendor_id/send", handler: h41 },
  { pattern: "/api/internal/workspaces/:id/pins", handler: h42 },
  { pattern: "/api/vendor/disputes/:id/messages", handler: h43 },
  { pattern: "/api/vendor/workspaces/:id/tasks", handler: h44 },
  { pattern: "/api/internal/vendors/:id/flags", handler: h45 },
  { pattern: "/api/internal/vendors/:id/notes", handler: h46 },
  { pattern: "/api/vendor/workspaces/:id/pins", handler: h47 },
  { pattern: "/api/internal/pos/:id/messages", handler: h48 },
  { pattern: "/api/internal/rfqs/:id/publish", handler: h49 },
  { pattern: "/api/vendor/contracts/:id/sign", handler: h50 },
  { pattern: "/api/internal/rfqs/:id/quotes", handler: h51 },
  { pattern: "/api/vendor/api-keys/:id/logs", handler: h52 },
  { pattern: "/api/internal/rfqs/:id/close", handler: h53 },
  { pattern: "/api/vendor/pos/:id/messages", handler: h54 },
  { pattern: "/api/vendor/rfqs/:id/decline", handler: h55 },
  { pattern: "/api/internal/tax/rules/:id", handler: h56 },
  { pattern: "/api/vendor/rfqs/:id/quotes", handler: h57 },
  { pattern: "/api/internal/analytics/sustainability-trend", handler: h58 },
  { pattern: "/api/internal/compliance/automation-report", handler: h59 },
  { pattern: "/api/internal/compliance/automation-rules", handler: h60 },
  { pattern: "/api/internal/marketplace/convert-to-rfq", handler: h61 },
  { pattern: "/api/internal/analytics/diversity-spend", handler: h62 },
  { pattern: "/api/internal/compliance/document-types", handler: h63 },
  { pattern: "/api/internal/discount-offers/analytics", handler: h64 },
  { pattern: "/api/internal/discount-offers/generate", handler: h65 },
  { pattern: "/api/xoro/writeback/create-buy-request", handler: h66 },
  { pattern: "/api/internal/analytics/early-payment", handler: h67 },
  { pattern: "/api/internal/analytics/health-scores", handler: h68 },
  { pattern: "/api/internal/compliance/audit-trail", handler: h69 },
  { pattern: "/api/vendor/mobile/deregister-device", handler: h70 },
  { pattern: "/api/internal/marketplace/benchmark", handler: h71 },
  { pattern: "/api/internal/marketplace/inquiries", handler: h72 },
  { pattern: "/api/internal/messages/unread-count", handler: h73 },
  { pattern: "/api/internal/payments/virtual-card", handler: h74 },
  { pattern: "/api/internal/tax/remittance-report", handler: h75 },
  { pattern: "/api/internal/analytics/categories", handler: h76 },
  { pattern: "/api/vendor/compliance/audit-trail", handler: h77 },
  { pattern: "/api/vendor/mobile/register-device", handler: h78 },
  { pattern: "/api/xoro/writeback/cancel-po-line", handler: h79 },
  { pattern: "/api/xoro/writeback/reserve-update", handler: h80 },
  { pattern: "/api/internal/analytics/financial", handler: h81 },
  { pattern: "/api/internal/marketplace/inquire", handler: h82 },
  { pattern: "/api/internal/scorecards/generate", handler: h83 },
  { pattern: "/api/vendor/marketplace/inquiries", handler: h84 },
  { pattern: "/api/vendor/messages/unread-count", handler: h85 },
  { pattern: "/api/vendor/scf/eligible-invoices", handler: h86 },
  { pattern: "/api/internal/ai/mention-suggest", handler: h87 },
  { pattern: "/api/internal/analytics/forecast", handler: h88 },
  { pattern: "/api/internal/vendors/diversity", handler: h89 },
  { pattern: "/api/vendor/marketplace/listing", handler: h90 },
  { pattern: "/api/xoro/writeback/expedite-po", handler: h91 },
  { pattern: "/api/internal/insights/summary", handler: h92 },
  { pattern: "/api/internal/tax/calculations", handler: h93 },
  { pattern: "/api/vendor/compliance/summary", handler: h94 },
  { pattern: "/api/internal/analytics/spend", handler: h95 },
  { pattern: "/api/internal/reports/vendors", handler: h96 },
  { pattern: "/api/internal/tax/remittances", handler: h97 },
  { pattern: "/api/internal/vendors/suggest", handler: h98 },
  { pattern: "/api/vendor/onboarding/submit", handler: h99 },
  { pattern: "/api/xoro/writeback/update-po", handler: h100 },
  { pattern: "/api/internal/ai/ops-summary", handler: h101 },
  { pattern: "/api/internal/messages/inbox", handler: h102 },
  { pattern: "/api/vendor/analytics/health", handler: h103 },
  { pattern: "/api/vendor/disputes/summary", handler: h104 },
  { pattern: "/api/vendor/mobile/dashboard", handler: h105 },
  { pattern: "/api/vendor/mobile/push-test", handler: h106 },
  { pattern: "/api/vendor/reports/invoices", handler: h107 },
  { pattern: "/api/internal/ai/user-facts", handler: h108 },
  { pattern: "/api/internal/reports/spend", handler: h109 },
  { pattern: "/api/vendor/reports/summary", handler: h110 },
  { pattern: "/api/vendor/tax/withholding", handler: h111 },
  { pattern: "/api/internal/ai/documents", handler: h112 },
  { pattern: "/api/internal/analytics/fx", handler: h113 },
  { pattern: "/api/internal/bulk/process", handler: h114 },
  { pattern: "/api/internal/scf/requests", handler: h115 },
  { pattern: "/api/edi/outbound/payment", handler: h116 },
  { pattern: "/api/internal/ai/insights", handler: h117 },
  { pattern: "/api/vendor/scf/requests", handler: h118 },
  { pattern: "/api/internal/tax/rules", handler: h119 },
  { pattern: "/api/vendor/bulk/upload", handler: h120 },
  { pattern: "/api/vendor/mobile/feed", handler: h121 },
  { pattern: "/api/vendor/reports/pos", handler: h122 },
  { pattern: "/api/vendor/scf/request", handler: h123 },
  { pattern: "/api/internal/fx/rates", handler: h124 },
  { pattern: "/api/vendor/edi/status", handler: h125 },
  { pattern: "/api/edi/outbound/po", handler: h126 },
  { pattern: "/api/internal/workflow-executions/:id", handler: h127 },
  { pattern: "/api/internal/onboarding/:vendor_id", handler: h128 },
  { pattern: "/api/internal/workflow-rules/:id", handler: h129 },
  { pattern: "/api/internal/scf-programs/:id", handler: h130 },
  { pattern: "/api/vendor/sustainability/:id", handler: h131 },
  { pattern: "/api/marketplace/listings/:id", handler: h132 },
  { pattern: "/api/internal/workspaces/:id", handler: h133 },
  { pattern: "/api/edi/inbound/:vendor_id", handler: h134 },
  { pattern: "/api/internal/anomalies/:id", handler: h135 },
  { pattern: "/api/internal/contracts/:id", handler: h136 },
  { pattern: "/api/vendor/attachments/:id", handler: h137 },
  { pattern: "/api/internal/disputes/:id", handler: h138 },
  { pattern: "/api/internal/insights/:id", handler: h139 },
  { pattern: "/api/internal/payments/:id", handler: h140 },
  { pattern: "/api/vendor/workspaces/:id", handler: h141 },
  { pattern: "/api/internal/vendors/:id", handler: h142 },
  { pattern: "/api/vendor/contracts/:id", handler: h143 },
  { pattern: "/api/vendor/shipments/:id", handler: h144 },
  { pattern: "/api/vendor/api-keys/:id", handler: h145 },
  { pattern: "/api/vendor/disputes/:id", handler: h146 },
  { pattern: "/api/vendor/invoices/:id", handler: h147 },
  { pattern: "/api/internal/rfqs/:id", handler: h148 },
  { pattern: "/api/vendor/bulk/:id", handler: h149 },
  { pattern: "/api/vendor/rfqs/:id", handler: h150 },
  { pattern: "/api/cron/notification-digest-flush", handler: h151 },
  { pattern: "/api/internal/phase-change-requests", handler: h152 },
  { pattern: "/api/cron/workspace-tasks-due-soon", handler: h153 },
  { pattern: "/api/cron/early-payment-analytics", handler: h154 },
  { pattern: "/api/internal/workflow-executions", handler: h155 },
  { pattern: "/api/cron/ai-proactive-insights", handler: h156 },
  { pattern: "/api/cron/compliance-automation", handler: h157 },
  { pattern: "/api/cron/discount-offers-daily", handler: h158 },
  { pattern: "/api/cron/health-scores-monthly", handler: h159 },
  { pattern: "/api/cron/insights-digest-daily", handler: h160 },
  { pattern: "/api/internal/preferred-vendors", handler: h161 },
  { pattern: "/api/vendor/payment-preferences", handler: h162 },
  { pattern: "/api/vendor/ai-extract-invoice", handler: h163 },
  { pattern: "/api/vendor/payment-preference", handler: h164 },
  { pattern: "/api/internal/discount-offers", handler: h165 },
  { pattern: "/api/vendor/diversity-profile", handler: h166 },
  { pattern: "/api/cron/scorecards-monthly", handler: h167 },
  { pattern: "/api/internal/sustainability", handler: h168 },
  { pattern: "/api/internal/workflow-rules", handler: h169 },
  { pattern: "/api/xoro/inventory-snapshot", handler: h170 },
  { pattern: "/api/cron/anomalies-nightly", handler: h171 },
  { pattern: "/api/cron/benchmark-compute", handler: h172 },
  { pattern: "/api/internal/virtual-cards", handler: h173 },
  { pattern: "/api/planning/sync-open-pos", handler: h174 },
  { pattern: "/api/vendor/change-requests", handler: h175 },
  { pattern: "/api/vendor/discount-offers", handler: h176 },
  { pattern: "/api/xoro/sync-item-costing", handler: h177 },
  { pattern: "/api/cron/compliance-daily", handler: h178 },
  { pattern: "/api/cron/po-issued-notify", handler: h179 },
  { pattern: "/api/internal/ip-ai-demand", handler: h180 },
  { pattern: "/api/internal/scf-programs", handler: h181 },
  { pattern: "/api/planning/sync-on-hand", handler: h182 },
  { pattern: "/api/vendor/sustainability", handler: h183 },
  { pattern: "/api/cron/contracts-daily", handler: h184 },
  { pattern: "/api/cron/insights-weekly", handler: h185 },
  { pattern: "/api/internal/phase-notes", handler: h186 },
  { pattern: "/api/marketplace/listings", handler: h187 },
  { pattern: "/api/tanda/sync-from-xoro", handler: h188 },
  { pattern: "/api/vendor/virtual-cards", handler: h189 },
  { pattern: "/api/internal/compliance", handler: h190 },
  { pattern: "/api/internal/esg-scores", handler: h191 },
  { pattern: "/api/internal/onboarding", handler: h192 },
  { pattern: "/api/internal/scorecards", handler: h193 },
  { pattern: "/api/internal/workspaces", handler: h194 },
  { pattern: "/api/sales/sync-invoices", handler: h195 },
  { pattern: "/api/shopify/collections", handler: h196 },
  { pattern: "/api/cron/push-delivery", handler: h197 },
  { pattern: "/api/internal/anomalies", handler: h198 },
  { pattern: "/api/internal/contracts", handler: h199 },
  { pattern: "/api/vendor/attachments", handler: h200 },
  { pattern: "/api/xoro/probe-filters", handler: h201 },
  { pattern: "/api/xoro/sales-history", handler: h202 },
  { pattern: "/api/cron/fx-rate-sync", handler: h203 },
  { pattern: "/api/internal/disputes", handler: h204 },
  { pattern: "/api/internal/entities", handler: h205 },
  { pattern: "/api/internal/style-master/:id", handler: h252 },
  { pattern: "/api/internal/style-master", handler: h251 },
  { pattern: "/api/internal/vendor-master/:id", handler: h254 },
  { pattern: "/api/internal/vendor-master", handler: h253 },
  { pattern: "/api/internal/customer-master/:id", handler: h256 },
  { pattern: "/api/internal/customer-master", handler: h255 },
  { pattern: "/api/internal/gl-accounts/:id", handler: h258 },
  { pattern: "/api/internal/gl-accounts", handler: h257 },
  { pattern: "/api/internal/gl-periods/:id", handler: h260 },
  { pattern: "/api/internal/gl-periods", handler: h259 },
  { pattern: "/api/internal/journal-entries/:id/reverse", handler: h263 },
  { pattern: "/api/internal/journal-entries/:id", handler: h262 },
  { pattern: "/api/internal/journal-entries", handler: h261 },
  { pattern: "/api/internal/approval-requests/:id/decide", handler: h268 },
  { pattern: "/api/internal/approval-requests/:id/cancel", handler: h269 },
  { pattern: "/api/internal/approval-requests/:id", handler: h267 },
  { pattern: "/api/internal/approval-requests", handler: h266 },
  { pattern: "/api/internal/approval-rules/:id", handler: h265 },
  { pattern: "/api/internal/approval-rules", handler: h264 },
  { pattern: "/api/internal/notifications/:id/mark-read", handler: h271 },
  { pattern: "/api/internal/notifications", handler: h270 },
  { pattern: "/api/internal/notification-preferences", handler: h272 },
  { pattern: "/api/internal/documents/:id/signed-url", handler: h274 },
  { pattern: "/api/internal/documents/:id/archive", handler: h275 },
  { pattern: "/api/internal/documents", handler: h273 },
  { pattern: "/api/internal/employees/:id", handler: h277 },
  { pattern: "/api/internal/employees", handler: h276 },
  { pattern: "/api/internal/auth/provision", handler: h278 },
  { pattern: "/api/internal/inventory-transfers", handler: h279 },
  // Inventory adjustments — subpath /:id/post BEFORE bare /:id (first-match-wins)
  { pattern: "/api/internal/inventory-adjustments/:id/post", handler: h297 },
  { pattern: "/api/internal/inventory-adjustments/:id", handler: h296 },
  { pattern: "/api/internal/inventory-adjustments", handler: h295 },
  // Scanner — subpaths BEFORE /:id parent (first-match-wins dispatcher)
  { pattern: "/api/internal/scanner/events/batch", handler: h280 },
  { pattern: "/api/internal/scanner/sessions/:id/submit", handler: h281 },
  { pattern: "/api/internal/scanner/sessions/:id/cancel", handler: h282 },
  { pattern: "/api/internal/scanner/sessions/:id", handler: h283 },
  { pattern: "/api/internal/scanner/sessions", handler: h284 },
  // AP — subpaths BEFORE /:id parent (first-match-wins dispatcher)
  { pattern: "/api/internal/ap-invoices/:id/post", handler: h287 },
  { pattern: "/api/internal/ap-invoices/:id/pay", handler: h288 },
  { pattern: "/api/internal/ap-invoices/:id/void", handler: h289 },
  { pattern: "/api/internal/ap-invoices/:id", handler: h286 },
  { pattern: "/api/internal/ap-invoices", handler: h285 },
  { pattern: "/api/internal/ap-payments", handler: h290 },
  // Fabric Codes (P3-11) — subpaths-before-parent
  { pattern: "/api/internal/fabric-codes/:id", handler: h292 },
  { pattern: "/api/internal/fabric-codes", handler: h291 },
  { pattern: "/api/internal/style-fabric-codes/:id", handler: h294 },
  { pattern: "/api/internal/style-fabric-codes", handler: h293 },
  // Payment Terms (P3-9) — :id before bare collection (first-match-wins)
  { pattern: "/api/internal/payment-terms/:id", handler: h303 },
  { pattern: "/api/internal/payment-terms", handler: h302 },
  // Cycle Counts (P3-6) — subpaths BEFORE /:id (first-match-wins)
  { pattern: "/api/internal/inventory-cycle-counts/:id/finalize", handler: h301 },
  { pattern: "/api/internal/inventory-cycle-counts/:id/lines/:line_id", handler: h300 },
  { pattern: "/api/internal/inventory-cycle-counts/:id", handler: h299 },
  { pattern: "/api/internal/inventory-cycle-counts", handler: h298 },
  { pattern: "/api/internal/insights", handler: h206 },
  { pattern: "/api/internal/payments", handler: h207 },
  { pattern: "/api/shopify/inventory", handler: h208 },
  { pattern: "/api/vendor/compliance", handler: h209 },
  { pattern: "/api/vendor/onboarding", handler: h210 },
  { pattern: "/api/vendor/workspaces", handler: h211 },
  { pattern: "/api/internal/vendors", handler: h212 },
  { pattern: "/api/shopify/products", handler: h213 },
  { pattern: "/api/vendor/contracts", handler: h214 },
  { pattern: "/api/vendor/esg-score", handler: h215 },
  { pattern: "/api/vendor/scorecard", handler: h216 },
  { pattern: "/api/vendor/shipments", handler: h217 },
  { pattern: "/api/shopify/returns", handler: h218 },
  { pattern: "/api/vendor/api-keys", handler: h219 },
  { pattern: "/api/vendor/disputes", handler: h220 },
  { pattern: "/api/vendor/entities", handler: h221 },
  { pattern: "/api/vendor/invoices", handler: h222 },
  { pattern: "/api/vendor/payments", handler: h223 },
  { pattern: "/api/shopify/orders", handler: h224 },
  { pattern: "/api/vendor/banking", handler: h225 },
  { pattern: "/api/internal/rfqs", handler: h226 },
  { pattern: "/api/xoro/open-pos", handler: h227 },
  { pattern: "/api/xoro/receipts", handler: h229 },
  { pattern: "/api/ai/ask-grid", handler: h230 },
  { pattern: "/api/edi/inbound", handler: h231 },
  { pattern: "/api/master/sync", handler: h232 },
  { pattern: "/api/vendor/bulk", handler: h233 },
  { pattern: "/api/vendor/rfqs", handler: h234 },
  { pattern: "/api/ats/upload", handler: h235 },
  { pattern: "/api/vendor/erp", handler: h236 },
  { pattern: "/api/xoro/items", handler: h237 },
  { pattern: "/api/xoro-items-missing-sync", handler: h238 },
  { pattern: "/api/xoro-receipts-sync", handler: h239 },
  { pattern: "/api/send-notification", handler: h240 },
  { pattern: "/api/ats-supply-sync", handler: h241 },
  { pattern: "/api/xoro-sales-sync", handler: h242 },
  { pattern: "/api/searates-proxy", handler: h243 },
  { pattern: "/api/tanda-pos-sync", handler: h244 },
  { pattern: "/api/dropbox-proxy", handler: h245 },
  { pattern: "/api/vendor-invite", handler: h246 },
  { pattern: "/api/xoro-ap-sync", handler: h247 },
  { pattern: "/api/parse-excel", handler: h248 },
  { pattern: "/api/xoro-proxy", handler: h249 },
  { pattern: "/api/sales/backfill-grain", handler: h250 },
  // P4-4 — AR Invoices admin. Subpath routes BEFORE bare :id.
  { pattern: "/api/internal/ar-invoices/:id/post", handler: h306 },
  { pattern: "/api/internal/ar-invoices/:id/void", handler: h307 },
  { pattern: "/api/internal/ar-invoices/:id", handler: h305 },
  { pattern: "/api/internal/ar-invoices", handler: h304 },
  // P4-5 — AR Receipts admin (h308..h312). Subpath routes BEFORE bare :id.
  { pattern: "/api/internal/ar-receipts/:id/post", handler: h310 },
  { pattern: "/api/internal/ar-receipts/:id/void", handler: h311 },
  { pattern: "/api/internal/ar-receipts/:id", handler: h309 },
  { pattern: "/api/internal/ar-receipts", handler: h308 },
  { pattern: "/api/internal/ar-receipt-applications/:id", handler: h312 },
  // P4-6 — AR Aging GET (h313).
  { pattern: "/api/internal/ar-aging", handler: h313 },
  // P4-8 — AR historical backfill (h314 POST run + h315 GET status).
  { pattern: "/api/internal/ar-backfill/run", handler: h314 },
  { pattern: "/api/internal/ar-backfill/status", handler: h315 },
  // P5-1 — Period close mechanics.
  { pattern: "/api/internal/gl-periods/:id/close", handler: h316 },
  { pattern: "/api/internal/gl-periods/:id/reopen", handler: h317 },
  // P5-2 — Trial Balance GET (h318).
  { pattern: "/api/internal/trial-balance", handler: h318 },
  // P5-3 — Income Statement GET (h319).
  { pattern: "/api/internal/income-statement", handler: h319 },
  // P5-4 — Balance Sheet GET (h320).
  { pattern: "/api/internal/balance-sheet", handler: h320 },
  // P5-5 — Cash Flow Statement GET (h321).
  { pattern: "/api/internal/cash-flow", handler: h321 },
  // P5-6 — Year-End Close runner.
  { pattern: "/api/internal/year-end-close/run", handler: h322 },
  // P5-7 — Period-close pre-flight check.
  { pattern: "/api/internal/gl-periods/:id/preflight", handler: h323 },
  // P6-2 — Plaid Link integration + sync cron + webhook.
  { pattern: "/api/internal/bank-feeds/link-token", handler: h324 },
  { pattern: "/api/internal/bank-feeds/exchange",   handler: h325 },
  { pattern: "/api/cron/bank-feed-sync",            handler: h326 },
  { pattern: "/api/webhooks/plaid",                 handler: h327 },
  // P6-3 — Bank CSV upload.
  { pattern: "/api/internal/bank-feeds/csv-upload", handler: h328 },
  // P6-5 — Bank reconciliation admin endpoints. Subpath actions BEFORE bare /:id semantics.
  { pattern: "/api/internal/bank-transactions/:id/match-candidates", handler: h331 },
  { pattern: "/api/internal/bank-transactions/:id/apply-match",       handler: h332 },
  { pattern: "/api/internal/bank-transactions/:id/unmatch",           handler: h333 },
  { pattern: "/api/internal/bank-transactions/:id/create-je",         handler: h334 },
  { pattern: "/api/internal/bank-transactions/:id/ignore",            handler: h335 },
  { pattern: "/api/internal/bank-transactions",                       handler: h330 },
  { pattern: "/api/internal/bank-accounts/:id",                       handler: h339 },
  { pattern: "/api/internal/bank-accounts",                           handler: h329 },
  // P6-7 — Auto-post fee rules cron + manual trigger.
  { pattern: "/api/cron/bank-auto-post-fees",                         handler: h340 },
  // P7-5 — Commission accrue/reverse/settle RPCs + list endpoints.
  { pattern: "/api/internal/commissions/accrue",                      handler: h341 },
  { pattern: "/api/internal/commissions/reverse",                     handler: h342 },
  { pattern: "/api/internal/commissions/settle",                      handler: h343 },
  { pattern: "/api/internal/commissions/accruals",                    handler: h344 },
  { pattern: "/api/internal/commissions/payouts",                     handler: h345 },
  // P7-7 — M9-subset operational reports under the new 📊 Reports menu group.
  { pattern: "/api/internal/ap-aging",                                handler: h346 },
  { pattern: "/api/internal/sales-by-rep",                            handler: h347 },
  { pattern: "/api/internal/sales-by-customer",                       handler: h348 },
  { pattern: "/api/internal/gl-detail",                               handler: h349 },
  // P7-9 — Customer Service / Cases. Subpath BEFORE bare /:id route.
  { pattern: "/api/internal/cases/:id/comments",                      handler: h352 },
  { pattern: "/api/internal/cases/:id",                               handler: h351 },
  { pattern: "/api/internal/cases",                                   handler: h350 },
  { pattern: "/api/webhooks/resend-inbound",                          handler: h353 },
  // P8-2 — CRM (M25). Subpath routes BEFORE bare /:id routes.
  { pattern: "/api/internal/crm/opportunities/:id/stage",             handler: h362 },
  { pattern: "/api/internal/crm/opportunities/:id",                   handler: h361 },
  { pattern: "/api/internal/crm/opportunities",                       handler: h360 },
  { pattern: "/api/internal/crm/activities/:id",                      handler: h364 },
  { pattern: "/api/internal/crm/activities",                          handler: h363 },
  { pattern: "/api/internal/crm/tasks/:id",                           handler: h366 },
  { pattern: "/api/internal/crm/tasks",                               handler: h365 },
  { pattern: "/api/internal/crm/pipeline-report",                     handler: h367 },
  // T10-2 — Cross-cutter Xoro shadow mirror, AR domain manual trigger.
  { pattern: "/api/internal/xoro-mirror/ar",                          handler: h400 },
  // T10-5 — Cross-cutter Xoro shadow mirror, daily summary JE poster.
  { pattern: "/api/internal/xoro-mirror/summary-je",                  handler: h403 },
  // T10-6 — Nightly Xoro mirror orchestrator cron (Vercel schedule 30 1 * * *).
  { pattern: "/api/cron/xoro-mirror-nightly",                         handler: h404 },
  // T4-1 — Cross-cutter Personalization click-decay cron (Vercel schedule 0 3 * * *).
  { pattern: "/api/cron/menu-usage-decay",                            handler: h420 },
  // P8-7 — PIM images. Specific subpaths BEFORE the bare /:id route.
  // Image routes must come BEFORE the bare /:style_id route from P8-6 so
  // /styles/:style_id/images/... gets matched first.
  { pattern: "/api/internal/pim/styles/:style_id/images/:id/signed-url", handler: h383 },
  { pattern: "/api/internal/pim/styles/:style_id/images/:id/delete",     handler: h382 },
  { pattern: "/api/internal/pim/styles/:style_id/images/:id",            handler: h381 },
  { pattern: "/api/internal/pim/styles/:style_id/images",                handler: h380 },
  // P8-6 — PIM (M42) non-image endpoints.
  // Subpath actions MUST come before bare /:style_id and /:id routes.
  { pattern: "/api/internal/pim/styles/:style_id/description/publish", handler: h377 },
  { pattern: "/api/internal/pim/styles/:style_id/description",         handler: h376 },
  { pattern: "/api/internal/pim/styles/:style_id/attributes",          handler: h375 },
  { pattern: "/api/internal/pim/styles/:style_id",                     handler: h374 },
  { pattern: "/api/internal/pim/attribute-defs/:id",                   handler: h373 },
  { pattern: "/api/internal/pim/attribute-defs",                       handler: h372 },
  { pattern: "/api/internal/pim/categories/:id",                       handler: h371 },
  { pattern: "/api/internal/pim/categories",                           handler: h370 },
  // T10-3 — Xoro shadow-mirror AP domain (manual trigger).
  { pattern: "/api/internal/xoro-mirror/ap",                           handler: h401 },
  // T6-2 — Global full-text search across the 11 v1 entities.
  { pattern: "/api/internal/search",                                   handler: h426 },
  // T4-2 — Cross-cutter Personalization (favorites + auto-landing + click telemetry).
  // Subpath PUT/POST routes registered BEFORE the bare /preferences GET so
  // /preferences/favorites and /preferences/home-route match their dedicated
  // handlers (not the bare-GET map) when the dispatcher walks ROUTES top-down.
  { pattern: "/api/internal/users/me/preferences/favorites",           handler: h422 },
  { pattern: "/api/internal/users/me/preferences/home-route",          handler: h423 },
  { pattern: "/api/internal/users/me/preferences",                     handler: h421 },
  { pattern: "/api/internal/users/me/menu-click",                      handler: h424 },
  { pattern: "/api/internal/users/me/menu-usage/top",                  handler: h425 },
  // P10-2b — Entity-switcher API. Subpath PUT routes registered BEFORE the
  // bare GET so /entity-switch and /entity-default match their dedicated
  // handlers (not the bare /entities GET) when the dispatcher walks
  // ROUTES top-down. The three paths don't actually overlap, but the
  // convention is "subpaths-first" and we keep the audit trail consistent.
  { pattern: "/api/internal/users/me/entity-switch",                   handler: h430 },
  { pattern: "/api/internal/users/me/entity-default",                  handler: h431 },
  { pattern: "/api/internal/users/me/entities",                        handler: h432 },
  // P12b-2 — Walmart Marketplace orders ingest.
  { pattern: "/api/internal/walmart/sync-orders",                      handler: h452 },
  { pattern: "/api/cron/walmart-orders-nightly",                       handler: h453 },
  // P12c-2 — Faire wholesale marketplace ingest (manual triggers + crons).
  { pattern: "/api/internal/faire/sync-orders",                        handler: h454 },
  { pattern: "/api/cron/faire-orders-nightly",                         handler: h455 },
  { pattern: "/api/internal/faire/sync-payouts",                       handler: h456 },
  { pattern: "/api/cron/faire-payouts-monthly",                        handler: h457 },
  // P11-3 — Shopify AR JE posting manual backfill.
  { pattern: "/api/internal/shopify/post-order/:id",                   handler: h441 },
  // P11-9 — Shopify Payments payout reconciliation manual trigger + cron.
  { pattern: "/api/internal/shopify/sync-payouts",                     handler: h444 },
  { pattern: "/api/cron/shopify-payouts-daily",                        handler: h445 },
  // P11-2 — Shopify orders webhook intake.
  { pattern: "/api/internal/shopify/webhooks/orders",                  handler: h440 },
  // P11-4 — Shopify backfill cron + manual trigger (webhook-drop safety net).
  { pattern: "/api/internal/shopify/backfill",                         handler: h442 },
  { pattern: "/api/cron/shopify-backfill",                             handler: h443 },
  // P12a-2 — Amazon FBA SP-API orders ingest.
  { pattern: "/api/internal/fba/sync-orders",                          handler: h450 },
  { pattern: "/api/cron/fba-orders-nightly",                           handler: h451 },
  // P12a-3 — Amazon FBA AR invoice JE posting (manual backfill).
  { pattern: "/api/internal/fba/post-order/:id",                       handler: h458 },
  // P12b-3 — Walmart AR JE posting manual backfill.
  { pattern: "/api/internal/walmart/post-order/:id",                   handler: h459 },
  // P12b-4 — Walmart Marketplace settlement reconciliation.
  { pattern: "/api/internal/walmart/sync-settlements",                 handler: h464 },
  { pattern: "/api/cron/walmart-settlements-weekly",                   handler: h465 },
  // P12c-4 — Faire wholesale returns ingest (credit memo + restock).
  { pattern: "/api/internal/faire/sync-returns",                       handler: h473 },
  { pattern: "/api/cron/faire-returns-weekly",                         handler: h474 },
  // P12b-5 — Walmart returns sync (credit memo + restock + restocking fee).
  { pattern: "/api/internal/walmart/sync-returns",                     handler: h471 },
  { pattern: "/api/cron/walmart-returns-daily",                        handler: h472 },
  // P11-8 — Shopify dispute (chargeback) webhook intake.
  { pattern: "/api/internal/shopify/webhooks/disputes",                handler: h466 },
  // Cross-cutter T11-3 — Universal audit log read endpoints.
  { pattern: "/api/internal/audit/row-history",                        handler: h485 },
  { pattern: "/api/internal/audit/log",                                handler: h486 },
  // Costing Module — Chunk 2 (CRUD + autocompletes + select-quote stub).
  { pattern: "/api/internal/costing/projects",                         handler: h475 },
  { pattern: "/api/internal/costing/projects/:id",                     handler: h476 },
  { pattern: "/api/internal/costing/projects/:id/lines",               handler: h477 },
  { pattern: "/api/internal/costing/lines/:line_id",                   handler: h478 },
  { pattern: "/api/internal/costing/lines/:line_id/quotes",            handler: h479 },
  { pattern: "/api/internal/costing/lines/:line_id/quotes/:quote_id",  handler: h480 },
  { pattern: "/api/internal/costing/lines/:line_id/select-quote",      handler: h481 },
  { pattern: "/api/internal/costing/search/styles",                    handler: h482 },
  { pattern: "/api/internal/costing/search/vendors",                   handler: h483 },
  { pattern: "/api/internal/costing/search/customers",                 handler: h484 },
  { pattern: "/api/internal/costing/search/sales-reps",                handler: h493 },
  { pattern: "/api/internal/costing/search/fabrics",                   handler: h494 },
  { pattern: "/api/internal/costing/search/categories",                handler: h495 },
  { pattern: "/api/internal/costing/search/scales",                    handler: h496 },
  // Costing Module — Chunk 5 (LY + trailing-3-month comp aggregation).
  { pattern: "/api/internal/costing/comp/ly",                          handler: h489 },
  { pattern: "/api/internal/costing/comp/t3",                          handler: h490 },
  // Costing Module — Chunk 7 (compliance checklist handlers).
  { pattern: "/api/internal/costing/lines/:line_id/compliance",            handler: h491 },
  { pattern: "/api/internal/costing/lines/:line_id/compliance/:req_id",    handler: h492 },
];

export function compileRoutes(routes) {
  return routes.map((r) => {
    const segs = r.pattern.split("/").filter(Boolean);
    const params = [];
    const regexParts = segs.map((seg) => {
      if (seg.startsWith(":")) { params.push(seg.slice(1)); return "([^/]+)"; }
      if (seg.startsWith("*")) { params.push(seg.slice(1)); return "(.+)"; }
      return seg.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    });
    const regex = new RegExp("^/" + regexParts.join("/") + "/?$");
    return { ...r, regex, params };
  });
}
