-- ════════════════════════════════════════════════════════════════════════════
-- Merge non-PL color-casing DUPLICATE SKUs (operator-approved, 2026-06-13).
--
-- After 20260869000000 renamed non-PL SKU colors to canonical, ~119 cells still
-- held TWO SKU rows for the same (style, populated size, inseam) — one already
-- canonical, one a color-casing variant that could not be renamed (would collide
-- on the logical-unique index). These are genuine same-product duplicates; we
-- merge the variant (loser) into the canonical SKU (survivor) via the existing
-- collision-aware merge_item_master_dups() — it re-points inventory layers + all
-- FK refs, sums on-hand, backfills survivor cols, and drops the loser row.
--
-- Snapshots the loser rows + their inventory_layers first (audit / partial
-- recovery). EXCLUDES private-label (%PL) styles and all null-size collisions.
-- ════════════════════════════════════════════════════════════════════════════

CREATE TEMP TABLE _cmap(raw text, canon text) ON COMMIT DROP;
INSERT INTO _cmap(raw, canon) VALUES
('BLACK','Black'),
('VANISH-DK BLUE','Vanish-Dark Blue'),
('CHARCOAL','Charcoal'),
('SHIITAKE','Shiitake'),
('BELOW ZERO- LT WASH','Below Zero- Light Wash'),
('RINSE - DKBLUE','Rinse - DkBlue'),
('NAVY','Navy'),
('BLCK PARADISE','Black Paradise'),
('OLIVE','Olive'),
('KHAKI','Khaki'),
('BROWN','Brown'),
('MUSHROOM','Mushroom'),
('Blck Paradise','Black Paradise'),
('Lt Brown','Light Brown'),
('Blk Camo','Black Camo'),
('AMERICANA','Americana'),
('Lt Grey','Light Grey'),
('Smoke Blue - Lt Blue','Smoke Blue - Light Blue'),
('BERMUDA - LT WASH','Bermuda - Light Wash'),
('HARBOR - MED WASH','Harbor - Medium Wash'),
('Vanish-Dk Blue','Vanish-Dark Blue'),
('Dutch Wash- Med','Dutch Wash- Medium'),
('WHITE','White'),
('Crumble-MD BLU','Crumble-Medium BLU'),
('Charcoal Hthr','Charcoal Heather'),
('Carbon- Blck','Carbon- Black'),
('Mineral- Lt Blue','Mineral- Light Blue'),
('CASPAIN - LT WASH','Caspain - Light Wash'),
('SEA FLOOR - MED WASH','Sea Floor - Medium Wash'),
('Below Zero- Lt Wash','Below Zero- Light Wash'),
('BUENOS AIRES - LT WASH','Buenos Aires - Light Wash'),
('PYRITE-MED DARK WASH','PYRITE-Medium Dark Wash'),
('ISLAND BREEZE','Island Breeze'),
('VERNAULK - LT WASH','Vernaulk - Light Wash'),
('DEEP BLACK','Deep Black'),
('Skyline- Md Lt','Skyline- Medium Light'),
('Medusa-Dk Blue','Medusa-Dark Blue'),
('BLK CAMO','Black Camo'),
('GORDON - LT WASH','Gordon - Light Wash'),
('T16 Vtg Blk/Oyst Mushroom','T16 Vtg Black/Oyst Mushroom'),
('New Wheat- Md Dark','New Wheat- Medium Dark'),
('HAMMOCK','Hammock'),
('DRESS BLUES','Dress Blues'),
('Medm Hthr Gry','Medium Heather Grey'),
('CubanSnd- Md Wash','CubanSnd- Medium Wash'),
('ICEBERG GREEN','Iceberg Green'),
('SKY BLUE','Sky Blue'),
('Rust-Dk Blue','Rust-Dark Blue'),
('FOREST NIGHT','Forest Night'),
('Heather Gray','Heather Grey'),
('FLEETWOOD - MED WASH','Fleetwood - Medium Wash'),
('CLOUD DANCER','Cloud Dancer'),
('Blk/Chrc Hthr','Black/Charcoal Heather'),
('Sandlot - Med Wash','Sandlot - Medium Wash'),
('STEEL GREY','Steel Grey'),
('Lt Blue','Light Blue'),
('Drought Wash - Med Light','Drought Wash - Medium Light'),
('WALNUT','Walnut'),
('OYSTER MUSHROOM','Oyster Mushroom'),
('Mushroom- Lt Grey','Mushroom- Light Grey'),
('VALLARTA BLUE','Vallarta Blue'),
('GRAPE WINE MANTA','Grape Wine Manta'),
('RAINDROPS','Raindrops'),
('MOONLESS NIGHTS MANTA','Moonless Nights Manta'),
('Creek - Md Lt Wash','Creek - Medium Light Wash'),
('LIGHT OLIVE','Light Olive'),
('BRUSHED ALLOY','Brushed Alloy'),
('skyway','Skyway'),
('DEEP TEAL','Deep Teal'),
('Beach Wash - Lt Wash','Beach Wash - Light Wash'),
('LT BROWN','Light Brown'),
('EATON - LT WASH','Eaton - Light Wash'),
('Buenos Aires - Lt Wash','Buenos Aires - Light Wash'),
('Media Park- Drk Wash','Media Park- Dark Wash'),
('Black/Gray','Black/Grey'),
('LAVENDER','Lavender'),
('Aruba- Md Wash','Aruba- Medium Wash'),
('DARK OLIVE','Dark Olive'),
('GREEN CAMO','Green Camo'),
('Sediment - Lt Wash','Sediment - Light Wash'),
('SODALITE BLUE','Sodalite Blue'),
('GLACIER','Glacier'),
('MOONLESS NIGHTS','Moonless Nights'),
('Black Hthr','Black Heather'),
('ROASTED CASHEW','Roasted Cashew'),
('Blue Stone - Med Wash','Blue Stone - Medium Wash'),
('DAIQUIRI GREEN','Daiquiri Green'),
('NAVAL ACADEMY','Naval Academy'),
('Crow - Washed Blk','Crow - Washed Black'),
('SAND MARLED','Sand Marled'),
('Gateway - Med Wash','Gateway - Medium Wash'),
('Robin - Md Blue','Robin - Medium Blue'),
('Navy Hthr','Navy Heather'),
('Cole - Med Wash','Cole - Medium Wash'),
('Cobalt - Dk Blue','Cobalt - Dark Blue'),
('INDIGO MARLED','Indigo Marled'),
('RED','Red'),
('Willow - Dk Blue','Willow - Dark Blue'),
('SANTORINI - LT WASH','Santorini - Light Wash'),
('LT GREY','Light Grey'),
('Azul - Md Blue','Azul - Medium Blue'),
('GRAPE WINE','Grape Wine'),
('TIBETAN RED','Tibetan Red'),
('Skylar - Lt Blue','Skylar-LtBlue'),
('Caspain - Lt Wash','Caspain - Light Wash'),
('Manila - Lt Wash w Tint','Manila - Light Wash w Tint'),
('Palms- Md Lt Wash','Palms- Medium Light Wash'),
('WASHED CHARCOAL','Washed Charcoal'),
('Periwinkle- Lt Wash','Periwinkle- Light Wash'),
('ISLAND BREEZE LT WASH','Island Breeze Light wash'),
('Flow Wash - Lt Wash','Flow Wash - Light Wash'),
('Saltwater - Med Wash','Saltwater - Medium Wash'),
('BLK Camo','Black Camo'),
('Lt Pink','Light Pink'),
('SUN KISSED CORAL','Sun Kissed Coral'),
('BLACK WATER CAMO','Black Water Camo'),
('OCEAN HUT','Ocean Hut'),
('CAVE - Lt Wash','CAVE - Light Wash'),
('Vernaulk - Lt Wash','Vernaulk - Light Wash'),
('IBIZA - MD WASH','Ibiza - Medium Wash'),
('BAYOU - MED WASH','Bayou - Medium Wash'),
('Sea shell','Seashell'),
('FALCON','Falcon'),
('PARADISE GREEN','Paradise Green'),
('MARINE- MD WASH','Marine- Medium Wash'),
('Eaton - Med Wash','Eaton - Medium Wash'),
('Sbltd Blk Camo','Sbltd Black Camo'),
('LIGHT WASH','Light Wash'),
('Dusk--Med Blue','Dusk--Medium Blue'),
('CANNES - MED WASH','Cannes - Medium Wash'),
('Mist Blue- Lt Wash','Mist Blue- Light Wash'),
('OxBloodCamo','Oxblood Camo'),
('GREY','Grey'),
('STORMY WEATHER','Stormy Weather'),
('SEASHELL','Seashell'),
('CARBON- Dk Wash','CARBON- Dark Wash'),
('OBSIDIAN','Obsidian'),
('Forget Me Not','Forget-Me-Not'),
('Chrcl Hthr','Charcoal Heather'),
('SEA OTTER','Sea Otter'),
('NVY','Navy'),
('LASSO WASH - DK WASH','Lasso Wash - Dark Wash'),
('TYPHOON','Typhoon'),
('HORIZON','Horizon'),
('FIN GD','Fin Gd'),
('Harbor - Med Wash','Harbor - Medium Wash'),
('ET SURFBOARD','Et Surfboard'),
('Blue Island - Md Lt Wash','Blue Island - Medium Light Wash'),
('REVISED SURF HUT','Revised Surf Hut'),
('HERITAGE SURF','Heritage Surf'),
('Bermuda - Lt Wash','Bermuda - Light Wash'),
('SHADOW GREEN','Shadow Green'),
('SURFER SUPPLY','Surfer Supply'),
('DULL GOLD','Dull Gold'),
('YELLOW CREAM','Yellow Cream'),
('Ibiza - Med Wash','Ibiza - Medium Wash'),
('MELTFIELD - Med Wash w Tint','MELTFIELD - Medium Wash w Tint'),
('IVY- Dk Wash','IVY- Dark Wash'),
('PEACH ECHO','Peach Echo'),
('Saint Lucia- Med Wash','Saint Lucia- Medium Wash'),
('BLUE RADIANCE','Blue Radiance'),
('Lasso Wash - Dk Wash','Lasso Wash - Dark Wash'),
('SURF HUT','Surf Hut'),
('BIRCH','Birch'),
('RUST - DK Blue','Rust-Dark Blue'),
('IRON BLUE - LT WASH','Iron Blue - Light Wash'),
('MAGIC MAUVE','Magic Mauve'),
('Luna-Lt Wash','Luna-Light Wash'),
('Lt. Grey Hthr','Light Grey Heather'),
('BLACK / YELLOW','Black / Yellow'),
('ULTRAMARINE - MED WASH','Ultramarine - Medium Wash'),
('THUNDERBOLT - DARK WASH','Thunderbolt - Dark Wash'),
('BlK/Blk','Black/Black'),
('Blk/Charcoal','Black/Charcoal'),
('BLUE FANG - LT WASH','Blue Fang - Light Wash'),
('BLUE HAWK - DARK WASH','Blue Hawk - Dark Wash'),
('STONE BLOCK GD','Stone Block Gd'),
('STEEL BLUE - LT WASH','Steel Blue - Light Wash'),
('Steam Wash - Lt Wash','Steam Wash - Light Wash'),
('Static - Blk Acid Wash','Static - Black Acid Wash'),
('Spring Water - Lt Wash','Spring Water - Light Wash'),
('CADET BLUE - MED WASH','Cadet Blue - Medium Wash'),
('Charcoal Blk','Charcoal Black'),
('CHESTNUT','Chestnut'),
('Sea Floor - Med Wash','Sea Floor - Medium Wash'),
('FRAGILE OCEAN','Fragile Ocean'),
('OYSTER','Oyster'),
('OXFORD - MED WASH','Oxford - Medium Wash'),
('WASHED BROWN','Washed Brown'),
('BYRON BAY - MED WASH','Byron Bay - Medium Wash'),
('Gray Storm','Grey Storm'),
('Blue Stone Med Wash','Blue Stone - Medium Wash'),
('Miami - Lt Blue','Miami - Light Blue'),
('FORGET-ME-NOT','Forget-Me-Not'),
('T1 BLACK','T1 Black'),
('IBIZA - MED WASH','Ibiza - Medium Wash'),
('Nv/Lt HthrGry','Nv/Light HthrGry'),
('Caribbean - Med Wash','Caribbean - Medium Wash'),
('Moisture - Med Wash','Moisture - Medium Wash'),
('Lt Grey Cali Bear','Light Grey Cali Bear'),
('SOUTH COAST','South Coast'),
('Burgndy/Off White','Burgundy/Off White'),
('Burgndy/Chrcl','Burgundy/Charcoal'),
('STEAM WASH - LT WASH','Steam Wash - Light Wash'),
('NewCastle-DK Wsh','NewCastle-Dark Wash'),
('STEAM WASH-LT WASH','Steam Wash - Light Wash'),
('Neptune - Med Wash','Neptune - Medium Wash'),
('BRIG SURF','Brig Surf'),
('Boreal Blue - Med Wash w Tint','Boreal Blue - Medium Wash w Tint'),
('Sulphur Wash- Dk Grey','Sulphur Wash- Dark Grey'),
('Surf - Lt Wash','Surf - Light Wash'),
('SURF CITY','Surf City'),
('Blk/Lt. Hthr Gry','Black/Light Heather Grey'),
('Misty Bay - Lt Wash','Misty Bay - Light Wash'),
('THALIA','Thalia'),
('Mist Drift - Lt Wash','Mist Drift - Light Wash'),
('ALEGRIA-Md Dark','ALEGRIA-Medium Dark'),
('Blacksands - Blk Wash wTint','Blacksands - Black Wash wTint'),
('VEIL - DARK WASH','Veil - Dark Wash'),
('MEDIUM WASH','Medium Wash'),
('Lt Grey/Charcoal','Light Grey/Charcoal'),
('PEPPER - ACID GREY','PEPPER - Acid Grey'),
('Everglades - Med Wash','Everglades - Medium Wash'),
('PLACID - LT WASH','Placid - Light Wash'),
('POND - MED WASH','Pond - Medium Wash'),
('ELKMONT TRADING','Elkmont Trading'),
('Eclipse - Med Wash','Eclipse - Medium Wash'),
('Eaton - Lt Wash','Eaton - Light Wash'),
('DULL GOLD GD','Dull Gold Gd'),
('Driftwood - Med Wash','Driftwood - Medium Wash'),
('Dk Teal','Dark Teal'),
('Fossil - Med Grey','Fossil - Medium Grey'),
('Rocky - Med Grey','Rocky - Medium Grey'),
('APRICOT','Apricot'),
('RUST - DK BLUE','Rust-Dark Blue'),
('SAGE','Sage'),
('Volt - Med Wash w Tint','Volt - Medium Wash w Tint'),
('Currents - Lt Wash','Currents - Light Wash'),
('Saltwater Sky - Lt Wash w Tint','Saltwater Sky - Light Wash w Tint'),
('Sandcastle - Lt Wash','Sandcastle - Light Wash'),
('Sea Breeze- Lt Wash','Sea Breeze- Light Wash'),
('Sea Mist - Lt Wash','Sea Mist - Light Wash'),
('Cinder - Lt Grey','Cinder - Light Grey'),
('Sea Spray - Lt Wash w Tint','Sea Spray - Light Wash w Tint'),
('Seal - Lt Grey','Seal - Light Grey'),
('Gray Wolf - Lt Gray','Grey Wolf - Light Grey'),
('Oceanside - Med Wash','Oceanside - Medium Wash'),
('Char Grn','Char Green'),
('CREEK - MD LT WASH','Creek - Medium Light Wash'),
('DARK WASH','Dark Wash'),
('ESPRESSO','Espresso'),
('GATEWAY - MED WASH','Gateway - Medium Wash'),
('HOBIE SURF','Hobie Surf'),
('Hthr Chrcl/Yellow','Heather Charcoal/Yellow'),
('Island Breeze lt wash','Island Breeze Light wash'),
('JACKS SURFBOARDS','Jacks Surfboards'),
('KRAKEN','Kraken'),
('Marine- Md Wash','Marine- Medium Wash'),
('Med Blue','Medium Blue'),
('New Lands - Md Lt Wash','New Lands - Medium Light Wash'),
('Oasis- Med Wash','Oasis- Medium Wash'),
('PINK OMBRE WASH','Pink Ombre Wash'),
('PYRITE-Med Dark Wash','PYRITE-Medium Dark Wash'),
('SangrOmni/Blk','SangrOmni/Black'),
('SEAPORT - MED WASH','Seaport - Medium Wash'),
('SEDIMENT - LT WASH','Sediment - Light Wash'),
('SHOREBREAK','Shorebreak'),
('SURF, WIND & FIRE','Surf, Wind & Fire'),
('TONAL GREY CAMO','Tonal Grey Camo'),
('Washed Olive','WASHED Olive'),
('WAVE RIDING VEHICLES','Wave Riding Vehicles'),
('STORM CAMO','Storm Camo'),
('Black/Lt Grey','Black/Light Grey'),
('Black/Black Marl','Black/Black Marled'),
('Shadow Wash- Dk','Shadow Wash- Dark'),
('Smokey- Drk Grey','Smokey- Dark Grey'),
('Drk Trpcl Gry','Dark Tropical Grey'),
('DOUBLE DUFF - LT WASH','Double Duff - Light Wash'),
('DEEP BLUE','Deep Blue'),
('BLUE JEAN','Blue Jean'),
('Lt Hthr Gry','Light Heather Grey'),
('Sparky / Dk Hthr Gry','Sparky / Dark Heather Grey'),
('SHIITAKE/ OFF WHITE','Shiitake/ Off White'),
('Salt Haze - Med Wash w Tint','Salt Haze - Medium Wash w Tint'),
('HONEY FLSH','Honey Flash'),
('Honey Flsh','Honey Flash'),
('WHITE/LT. HEATHER GREY','White/Light Heather Grey'),
('Gry/Blck','Grey/Black'),
('Seaport - Med Wash','Seaport - Medium Wash'),
('Skylark - Lt Wash','Skylark - Light Wash'),
('Caviar- Drk Black','Caviar- Dark Black'),
('BLANC DE BLANC','Blanc de Blanc'),
('TONAL Grey CAMO','Tonal Grey Camo'),
('Lt Lavender','Light Lavender'),
('Nvy/MdHthrGry','Navy/MdHthrGry'),
('CREAM','Cream'),
('PURPLE ROSE','Purple Rose'),
('SHIITAKE/BIRCH','Shiitake/Birch'),
('GUNMETAL','Gunmetal'),
('PROOF LAB','Proof Lab'),
('Jet Blck','Jet Black'),
('BROOKS - MED WASH','Brooks - Medium Wash'),
('INDIGO','Indigo'),
('WOODLAND CAM','Woodland Cam'),
('BROWN MIX','Brown Mix'),
('HEATHER GRAY','Heather Grey'),
('CLOVER','Clover'),
('Red Heathr','Red Heather'),
('BLUE MIX','Blue Mix'),
('TD SKY BLUE','TD Sky Blue'),
('Sbltd Grn Camo','Sbltd Green Camo'),
('Drk Peach Msty Plms','Dark Peach Misty Palms'),
('Chrcl Hthr/Blck','Charcoal Heather/Black'),
('TD SODALITE BLUE','TD Sodalite Blue'),
('SURF SUPPLIES','Surf Supplies'),
('Bad Lands - Md Wash','Bad Lands - Medium Wash'),
('OFF WHITE','Off White'),
('TD FORGETMENOT/DP TEAL','TD ForgetMeNot/Dp Teal'),
('ASSORTED','Assorted'),
('SNOW','Snow'),
('T15 VTG BLACK/PEACH ECHO','T15 Vtg Black/Peach Echo'),
('CRYSTAL PINK','Crystal Pink'),
('T16 VTG BLK/OYST MUSHROOM','T16 Vtg Black/Oyst Mushroom'),
('SAND','Sand'),
('GUAVA','Guava'),
('T18 BLACK/LAVENDER','T18 Black/Lavender'),
('BLUE','Blue'),
('T20 OCEANIC BLUES','T20 Oceanic Blues'),
('Hthr Navy','Heather Navy'),
('Blanco- Lt White Wash','Blanco- Light White Wash'),
('OCEANIC - Lt Wash','OCEANIC - Light Wash'),
('BURGUNDY MIX','Burgundy Mix'),
('Lt Kelp','Light Kelp'),
('CHOCOLATE','Chocolate'),
('Hthr Chrcoal','Heather Charcoal'),
('MILITARY OLIVE','Military Olive'),
('Chateau Gray','Chateau Grey'),
('CHARCOAL/ORANGE','Charcoal/Orange'),
('CHARCOAL MIX','Charcoal Mix'),
('olive/off white','Olive/Off White'),
('Harbor - Med Wash-32','Harbor - Medium Wash'),
('Open Sea - Lt Wash w Tint','Open Sea - Light Wash w Tint'),
('Zuma - Lt Wash','Zuma - Light Wash'),
('Snorlax - Med Wash','Snorlax - Medium Wash'),
('Cadet Blue - Med Wash','Cadet Blue - Medium Wash'),
('Gun Metal','Gunmetal'),
('Oxford - Med Wash','Oxford - Medium Wash'),
('STARLGHT BLUE','Starlght Blue'),
('BURGNDY/CHRCL','Burgundy/Charcoal'),
('Frqncy Strp','Frqncy Stripe'),
('Steel Blue - Lt Wash','Steel Blue - Light Wash'),
('FLOHANA','Flohana'),
('Storm Gry','Storm Grey'),
('navy/black','Navy/Black'),
('Sunwashed Blue - Lt Wash wTint','Sunwashed Blue - Light Wash wTint'),
('IBIZA-Med','Ibiza'),
('Navy/Light Heather Gry','Navy/Light Heather Grey'),
('SURFERS SUPPLIES','Surfers Supplies'),
('Blue Fang - Lt Wash','Blue Fang - Light Wash'),
('T4 PINK / BLUE','T4 Pink / Blue'),
('BLK/CHRC HTHR','Black/Charcoal Heather'),
('TD 13 BLUE/ORCHID','Td 13 Blue/Orchid'),
('WHITECAP','Whitecap'),
('White / Black','White/Black'),
('ET SURFBOARDS','Et Surfboards'),
('Pond - Med Wash','Pond - Medium Wash'),
('Estate Blue Omni/ Blk','Estate Blue Omni/ Black'),
('HEATHER SEA BLUE','Heather Sea Blue'),
('New Lands- Md Lt','New Lands- Medium Light'),
('PUMICE - Med Grey','PUMICE - Medium Grey'),
('Gry Strm/ChrclHthr','Grey Storm/ChrclHthr'),
('Newcastle - Dk Wash','NewCastle-Dark Wash'),
('True Wash- Drk','True Wash- Dark'),
('BLACK/BLACK MARL','Black/Black Marled'),
('Gry Statc/Blk Strm','Grey Static/Black Storm'),
('Ultramarine - Med Wash','Ultramarine - Medium Wash'),
('BLACK HTHR','Black Heather'),
('Gry Mrl/Blk','Grey Marled/Black'),
('Lt Blue/Off White','Light Blue/Off White'),
('NV/LT HTHRGRY','Nv/Light HthrGry'),
('Nvy Snow','Navy Snow'),
('LT GREY/BLUE','Light Grey/Blue'),
('JYNX - DARK WASH','Jynx - Dark Wash'),
('Iron Blue - Lt Wash','Iron Blue - Light Wash'),
('Oatml Marl','Oatml Marled'),
('IRON & WINE','Iron & Wine'),
('GREEN MIX','Green Mix'),
('Dark Gray','Dark Grey'),
('Saint Lucia-Med Wash','Saint Lucia- Medium Wash'),
('Green Hthr Camo','Green Heather Camo'),
('HTHR NAVY','Heather Navy'),
('Coastal Blue - Lt Wash w Tint','Coastal Blue - Light Wash w Tint'),
('Green Camo/Med Hthr Gry','Green Camo/Medium Heather Grey'),
('Gray Storm/Charcoal','Grey Storm/Charcoal'),
('Sbltd Nvy Camo','Sbltd Navy Camo'),
('City Wash- Md Dark','City Wash- Medium Dark'),
('Gray Snow','Grey Snow'),
('INK TEAL','Ink Teal'),
('WAVECREST - Med Wash w Tint','WAVECREST - Medium Wash w Tint'),
('MD Grey Marled','Medium Grey Marled'),
('MEDIUM BLUE','Medium Blue'),
('MEDUSA-DK BLUE','Medusa-Dark Blue'),
('Hthr Navy-M/5','Heather Navy'),
('merlot','Merlot'),
('Heather Sea Blue-M/5','Heather Sea Blue'),
('HEATHER NAVY','Heather Navy'),
('HEATHER GREY','Heather Grey'),
('Moonwashed Sand - Lt Wash','Moonwashed Sand - Light Wash'),
('Harbor - Med Wash-38','Harbor - Medium Wash'),
('Harbor - Med Wash-36','Harbor - Medium Wash'),
('Harbor - Med Wash-34','Harbor - Medium Wash'),
('Mystic- Med Wash','Mystic- Medium Wash'),
('Nantucket - Med Wash','Nantucket - Medium Wash'),
('Harbor - Med Wash-30','Harbor - Medium Wash'),
('Harbor - Med Wash-29','Harbor - Medium Wash'),
('GUN METAL','Gunmetal'),
('Navy-M/10','Navy'),
('Navy-M/5','Navy'),
('Navy/Blue','Navy Blue'),
('navy/peach','Navy/Peach'),
('New Kelly Hth Green','New Kelly Heather Green'),
('Grey Snow/Chrc Hethtr','Grey Snow/Charcoal Hethtr'),
('GREEN NAVY','Green Navy'),
('Nvy/Heritage Blue','Navy/Heritage Blue'),
('Ocean Blue Med Wash','Ocean Blue Medium Wash'),
('white/blue','White/Blue'),
('GRAPHITE HEATHER','Graphite Heather'),
('AQUA','Aqua'),
('Outerbank - Lt Wash w Tint','Outerbank - Light Wash w Tint'),
('Glacier-XXL','Glacier'),
('Glacier-XLG','Glacier'),
('Glacier-SML','Glacier'),
('Glacier-MED','Glacier'),
('Glacier-LRG','Glacier'),
('PALMS- MD LT WASH','Palms- Medium Light Wash'),
('Falcon-XXL','Falcon'),
('Falcon-XLG','Falcon'),
('Falcon-SML','Falcon'),
('Falcon-MED','Falcon'),
('Falcon-LRG','Falcon'),
('FAIR AQUA','Fair Aqua'),
('Pond - Med Wash-29','Pond - Medium Wash'),
('Pond - Med Wash-30','Pond - Medium Wash'),
('Pond - Med Wash-32','Pond - Medium Wash'),
('Pond - Med Wash-34','Pond - Medium Wash'),
('Pond - Med Wash-36','Pond - Medium Wash'),
('Pond - Med Wash-38','Pond - Medium Wash'),
('Apollo - Med Wash w Tint','Apollo - Medium Wash w Tint'),
('ANTIQUE CHERRY RED','Antique Cherry Red'),
('DUTCH WASH- MED','Dutch Wash- Medium'),
('Red/Light Heather Gry','Red/Light Heather Grey'),
('Daybreak Sky - Med Wash w Tint','Daybreak Sky - Medium Wash w Tint'),
('RONTO WASH','Ronto Wash'),
('DARK PINE','Dark Pine'),
('Royal Hthr','Royal Heather'),
('RUST - DK Blue-29','Rust-Dark Blue'),
('RUST - DK Blue-30','Rust-Dark Blue'),
('RUST - DK Blue-32','Rust-Dark Blue'),
('RUST - DK Blue-34','Rust-Dark Blue'),
('RUST - DK Blue-36','Rust-Dark Blue'),
('RUST - DK Blue-38','Rust-Dark Blue'),
('Sahara - Med Wash w Tint','Sahara - Medium Wash w Tint'),
('Salt Lake - Med Wash','Salt Lake - Medium Wash'),
('Crimson - Dk Wash w Tint','Crimson - Dark Wash w Tint'),
('Clyde - Med Wash','Clyde - Medium Wash'),
('Sbltd Brgndy Camo','Sbltd Burgundy Camo'),
('Scrthd Blk','Scratched Black'),
('Chrcl Hthr/LtGry Hthr','Charcoal Heather/LtGry Heather'),
('Sea Water - Med Dk Wash','Sea Water - Medium Dark Wash'),
('Seaside - Lt Wash','Seaside - Light Wash'),
('Charcoal-30','Charcoal'),
('SHOCKY PINK','Shocky Pink'),
('Sierra- Lt Md Wash','Sierra- Light Medium Wash'),
('Simple Sage CBO','Simple Sage Combo'),
('SKYFALL - Lt Wash','SKYFALL - Light Wash'),
('Cerulean - Med Dark Wash','Cerulean - Medium Dark Wash'),
('SKYLAR - LT BLUE','Skylar-LtBlue'),
('CAVIAR WASH','Caviar Wash'),
('CAPRI BLUE','Capri Blue'),
('WOODLAND CAMO','Woodland Camo'),
('IRISH GREEN','Irish Green'),
('Splash- Drk Wash','Splash- Dark Wash'),
('Burgundy Hthr','Burgundy Heather'),
('BURGUNDY','Burgundy'),
('Burgndy/Chrcl-M/10','Burgundy/Charcoal'),
('Brown/Chrcl Hthr','Brown/Charcoal Heather'),
('BROWN CAMO','Brown Camo'),
('Brngdy/MHthrGry','Burgundy/MHthrGry'),
('Stone Block Cmbo','Stone Block Combo'),
('SULPHUR WASH- DK GREY','Sulphur Wash- Dark Grey'),
('BLUE NAVY','Blue Navy'),
('Blue Moon- Md Drk Wash','Blue Moon- Medium Dark Wash'),
('Amazon - Med Wash w Tint','Amazon - Medium Wash w Tint'),
('BLUE ISLAND - MD LT WASH','Blue Island - Medium Light Wash'),
('BLUE FOG','Blue Fog'),
('BLUE CAMO','Blue Camo'),
('Blk/MdHthrGry','Black/MdHthrGry'),
('T7 SPIRAL LAV/AQUA','T7 Spiral lav/aqua'),
('Blk/Heather','Black Heather'),
('T9 NAVY','T9 Navy'),
('Blk Spc Dye / Blk','Black Space Dye / Black'),
('Blck/HthrGry','Black/HthrGry'),
('Blck/Brgndy','Black/Burgundy'),
('Blck Paradise-38','Black Paradise'),
('Blck Paradise-36','Black Paradise'),
('TD OLIVE','TD Olive'),
('TD PURPLE TEAL','Td Purple Teal'),
('Blck Paradise-34','Black Paradise'),
('Blck Paradise-32','Black Paradise'),
('Blck Paradise-30','Black Paradise'),
('Blck Paradise-29','Black Paradise'),
('Blck Marl','Black Marled'),
('Blck Knght','Black Knight'),
('Blck Fade','Black Fade'),
('Titanium Gry GD','Titanium Grey GD'),
('BLANCO','Blanco'),
('TRUE WASH- DRK','True Wash- Dark'),
('BLACK/NEON GREEN','Black/Neon Green'),
('Black-M/10','Black'),
('Typhoon- Drk Wash','Typhoon- Dark Wash'),
('VALENTINE','Valentine'),
('Veil - Dark Wash-29','Veil - Dark Wash'),
('Veil - Dark Wash-30','Veil - Dark Wash'),
('Veil - Dark Wash-32','Veil - Dark Wash'),
('Veil - Dark Wash-34','Veil - Dark Wash'),
('Veil - Dark Wash-36','Veil - Dark Wash'),
('Veil - Dark Wash-38','Veil - Dark Wash'),
('BEACH SIDE- LT WASH','Beach Side- Light wash'),
('Beach Side- lt wash','Beach Side- Light wash'),
('Barcelona - Lt Wash','Barcelona - Light Wash'),
('Warm Gray','Warm Grey'),
('ATLANTIC BLUE','Atlantic Blue'),
('LT BEIGE CAMO','Light Beige Camo'),
('Lt Gray/Black','Light Grey/Black'),
('Lt Gray/Navy','Light Grey/Navy'),
('Lt Green','Light Green'),
('Kelly Hthr','Kelly Heather'),
('Lt Grey Tonal Camo','Light Grey Tonal Camo'),
('Lt Grey/Black','Light Grey/Black'),
('Lt Hthr/White','Light Heather/White'),
('LT LAVENDER','Light Lavender'),
('LT PINK','Light Pink'),
('Lt. Hthr Gry/Black','Light Heather Grey/Black'),
('Lt. Indigo','Light Indigo');

CREATE TEMP TABLE _pairs ON COMMIT DROP AS
WITH losers AS (
  SELECT i.id AS loser_id, i.style_id, i.size, i.inseam, m.canon
  FROM ip_item_master i JOIN _cmap m ON i.color = m.raw
  WHERE i.style_code NOT ILIKE '%PL' AND i.size IS NOT NULL
    AND EXISTS (SELECT 1 FROM ip_item_master x WHERE x.style_id = i.style_id
      AND x.size = i.size AND COALESCE(x.inseam,'') = COALESCE(i.inseam,'')
      AND x.color = m.canon AND x.id <> i.id)
)
SELECT l.loser_id,
  (SELECT x.id FROM ip_item_master x WHERE x.style_id = l.style_id AND x.size = l.size
     AND COALESCE(x.inseam,'') = COALESCE(l.inseam,'') AND x.color = l.canon
     ORDER BY x.id LIMIT 1) AS survivor_id
FROM losers l;

-- Snapshots (permanent) BEFORE any deletion.
CREATE TABLE IF NOT EXISTS _sku_merge_losers_bk_20260613 AS
  SELECT * FROM ip_item_master WHERE id IN (SELECT loser_id FROM _pairs);
CREATE TABLE IF NOT EXISTS _sku_merge_layers_bk_20260613 AS
  SELECT * FROM inventory_layers WHERE item_id IN (SELECT loser_id FROM _pairs);

DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT loser_id, survivor_id FROM _pairs
           WHERE survivor_id IS NOT NULL AND survivor_id <> loser_id
  LOOP
    PERFORM merge_item_master_dups(r.survivor_id, ARRAY[r.loser_id]);
  END LOOP;
END $$;
