-- Proactive insights surfaced by the Ask AI cron (Tier 3K).
--
-- A nightly job (api/cron/ai-proactive-insights.js) scans live data,
-- runs hard-coded RULES to detect "stuff worth flagging," and writes
-- one row per detected insight. The Ask AI panel shows a 💡 indicator
-- with a count, and clicking it lists the open insights. The operator
-- can dismiss any insight (sets dismissed_at).
--
-- Quality bar: false positives kill trust. Rules use floors + ratios
-- (not raw thresholds) so we don't flag every tiny perturbation, and
-- we dedupe so the same signal doesn't re-fire every day.

CREATE TABLE IF NOT EXISTS ip_ai_proactive_insights (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rule            text NOT NULL,           -- 'customer_churn_signal', 'style_runaway_success', etc.
  severity        text NOT NULL DEFAULT 'info',  -- 'info' | 'warn' | 'urgent'
  subject_type    text NOT NULL,           -- 'customer' | 'style' | 'vendor' | 'compliance' | 'global'
  subject_id      text,                    -- ip_customer_master.id, style_code, etc. (null for global)
  subject_label   text,                    -- human-friendly subject name for display
  headline        text NOT NULL,           -- one-line summary the operator sees first
  detail          text,                    -- longer explanation; what + why + what to look at
  metrics         jsonb NOT NULL DEFAULT '{}'::jsonb,  -- ranked numbers, e.g. {"t30_revenue": 12500, "p30_revenue": 22000, "drop_pct": 43.2}
  detected_at     timestamptz NOT NULL DEFAULT now(),
  -- Dedupe key: (rule, subject_id, signal_date) so re-running the cron
  -- the same day doesn't multiply rows, and a signal that persists
  -- week-over-week only flags once per week.
  dedupe_key      text NOT NULL UNIQUE,
  dismissed_at    timestamptz,             -- when an operator dismissed it
  dismissed_by    text                     -- plm_user.id of dismisser
);

CREATE INDEX IF NOT EXISTS idx_ip_ai_proactive_insights_open
  ON ip_ai_proactive_insights (detected_at DESC)
  WHERE dismissed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_ip_ai_proactive_insights_rule
  ON ip_ai_proactive_insights (rule, detected_at DESC);

COMMENT ON TABLE ip_ai_proactive_insights IS
  'Rule-based proactive insights surfaced in the Ask AI panel. Generated by api/cron/ai-proactive-insights.js. Tier 3K.';
