-- ════════════════════════════════════════════════════════════════════════════
-- Normalize color_master — collapse case / spacing / size-leak / abbreviation
-- variants of the seeded colors into 857 canonical names.
--
-- The initial seed (20260867000000) inserted one row per distinct existing
-- ip_item_master.color, case-folded only — leaving spacing variants
-- ("Harbor - Med Wash" vs "Harbor- Med Wash"), size leaked into the color
-- ("Charcoal-30", "Navy-M/5"), and abbreviations (Lt/Dk/Hthr/Chrcl/Gry…) as
-- separate rows. This rebuild replaces them with the cleaned canonical set.
--
-- SAFE / additive: NO style references color_master yet (attributes.color_ids is
-- empty across every style — verified on prod), so a delete+reinsert cannot
-- orphan anything. A full backup is taken first for reversibility. This touches
-- ONLY the color picklist; ip_item_master SKU colors are NOT modified here (the
-- live-SKU rewrite is blocked on a separate size-field corruption repair).
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS _color_master_backup_20260613 AS
  SELECT * FROM color_master;

DO $$
DECLARE v_entity uuid;
BEGIN
  SELECT id INTO v_entity FROM entities WHERE code = 'ROF';
  IF v_entity IS NULL THEN RAISE EXCEPTION 'ROF entity not found'; END IF;

  DELETE FROM color_master WHERE entity_id = v_entity;

  INSERT INTO color_master (entity_id, name)
  SELECT v_entity, c.name
  FROM (VALUES
('# 3 Atlantic'),
('03-Boardwalk'),
('03SF-Charcoal'),
('ALEGRIA-Medium Dark'),
('ASH'),
('Abyss'),
('Admiral Medium Wash'),
('Agate'),
('Agave Green'),
('Alchemy'),
('Algae - Dark Wash'),
('Aloe'),
('Alpine Green'),
('Amazon - Medium Wash w Tint'),
('Americana'),
('Americana- MdBlue'),
('Aminism'),
('Annie Wash'),
('Antique Cherry Red'),
('Apollo - Medium Wash w Tint'),
('Apricot'),
('Aqua'),
('Aqua Medium Light Wash'),
('Army Green'),
('Army Green Camo'),
('Arnav - Dark Wash'),
('Artemis'),
('Aruba- Medium Wash'),
('Ash Grey'),
('Asphalt Wash'),
('Assorted'),
('Aster'),
('Atlantic Blue'),
('Autumn'),
('Autumn Camo'),
('Autumn Fade Grizzly Camo'),
('Autumn Grizzly Camo'),
('Azul - Medium Blue'),
('Azure - Medium M Wash'),
('BKB'),
('BKM'),
('BPK'),
('BUR'),
('Baby Pink'),
('Bad Lands - Medium Wash'),
('Barcelona - Light Wash'),
('Bark - Grey w Tint'),
('Bayou - Medium Wash'),
('Beach Side- Light wash'),
('Beach Wash - Light Wash'),
('Beige'),
('Below Zero- Light Wash'),
('Bermuda - Light Wash'),
('Birch'),
('Blac'),
('Black'),
('Black / Yellow'),
('Black Blessed Madonna'),
('Black Cali Bear'),
('Black Camo'),
('Black Check'),
('Black City Scape'),
('Black Fade'),
('Black Geo Camo'),
('Black Grave Garden'),
('Black Heather'),
('Black Knight'),
('Black Marled'),
('Black Oil'),
('Black Paradise'),
('Black Sands'),
('Black Shadow GD'),
('Black Slub'),
('Black Space Dye / Black'),
('Black Stone'),
('Black Storm'),
('Black Wash'),
('Black Water Camo'),
('Black Widow'),
('Black/ Off White'),
('Black/Birch'),
('Black/Black'),
('Black/Black Marled'),
('Black/Burgundy'),
('Black/Charcoal'),
('Black/Charcoal Heather'),
('Black/Egret'),
('Black/Grey'),
('Black/HthrGry'),
('Black/Light Grey'),
('Black/Light Heather Grey'),
('Black/MdHthrGry'),
('Black/Mint'),
('Black/Neon Green'),
('Black/Olive'),
('Black/Red'),
('Black/Salsa'),
('Black/Shaved Chocolate'),
('Black/Tan'),
('Black/Teal'),
('Black/White'),
('Blackberry'),
('Blacksands - Black Wash wTint'),
('Blanc de Blanc'),
('Blanc de Blanc Lake Camo'),
('Blanco'),
('Blanco Lilac'),
('Blanco V2'),
('Blanco- Light White Wash'),
('BlddStone'),
('BlkSpaceDye'),
('Blood'),
('Blue'),
('Blue Bleach'),
('Blue Bleached'),
('Blue Camo'),
('Blue Fang - Light Wash'),
('Blue Fog'),
('Blue Fog Topography'),
('Blue Hawk - Dark Wash'),
('Blue Island - Medium Light Wash'),
('Blue Jean'),
('Blue Mist'),
('Blue Mix'),
('Blue Moon- Medium Dark Wash'),
('Blue Navy'),
('Blue Radiance'),
('Blue Radience'),
('Blue Shadow'),
('Blue Slate'),
('Blue Stone'),
('Blue Stone - Medium Wash'),
('Blue Tide - Dark Wash w Tint'),
('Blue Tint'),
('Blue/Coral'),
('Blueberry'),
('Blush'),
('Boardwalk'),
('Bonsai - Dark Wash w Tint'),
('Bonzai - Dark Wash'),
('Boreal Blue - Medium Wash w Tint'),
('Bottle Green'),
('Brick'),
('Brig Surf'),
('Brooks - Medium Wash'),
('Brown'),
('Brown Camo'),
('Brown Clear Camo'),
('Brown Mix'),
('Brown/Charcoal Heather'),
('Brushed Alloy'),
('Buenos Aires - Light Wash'),
('Burg/Off White'),
('Burgundy'),
('Burgundy Bomba'),
('Burgundy Heather'),
('Burgundy Mix'),
('Burgundy/Charcoal'),
('Burgundy/Gold'),
('Burgundy/MHthrGry'),
('Burgundy/Off White'),
('Burgundy/White'),
('Byron Bay - Medium Wash'),
('CALM FRONT - Light Wash'),
('CARBON- Dark Wash'),
('CAVE - Light Wash'),
('CHR'),
('Cadet Blue - Medium Wash'),
('Camel'),
('Cannes - Medium Wash'),
('Canyon Sunset'),
('Cappuccino'),
('Capri Blue'),
('Carbon- Black'),
('Caribbean - Medium Wash'),
('Caspain - Light Wash'),
('Caviar Wash'),
('Caviar- Dark Black'),
('Celeste Wash'),
('Cerulean - Medium Dark Wash'),
('Chain'),
('Char Green'),
('Charcoal'),
('Charcoal Black'),
('Charcoal Bomba'),
('Charcoal Clear Camo'),
('Charcoal Heather'),
('Charcoal Heather/Black'),
('Charcoal Heather/LtGry Heather'),
('Charcoal Marled'),
('Charcoal Mix'),
('Charcoal/Grey'),
('Charcoal/Orange'),
('Chateau Grey'),
('Chestnut'),
('Chinese Apple'),
('Chinois Green'),
('Chocolate'),
('Chocolate Malt'),
('Chocolate Plum'),
('Chocolate Torte/Shaved Chocolate'),
('Chocolate/Tan'),
('Cinder - Light Grey'),
('Citrus Yellow'),
('City Wash- Medium Dark'),
('Classic Navy'),
('Climbing Ivy'),
('Cloud Blue'),
('Cloud Cream'),
('Cloud Dancer'),
('Clover'),
('Clyde - Medium Wash'),
('Coal - Dark Grey'),
('Coastal Blue - Light Wash w Tint'),
('Cobalt - Dark Blue'),
('Cole - Medium Wash'),
('Copen Blue Wash'),
('Copper'),
('Coral'),
('Coral Cobalt'),
('Coronet Blue'),
('Coronet Blue Lake Camo'),
('Cream'),
('Cream Grizzly Camo'),
('Cream Multi'),
('Cream Tonal Grizzly Camo'),
('Creek - Medium Light Wash'),
('Crimson - Dark Wash w Tint'),
('Crimson Stripe'),
('Crow - Washed Black'),
('Crumble-Medium BLU'),
('Crystal Pink'),
('CubanSnd- Medium Wash'),
('Currents - Light Wash'),
('DAWN'),
('DUSK'),
('Daiquiri Green'),
('Dark Blue'),
('Dark Brown'),
('Dark Denim Wash'),
('Dark Green Omni/Black'),
('Dark Grey'),
('Dark Ivy'),
('Dark Khaki'),
('Dark Olive'),
('Dark Olive Marled'),
('Dark Peach'),
('Dark Peach Misty Palms'),
('Dark Pine'),
('Dark Slate'),
('Dark Teal'),
('Dark Tropical Grey'),
('Dark Wash'),
('Daybreak Sky - Medium Wash w Tint'),
('Dazzling Blue/Cloud Dancer'),
('Deathstar'),
('Deep Black'),
('Deep Black GD'),
('Deep Blue'),
('Deep Teal'),
('Delphinium Blue'),
('Desert Sage'),
('DkSprng/MdGry'),
('Double Duff - Light Wash'),
('Dress Blues'),
('Driftwood - Medium Wash'),
('Drought Wash - Medium Light'),
('Dubai - Dark Wash'),
('Dull Gold'),
('Dull Gold Gd'),
('Dusk--Medium Blue'),
('Dusty Plum'),
('Dutch Wash- Medium'),
('Eaton - Light Wash'),
('Eaton - Medium Wash'),
('Eclipse'),
('Eclipse - Medium Wash'),
('Elderberry'),
('Elkmont Trading'),
('Emerald/Grey'),
('Ensign'),
('Espresso'),
('Estate'),
('Estate Blue'),
('Estate Blue Omni/ Black'),
('Et Surfboard'),
('Et Surfboards'),
('Everglades - Medium Wash'),
('FOG - Grey'),
('FUS'),
('Faded Salmon'),
('Fair Aqua'),
('Falcon'),
('Falcon Lake Camo'),
('Fiesta'),
('Fin Gd'),
('Fleetwood - Medium Wash'),
('Flohana'),
('Flow Wash - Light Wash'),
('Forest Night'),
('Forget-Me-Not'),
('Forget-Me-Not Whales'),
('Fossil - Medium Grey'),
('Fountain Blue'),
('Fragile Ocean'),
('Frost'),
('Frqncy Stripe'),
('Fuchsia'),
('GNC'),
('GOR'),
('Gateway - Medium Wash'),
('Glacier'),
('Golden Oak Geo Camo'),
('GoldenOak'),
('Gordon - Light Wash'),
('Grape Wine'),
('Grape Wine Manta'),
('Grapewine/Elderberry'),
('Graphite'),
('Graphite Heather'),
('Green'),
('Green Camo'),
('Green Camo/Medium Heather Grey'),
('Green Combo'),
('Green Heather Camo'),
('Green Mix'),
('Green Navy'),
('Green Pumpkin'),
('Green Pumpkin Lake Camo'),
('Grey'),
('Grey Ashen Camo'),
('Grey Camo'),
('Grey Marled/Black'),
('Grey Snow'),
('Grey Snow/Charcoal Hethtr'),
('Grey Static/Black Storm'),
('Grey Storm'),
('Grey Storm/Charcoal'),
('Grey Storm/ChrclHthr'),
('Grey Wolf - Light Grey'),
('Grey/Black'),
('Guava'),
('Gunmetal'),
('Gunmetal/Royal Heather'),
('H.G'),
('Hailstorm - Dark Wash'),
('Hammock'),
('Harbor - Medium Wash'),
('Harbour Blue'),
('Heather Charcoal'),
('Heather Charcoal/Yellow'),
('Heather Grey'),
('Heather Grey/Slate'),
('Heather Navy'),
('Heather Sea Blue'),
('Hematite - Washed Black'),
('Heritage'),
('Heritage Surf'),
('High Waters - Dark Wash'),
('Hobie Surf'),
('Honey'),
('Honey / Mustard'),
('Honey Flash'),
('Horizon'),
('Hudson Wash'),
('Hunter'),
('ICE FIELD - Light Wash w Tint'),
('IVY- Dark Wash'),
('Ibiza'),
('Ibiza - Medium Wash'),
('Ice Blue'),
('Ice Melt'),
('Ice Water'),
('Iceberg Green'),
('IcebrgGreen/MnlssNight'),
('Imperial Blue'),
('Indigo'),
('Indigo Marled'),
('Indigo Rip'),
('Ink Teal'),
('Irish Green'),
('Iron & Wine'),
('Iron Blue - Light Wash'),
('Iron Gate'),
('Island Breeze'),
('Island Breeze Light wash'),
('Jacks Surfboards'),
('Jade'),
('Jet Black'),
('Jungle Camo'),
('Juniper'),
('Jynx - Dark Wash'),
('KHK'),
('Kauai'),
('Kelly Green'),
('Kelly Heather'),
('Kelp'),
('Khaki'),
('Khaki Cali Bear'),
('Kings Blue - Dark Wash'),
('Kraken'),
('LBL'),
('Lasso Wash - Dark Wash'),
('Lava'),
('Lavender'),
('LemonDrp'),
('Light Beige Camo'),
('Light Blue'),
('Light Blue/Off White'),
('Light Brown'),
('Light Denim Wash'),
('Light Green'),
('Light Grey'),
('Light Grey Cali Bear'),
('Light Grey Heather'),
('Light Grey Tonal Camo'),
('Light Grey/Black'),
('Light Grey/Blue'),
('Light Grey/Charcoal'),
('Light Grey/Navy'),
('Light HG/Charcoal'),
('Light Heather Grey'),
('Light Heather Grey/Black'),
('Light Heather/White'),
('Light Indigo'),
('Light Kelp'),
('Light Khaki'),
('Light Lavender'),
('Light Olive'),
('Light Pink'),
('Light Wash'),
('LtGrySpckl'),
('Lulu Wash'),
('Luna-Light Wash'),
('Lyons Blue'),
('MELTFIELD - Medium Wash w Tint'),
('MNT'),
('Maelstrom'),
('Magic Mauve'),
('Mahogany - Black w Tint'),
('Malibu'),
('Manila - Light Wash w Tint'),
('Marine Camo'),
('Marine Wash'),
('Marine- Medium Wash'),
('Maroon'),
('Maui - Light Wash'),
('MdmGryHthr/ChrlHthr'),
('Media Park- Dark Wash'),
('Medium Blue'),
('Medium Denim Wash'),
('Medium Grey'),
('Medium Grey Marled'),
('Medium Heather Grey'),
('Medium Wash'),
('Medusa-Dark Blue'),
('Mercury'),
('Merlot'),
('Miami - Light Blue'),
('Midnight'),
('Military Green'),
('Military Olive'),
('Millie Wash'),
('Mineral Red'),
('Mineral- Light Blue'),
('Mint'),
('Mist Blue- Light Wash'),
('Mist Drift - Light Wash'),
('Misty Bay - Light Wash'),
('Mocha Heather'),
('Moisture - Medium Wash'),
('Monaco Blue'),
('Monument'),
('Moon Mist - Grey Wash'),
('Moonless Nights'),
('Moonless Nights Lake Camo'),
('Moonless Nights Manta'),
('Moonless Nights Topography'),
('Moonless Nights/Lavndr'),
('Moonrock'),
('Moonwashed Sand - Light Wash'),
('Morning Dew'),
('Mossy Olive'),
('Mushroom'),
('Mushroom- Light Grey'),
('Mykonos'),
('Mysters Seas'),
('Mystic- Medium Wash'),
('Nantucket - Medium Wash'),
('Naval Academy'),
('Naval Academy/BlncDeBlnc'),
('Navy'),
('Navy Blue'),
('Navy Camo'),
('Navy Camo CA'),
('Navy Chevron'),
('Navy Heather'),
('Navy Nautical'),
('Navy Oil'),
('Navy Sky'),
('Navy Snow'),
('Navy/Black'),
('Navy/Heritage Blue'),
('Navy/Light Heather Grey'),
('Navy/MdHthrGry'),
('Navy/Navy'),
('Navy/Off White'),
('Navy/Peach'),
('Navy/Peony'),
('Navy/White'),
('Navy/White/Stormy'),
('Neon Mint heather'),
('Neon Yellow Heather'),
('Neptune - Medium Wash'),
('New Kelly Heather Green'),
('New Lands - Medium Light Wash'),
('New Lands- Medium Light'),
('New Wheat- Medium Dark'),
('NewCastle-Dark Wash'),
('Nickel'),
('Nieve'),
('Night Camo'),
('Nightfall'),
('Nocturnal'),
('Norse'),
('Nugget'),
('Nv/Light HthrGry'),
('NvySpaceDye'),
('OCEANIC - Light Wash'),
('ORG'),
('OWT'),
('Oasis- Medium Wash'),
('Oatmeal'),
('Oatmilk'),
('Oatml Marled'),
('Obsidian'),
('Ocean Blue Medium Wash'),
('Ocean Camo/Charcoal'),
('Ocean Hut'),
('Ocean Teal'),
('Ocean Tide'),
('Oceanside - Medium Wash'),
('Off White'),
('Off White/Black'),
('Off White/Burgundy'),
('Off White/Royal'),
('Og Camo'),
('Olive'),
('Olive Gradient Camo'),
('Olive Heather'),
('Olive Vine'),
('Olive/Off White'),
('OliveSpaceDye'),
('Olv/ChrclHthr'),
('OlvCamo'),
('Omen'),
('Onyx Wash'),
('Opal Grey'),
('Open Sea - Light Wash w Tint'),
('Orange'),
('Orchid'),
('Orion'),
('Outerbank - Light Wash w Tint'),
('Overcast - Lt.Blue'),
('Oxblood'),
('Oxblood Camo'),
('Oxford - Medium Wash'),
('Oxford Blue'),
('Oyster'),
('Oyster Mushroom'),
('PEPPER - Acid Grey'),
('PFD'),
('PNK'),
('PUMICE - Medium Grey'),
('PUR'),
('PYRITE-Medium Dark Wash'),
('Palms- Medium Light Wash'),
('Panther - Black'),
('Paradise Green'),
('Pastel Lght Blue'),
('Pastel Lght Pink'),
('Pastel Turqouise'),
('Peach'),
('Peach Echo'),
('Peach Parfait'),
('Peaks'),
('Pepper'),
('Periwinkle- Light Wash'),
('Pink'),
('Pink Ombre Wash'),
('Pink Wash'),
('Pink/Blue'),
('Placid - Light Wash'),
('Pond - Medium Wash'),
('Proof Lab'),
('Pumice Stone'),
('Purple'),
('Purple Rose'),
('RYB'),
('Raindrops'),
('Raspberry Mandarin'),
('Raspberry Wine'),
('Real Teal'),
('Red'),
('Red Heather'),
('Red/Beige'),
('Red/Black'),
('Red/Light Heather Grey'),
('Red/Off White'),
('Redwoods - Dark Wash'),
('Reef'),
('Revised Surf Hut'),
('Rinse - DkBlue'),
('River Blue'),
('River Lee - Dark Wash'),
('River and Roads'),
('Riviera'),
('Roasted Cashew'),
('Robin'),
('Robin - Medium Blue'),
('Rocky - Medium Grey'),
('Ronto Wash'),
('Rose Red'),
('Royal'),
('Royal Blue'),
('Royal Heather'),
('Royal/Off White'),
('Ruby Wine'),
('Rust-Dark Blue'),
('SKYFALL - Light Wash'),
('Sage'),
('Sahara - Medium Wash w Tint'),
('Sahara Camo'),
('Sailing Wash'),
('Sailor Wash'),
('Saint Lucia- Medium Wash'),
('Salsa/Black'),
('Salt Haze - Medium Wash w Tint'),
('Salt Lake - Medium Wash'),
('Saltwater - Medium Wash'),
('Saltwater Sky - Light Wash w Tint'),
('Salty''s Surf Shop'),
('Sand'),
('Sand Marled'),
('Sand Rock'),
('Sandcastle - Light Wash'),
('Sandlot'),
('Sandlot - Medium Wash'),
('Sandstone'),
('SangrOmni/Black'),
('Sangria'),
('Sangria Omni'),
('Santorini - Light Wash'),
('Sapphire'),
('Sbltd Black Camo'),
('Sbltd Burgundy Camo'),
('Sbltd Green Camo'),
('Sbltd Navy Camo'),
('Scratched Black'),
('Sea Blue'),
('Sea Breeze- Light Wash'),
('Sea Floor - Medium Wash'),
('Sea Mist - Light Wash'),
('Sea Otter'),
('Sea Spray - Light Wash w Tint'),
('Sea Water - Medium Dark Wash'),
('Seafoam'),
('Seal - Light Grey'),
('Seaport - Medium Wash'),
('Seashell'),
('Seaside - Light Wash'),
('Seaweed - Dark Wash'),
('Sediment - Light Wash'),
('Serene'),
('Shadow Green'),
('Shadow Wash Black'),
('Shadow Wash- Dark'),
('Shamrock Green/Off White'),
('Shiitake'),
('Shiitake Hunters Camo'),
('Shiitake/ Off White'),
('Shiitake/Birch'),
('Shiitake/Black'),
('Shocky Pink'),
('Shorebreak'),
('Sierra- Light Medium Wash'),
('Silver'),
('Silver/Black'),
('Simple Sage Combo'),
('Simple Sage GD'),
('Sky'),
('Sky Blue'),
('Sky Light Wash'),
('Skydiver Blue/White'),
('Skylar-LtBlue'),
('Skylark - Light Wash'),
('Skyline- Medium Light'),
('Skyway'),
('Skyway Blue'),
('Slate'),
('Slate Blue'),
('Slate/Off White'),
('Smoke Blue - Light Blue'),
('Smokey- Dark Grey'),
('Snd Camo4'),
('Snorlax - Medium Wash'),
('Snow'),
('Sodalite Blue'),
('Soft Serve'),
('Sonar'),
('South Coast'),
('Spa Blue'),
('Spade'),
('Sparky / Dark Heather Grey'),
('Splash- Dark Wash'),
('Spring Water - Light Wash'),
('Starlght Blue'),
('Starlight Blue'),
('Static - Black Acid Wash'),
('Steam Wash'),
('Steam Wash - Light Wash'),
('Steel'),
('Steel Blue - Light Wash'),
('Steel Grey'),
('Stellar'),
('Sterling'),
('Stn Splattr'),
('Stone'),
('Stone Block Combo'),
('Stone Block Gd'),
('Storm'),
('Storm Blue/Apricot'),
('Storm Camo'),
('Storm Grey'),
('Stormy'),
('Stormy Weather'),
('Sulphur Wash- Dark Grey'),
('Sun Kissed Coral'),
('Sunny Daze'),
('Sunset'),
('Sunwashed Blue - Light Wash wTint'),
('Surf - Light Wash'),
('Surf City'),
('Surf Hut'),
('Surf Spray'),
('Surf Supplies'),
('Surf, Wind & Fire'),
('Surfer Supply'),
('Surfers Supplies'),
('T1 Black'),
('T15 Vtg Black/Peach Echo'),
('T16 Vtg Black/Oyst Mushroom'),
('T17 Black/Discharge'),
('T18 Black/Lavender'),
('T19 Oceanic Greens'),
('T20 Oceanic Blues'),
('T4 Pink / Blue'),
('T6 Lavender/blue'),
('T7 Spiral lav/aqua'),
('T8 Rainbow Sherbet'),
('T9 Navy'),
('TD Black'),
('TD Elderberry/Grape Wine'),
('TD ForgetMeNot/Dp Teal'),
('TD Ginger'),
('TD Navy'),
('TD Olive'),
('TD Sky Blue'),
('TD Sodalite Blue'),
('TD26 Black/White'),
('Tan'),
('Taupe Grey'),
('Td 13 Blue/Orchid'),
('Td Purple Teal'),
('Tea'),
('Tea Hunters Camo'),
('Teal'),
('Thalia'),
('Thunderbolt - Dark Wash'),
('Thyme'),
('Tibetan Red'),
('TibetanRed/MoonlssNights'),
('Titanium Grey GD'),
('Tonal Black Camo'),
('Tonal Green Camo'),
('Tonal Grey Camo'),
('Tonal Khaki Camo'),
('Tree Camo'),
('Trench Water - Dark Wash w Tint'),
('Trey Lavender'),
('Tropical Peach'),
('True Blue'),
('True Light Blue'),
('True Red'),
('True Wash- Dark'),
('TrueGrnCamo'),
('Trunks'),
('Tsunami'),
('Tur'),
('Turqouise'),
('Twilight'),
('Twill GD'),
('Typhoon'),
('Typhoon- Dark Wash'),
('US Flag'),
('Ultimate Grey'),
('Ultramarine - Medium Wash'),
('Undertow'),
('VNK'),
('Valentine'),
('Vallarta Blue'),
('Vallarta Blue Fly'),
('Vanish-Dark Blue'),
('Veil - Dark Wash'),
('Vernaulk - Light Wash'),
('Very Peri'),
('Vintage Lake'),
('Vista'),
('Volt - Medium Wash w Tint'),
('WASHED Black'),
('WASHED Khaki'),
('WASHED Olive'),
('WAVECREST - Medium Wash w Tint'),
('WHT'),
('Walnut'),
('Warm Grey'),
('Washed Brown'),
('Washed Charcoal'),
('Washed Stone'),
('Wave Riding Vehicles'),
('Wavey'),
('Wheat'),
('White'),
('White Camo'),
('White Navy'),
('White/Black'),
('White/Blue'),
('White/Green'),
('White/Light Heather Grey'),
('Whitecap'),
('Wht/MedHthr'),
('WhtCapGrey/Tibetan Red'),
('Willow - Dark Blue'),
('Winston Wash'),
('Wither Fade'),
('Wither Fade Ashen Camo'),
('Wither Fade Camo'),
('Woodland Cam'),
('Woodland Camo'),
('YLW'),
('Yellow'),
('Yellow Cream'),
('Yellow/Black'),
('Ziggy'),
('Zinc'),
('Zuma - Light Wash'),
('malt')
  ) AS c(name)
  ON CONFLICT (entity_id, lower(name)) DO NOTHING;
END $$;
