-- ============================================================================
-- Color aliases + nightly "last received date" sync.
--
-- color_aliases bridges a RAW Xoro colour spelling -> the canonical color_master
-- name (Tangerine SKU colours were normalized to canonical, but Xoro feeds still
-- arrive raw, e.g. "BLCK PARADISE" -> "Black Paradise"). Seeded from the
-- normalization map; reusable by any Xoro->Tangerine colour match.
--
-- sync_received_dates(p_rows): given [{s:style, c:rawColour, d:isoDate}] from the
-- nightly Playwright inventory snapshot ("Last Receipt Date" column; the REST
-- export has none), bridge the colour, take the newest date per (style,colour),
-- and stamp it onto that SKU's inventory layers (Xoro-seeded layers only, so a
-- real Tangerine PO-receipt layer is left alone). Idempotent (updates only when
-- the date changed). Called from api/ats/upload (which already ingests the
-- snapshot nightly), so last-received stays current with no new plumbing.
-- ============================================================================

CREATE TABLE IF NOT EXISTS color_aliases (
  entity_id      uuid NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  raw_lower      text NOT NULL,
  canonical_name text NOT NULL,
  PRIMARY KEY (entity_id, raw_lower)
);
COMMENT ON TABLE color_aliases IS 'Raw Xoro colour spelling (lowercased) -> canonical color_master name, for matching Xoro feeds to normalized Tangerine SKU colours.';

INSERT INTO color_aliases (entity_id, raw_lower, canonical_name)
SELECT (SELECT id FROM entities WHERE code='ROF'), v.raw_lower, v.canon
FROM (VALUES
('vanish-dk blue','Vanish-Dark Blue'),
('below zero- lt wash','Below Zero- Light Wash'),
('blck paradise','Black Paradise'),
('lt brown','Light Brown'),
('blk camo','Black Camo'),
('lt grey','Light Grey'),
('smoke blue - lt blue','Smoke Blue - Light Blue'),
('bermuda - lt wash','Bermuda - Light Wash'),
('harbor - med wash','Harbor - Medium Wash'),
('dutch wash- med','Dutch Wash- Medium'),
('crumble-md blu','Crumble-Medium BLU'),
('charcoal hthr','Charcoal Heather'),
('carbon- blck','Carbon- Black'),
('mineral- lt blue','Mineral- Light Blue'),
('caspain - lt wash','Caspain - Light Wash'),
('sea floor - med wash','Sea Floor - Medium Wash'),
('buenos aires - lt wash','Buenos Aires - Light Wash'),
('pyrite-med dark wash','PYRITE-Medium Dark Wash'),
('vernaulk - lt wash','Vernaulk - Light Wash'),
('skyline- md lt','Skyline- Medium Light'),
('medusa-dk blue','Medusa-Dark Blue'),
('gordon - lt wash','Gordon - Light Wash'),
('t16 vtg blk/oyst mushroom','T16 Vtg Black/Oyst Mushroom'),
('new wheat- md dark','New Wheat- Medium Dark'),
('medm hthr gry','Medium Heather Grey'),
('cubansnd- md wash','CubanSnd- Medium Wash'),
('rust-dk blue','Rust-Dark Blue'),
('heather gray','Heather Grey'),
('fleetwood - med wash','Fleetwood - Medium Wash'),
('blk/chrc hthr','Black/Charcoal Heather'),
('sandlot - med wash','Sandlot - Medium Wash'),
('lt blue','Light Blue'),
('drought wash - med light','Drought Wash - Medium Light'),
('mushroom- lt grey','Mushroom- Light Grey'),
('creek - md lt wash','Creek - Medium Light Wash'),
('beach wash - lt wash','Beach Wash - Light Wash'),
('eaton - lt wash','Eaton - Light Wash'),
('media park- drk wash','Media Park- Dark Wash'),
('black/gray','Black/Grey'),
('aruba- md wash','Aruba- Medium Wash'),
('sediment - lt wash','Sediment - Light Wash'),
('black hthr','Black Heather'),
('blue stone - med wash','Blue Stone - Medium Wash'),
('crow - washed blk','Crow - Washed Black'),
('gateway - med wash','Gateway - Medium Wash'),
('robin - md blue','Robin - Medium Blue'),
('navy hthr','Navy Heather'),
('cole - med wash','Cole - Medium Wash'),
('cobalt - dk blue','Cobalt - Dark Blue'),
('willow - dk blue','Willow - Dark Blue'),
('santorini - lt wash','Santorini - Light Wash'),
('azul - md blue','Azul - Medium Blue'),
('skylar - lt blue','Skylar-LtBlue'),
('manila - lt wash w tint','Manila - Light Wash w Tint'),
('palms- md lt wash','Palms- Medium Light Wash'),
('periwinkle- lt wash','Periwinkle- Light Wash'),
('island breeze lt wash','Island Breeze Light wash'),
('flow wash - lt wash','Flow Wash - Light Wash'),
('saltwater - med wash','Saltwater - Medium Wash'),
('lt pink','Light Pink'),
('cave - lt wash','CAVE - Light Wash'),
('ibiza - md wash','Ibiza - Medium Wash'),
('bayou - med wash','Bayou - Medium Wash'),
('sea shell','Seashell'),
('marine- md wash','Marine- Medium Wash'),
('eaton - med wash','Eaton - Medium Wash'),
('sbltd blk camo','Sbltd Black Camo'),
('dusk--med blue','Dusk--Medium Blue'),
('cannes - med wash','Cannes - Medium Wash'),
('mist blue- lt wash','Mist Blue- Light Wash'),
('oxbloodcamo','Oxblood Camo'),
('carbon- dk wash','CARBON- Dark Wash'),
('forget me not','Forget-Me-Not'),
('chrcl hthr','Charcoal Heather'),
('nvy','Navy'),
('lasso wash - dk wash','Lasso Wash - Dark Wash'),
('blue island - md lt wash','Blue Island - Medium Light Wash'),
('ibiza - med wash','Ibiza - Medium Wash'),
('meltfield - med wash w tint','MELTFIELD - Medium Wash w Tint'),
('ivy- dk wash','IVY- Dark Wash'),
('saint lucia- med wash','Saint Lucia- Medium Wash'),
('rust - dk blue','Rust-Dark Blue'),
('iron blue - lt wash','Iron Blue - Light Wash'),
('luna-lt wash','Luna-Light Wash'),
('lt. grey hthr','Light Grey Heather'),
('ultramarine - med wash','Ultramarine - Medium Wash'),
('blk/blk','Black/Black'),
('blk/charcoal','Black/Charcoal'),
('blue fang - lt wash','Blue Fang - Light Wash'),
('steel blue - lt wash','Steel Blue - Light Wash'),
('steam wash - lt wash','Steam Wash - Light Wash'),
('static - blk acid wash','Static - Black Acid Wash'),
('spring water - lt wash','Spring Water - Light Wash'),
('cadet blue - med wash','Cadet Blue - Medium Wash'),
('charcoal blk','Charcoal Black'),
('oxford - med wash','Oxford - Medium Wash'),
('byron bay - med wash','Byron Bay - Medium Wash'),
('gray storm','Grey Storm'),
('blue stone med wash','Blue Stone - Medium Wash'),
('miami - lt blue','Miami - Light Blue'),
('nv/lt hthrgry','Nv/Light HthrGry'),
('caribbean - med wash','Caribbean - Medium Wash'),
('moisture - med wash','Moisture - Medium Wash'),
('lt grey cali bear','Light Grey Cali Bear'),
('burgndy/off white','Burgundy/Off White'),
('burgndy/chrcl','Burgundy/Charcoal'),
('newcastle-dk wsh','NewCastle-Dark Wash'),
('steam wash-lt wash','Steam Wash - Light Wash'),
('neptune - med wash','Neptune - Medium Wash'),
('boreal blue - med wash w tint','Boreal Blue - Medium Wash w Tint'),
('sulphur wash- dk grey','Sulphur Wash- Dark Grey'),
('surf - lt wash','Surf - Light Wash'),
('blk/lt. hthr gry','Black/Light Heather Grey'),
('misty bay - lt wash','Misty Bay - Light Wash'),
('mist drift - lt wash','Mist Drift - Light Wash'),
('alegria-md dark','ALEGRIA-Medium Dark'),
('blacksands - blk wash wtint','Blacksands - Black Wash wTint'),
('lt grey/charcoal','Light Grey/Charcoal'),
('everglades - med wash','Everglades - Medium Wash'),
('placid - lt wash','Placid - Light Wash'),
('pond - med wash','Pond - Medium Wash'),
('eclipse - med wash','Eclipse - Medium Wash'),
('driftwood - med wash','Driftwood - Medium Wash'),
('dk teal','Dark Teal'),
('fossil - med grey','Fossil - Medium Grey'),
('rocky - med grey','Rocky - Medium Grey'),
('volt - med wash w tint','Volt - Medium Wash w Tint'),
('currents - lt wash','Currents - Light Wash'),
('saltwater sky - lt wash w tint','Saltwater Sky - Light Wash w Tint'),
('sandcastle - lt wash','Sandcastle - Light Wash'),
('sea breeze- lt wash','Sea Breeze- Light Wash'),
('sea mist - lt wash','Sea Mist - Light Wash'),
('cinder - lt grey','Cinder - Light Grey'),
('sea spray - lt wash w tint','Sea Spray - Light Wash w Tint'),
('seal - lt grey','Seal - Light Grey'),
('gray wolf - lt gray','Grey Wolf - Light Grey'),
('oceanside - med wash','Oceanside - Medium Wash'),
('char grn','Char Green'),
('hthr chrcl/yellow','Heather Charcoal/Yellow'),
('med blue','Medium Blue'),
('new lands - md lt wash','New Lands - Medium Light Wash'),
('oasis- med wash','Oasis- Medium Wash'),
('sangromni/blk','SangrOmni/Black'),
('seaport - med wash','Seaport - Medium Wash'),
('black/lt grey','Black/Light Grey'),
('black/black marl','Black/Black Marled'),
('shadow wash- dk','Shadow Wash- Dark'),
('smokey- drk grey','Smokey- Dark Grey'),
('drk trpcl gry','Dark Tropical Grey'),
('double duff - lt wash','Double Duff - Light Wash'),
('lt hthr gry','Light Heather Grey'),
('sparky / dk hthr gry','Sparky / Dark Heather Grey'),
('salt haze - med wash w tint','Salt Haze - Medium Wash w Tint'),
('honey flsh','Honey Flash'),
('white/lt. heather grey','White/Light Heather Grey'),
('gry/blck','Grey/Black'),
('skylark - lt wash','Skylark - Light Wash'),
('caviar- drk black','Caviar- Dark Black'),
('lt lavender','Light Lavender'),
('nvy/mdhthrgry','Navy/MdHthrGry'),
('jet blck','Jet Black'),
('brooks - med wash','Brooks - Medium Wash'),
('red heathr','Red Heather'),
('sbltd grn camo','Sbltd Green Camo'),
('drk peach msty plms','Dark Peach Misty Palms'),
('chrcl hthr/blck','Charcoal Heather/Black'),
('bad lands - md wash','Bad Lands - Medium Wash'),
('hthr navy','Heather Navy'),
('blanco- lt white wash','Blanco- Light White Wash'),
('oceanic - lt wash','OCEANIC - Light Wash'),
('lt kelp','Light Kelp'),
('hthr chrcoal','Heather Charcoal'),
('chateau gray','Chateau Grey'),
('harbor - med wash-32','Harbor - Medium Wash'),
('open sea - lt wash w tint','Open Sea - Light Wash w Tint'),
('zuma - lt wash','Zuma - Light Wash'),
('snorlax - med wash','Snorlax - Medium Wash'),
('gun metal','Gunmetal'),
('frqncy strp','Frqncy Stripe'),
('storm gry','Storm Grey'),
('sunwashed blue - lt wash wtint','Sunwashed Blue - Light Wash wTint'),
('ibiza-med','Ibiza'),
('navy/light heather gry','Navy/Light Heather Grey'),
('white / black','White/Black'),
('estate blue omni/ blk','Estate Blue Omni/ Black'),
('new lands- md lt','New Lands- Medium Light'),
('pumice - med grey','PUMICE - Medium Grey'),
('gry strm/chrclhthr','Grey Storm/ChrclHthr'),
('newcastle - dk wash','NewCastle-Dark Wash'),
('true wash- drk','True Wash- Dark'),
('gry statc/blk strm','Grey Static/Black Storm'),
('gry mrl/blk','Grey Marled/Black'),
('lt blue/off white','Light Blue/Off White'),
('nvy snow','Navy Snow'),
('lt grey/blue','Light Grey/Blue'),
('oatml marl','Oatml Marled'),
('dark gray','Dark Grey'),
('saint lucia-med wash','Saint Lucia- Medium Wash'),
('green hthr camo','Green Heather Camo'),
('coastal blue - lt wash w tint','Coastal Blue - Light Wash w Tint'),
('green camo/med hthr gry','Green Camo/Medium Heather Grey'),
('gray storm/charcoal','Grey Storm/Charcoal'),
('sbltd nvy camo','Sbltd Navy Camo'),
('city wash- md dark','City Wash- Medium Dark'),
('gray snow','Grey Snow'),
('wavecrest - med wash w tint','WAVECREST - Medium Wash w Tint'),
('md grey marled','Medium Grey Marled'),
('hthr navy-m/5','Heather Navy'),
('heather sea blue-m/5','Heather Sea Blue'),
('moonwashed sand - lt wash','Moonwashed Sand - Light Wash'),
('harbor - med wash-38','Harbor - Medium Wash'),
('harbor - med wash-36','Harbor - Medium Wash'),
('harbor - med wash-34','Harbor - Medium Wash'),
('mystic- med wash','Mystic- Medium Wash'),
('nantucket - med wash','Nantucket - Medium Wash'),
('harbor - med wash-30','Harbor - Medium Wash'),
('harbor - med wash-29','Harbor - Medium Wash'),
('navy-m/10','Navy'),
('navy-m/5','Navy'),
('navy/blue','Navy Blue'),
('new kelly hth green','New Kelly Heather Green'),
('grey snow/chrc hethtr','Grey Snow/Charcoal Hethtr'),
('nvy/heritage blue','Navy/Heritage Blue'),
('ocean blue med wash','Ocean Blue Medium Wash'),
('outerbank - lt wash w tint','Outerbank - Light Wash w Tint'),
('glacier-xxl','Glacier'),
('glacier-xlg','Glacier'),
('glacier-sml','Glacier'),
('glacier-med','Glacier'),
('glacier-lrg','Glacier'),
('falcon-xxl','Falcon'),
('falcon-xlg','Falcon'),
('falcon-sml','Falcon'),
('falcon-med','Falcon'),
('falcon-lrg','Falcon'),
('pond - med wash-29','Pond - Medium Wash'),
('pond - med wash-30','Pond - Medium Wash'),
('pond - med wash-32','Pond - Medium Wash'),
('pond - med wash-34','Pond - Medium Wash'),
('pond - med wash-36','Pond - Medium Wash'),
('pond - med wash-38','Pond - Medium Wash'),
('apollo - med wash w tint','Apollo - Medium Wash w Tint'),
('red/light heather gry','Red/Light Heather Grey'),
('daybreak sky - med wash w tint','Daybreak Sky - Medium Wash w Tint'),
('royal hthr','Royal Heather'),
('rust - dk blue-29','Rust-Dark Blue'),
('rust - dk blue-30','Rust-Dark Blue'),
('rust - dk blue-32','Rust-Dark Blue'),
('rust - dk blue-34','Rust-Dark Blue'),
('rust - dk blue-36','Rust-Dark Blue'),
('rust - dk blue-38','Rust-Dark Blue'),
('sahara - med wash w tint','Sahara - Medium Wash w Tint'),
('salt lake - med wash','Salt Lake - Medium Wash'),
('crimson - dk wash w tint','Crimson - Dark Wash w Tint'),
('clyde - med wash','Clyde - Medium Wash'),
('sbltd brgndy camo','Sbltd Burgundy Camo'),
('scrthd blk','Scratched Black'),
('chrcl hthr/ltgry hthr','Charcoal Heather/LtGry Heather'),
('sea water - med dk wash','Sea Water - Medium Dark Wash'),
('seaside - lt wash','Seaside - Light Wash'),
('charcoal-30','Charcoal'),
('sierra- lt md wash','Sierra- Light Medium Wash'),
('simple sage cbo','Simple Sage Combo'),
('skyfall - lt wash','SKYFALL - Light Wash'),
('cerulean - med dark wash','Cerulean - Medium Dark Wash'),
('splash- drk wash','Splash- Dark Wash'),
('burgundy hthr','Burgundy Heather'),
('burgndy/chrcl-m/10','Burgundy/Charcoal'),
('brown/chrcl hthr','Brown/Charcoal Heather'),
('brngdy/mhthrgry','Burgundy/MHthrGry'),
('stone block cmbo','Stone Block Combo'),
('blue moon- md drk wash','Blue Moon- Medium Dark Wash'),
('amazon - med wash w tint','Amazon - Medium Wash w Tint'),
('blk/mdhthrgry','Black/MdHthrGry'),
('blk/heather','Black Heather'),
('blk spc dye / blk','Black Space Dye / Black'),
('blck/hthrgry','Black/HthrGry'),
('blck/brgndy','Black/Burgundy'),
('blck paradise-38','Black Paradise'),
('blck paradise-36','Black Paradise'),
('blck paradise-34','Black Paradise'),
('blck paradise-32','Black Paradise'),
('blck paradise-30','Black Paradise'),
('blck paradise-29','Black Paradise'),
('blck marl','Black Marled'),
('blck knght','Black Knight'),
('blck fade','Black Fade'),
('titanium gry gd','Titanium Grey GD'),
('black-m/10','Black'),
('typhoon- drk wash','Typhoon- Dark Wash'),
('veil - dark wash-29','Veil - Dark Wash'),
('veil - dark wash-30','Veil - Dark Wash'),
('veil - dark wash-32','Veil - Dark Wash'),
('veil - dark wash-34','Veil - Dark Wash'),
('veil - dark wash-36','Veil - Dark Wash'),
('veil - dark wash-38','Veil - Dark Wash'),
('beach side- lt wash','Beach Side- Light wash'),
('barcelona - lt wash','Barcelona - Light Wash'),
('warm gray','Warm Grey'),
('lt beige camo','Light Beige Camo'),
('lt gray/black','Light Grey/Black'),
('lt gray/navy','Light Grey/Navy'),
('lt green','Light Green'),
('kelly hthr','Kelly Heather'),
('lt grey tonal camo','Light Grey Tonal Camo'),
('lt grey/black','Light Grey/Black'),
('lt hthr/white','Light Heather/White'),
('lt. hthr gry/black','Light Heather Grey/Black'),
('lt. indigo','Light Indigo')
) AS v(raw_lower, canon)
ON CONFLICT (entity_id, raw_lower) DO UPDATE SET canonical_name = EXCLUDED.canonical_name;

CREATE OR REPLACE FUNCTION sync_received_dates(p_rows jsonb)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $func$
DECLARE n integer;
BEGIN
  WITH rows AS (
    SELECT upper(btrim(e->>'s')) AS style, lower(btrim(e->>'c')) AS rawc, (e->>'d')::date AS d
    FROM jsonb_array_elements(p_rows) e
    WHERE (e->>'s') IS NOT NULL AND (e->>'c') IS NOT NULL AND (e->>'d') ~ '^\d{4}-\d{2}-\d{2}$'
  ),
  resolved AS (
    SELECT r.style, lower(COALESCE(ca.canonical_name, r.rawc)) AS canon_l, r.d
    FROM rows r
    LEFT JOIN color_aliases ca ON ca.raw_lower = r.rawc
  ),
  maxd AS (
    SELECT style, canon_l, max(d) AS d FROM resolved GROUP BY style, canon_l
  )
  UPDATE inventory_layers l
  SET received_at = m.d::timestamptz
  FROM maxd m
  JOIN ip_item_master i ON upper(i.style_code) = m.style AND lower(btrim(i.color)) = m.canon_l
  WHERE l.item_id = i.id
    AND l.source_kind IN ('xoro_rest_size','opening_balance')
    AND l.received_at::date <> m.d;
  GET DIAGNOSTICS n = ROW_COUNT;
  RETURN n;
END $func$;
