-- ════════════════════════════════════════════════════════════════════════════
-- Backfill declared style colors from inventory (operator request 2026-06-13).
--
-- Every color present on a style's SKUs (ip_item_master.color, what the
-- Inventory Matrix shows) but NOT yet in the style's declared color set
-- (style_master.attributes.color_ids) is added, by matching the SKU color to a
-- color_master row. Matching is tolerant: it maps EVERY known spelling (raw +
-- the normalized canonical) to the canonical color_master id, so messy SKU
-- colors (e.g. PL styles still on raw casing) still resolve. Existing declared
-- color_ids are preserved (union). Backs up attributes first.
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS _style_attrs_backup_20260613 AS
  SELECT id, attributes FROM style_master;

CREATE TEMP TABLE _cmap(raw text, canon text) ON COMMIT DROP;
INSERT INTO _cmap(raw, canon) VALUES
('Black','Black'),
('VANISH-DK BLUE','Vanish-Dark Blue'),
('Charcoal','Charcoal'),
('Olive','Olive'),
('White','White'),
('SHIITAKE','Shiitake'),
('BELOW ZERO- LT WASH','Below Zero- Light Wash'),
('RINSE - DKBLUE','Rinse - DkBlue'),
('NAVY','Navy'),
('Khaki','Khaki'),
('BLCK PARADISE','Black Paradise'),
('BROWN','Brown'),
('MUSHROOM','Mushroom'),
('Moonless Nights','Moonless Nights'),
('Grey','Grey'),
('Lt Brown','Light Brown'),
('Dull Gold','Dull Gold'),
('Blk Camo','Black Camo'),
('AMERICANA','Americana'),
('Birch','Birch'),
('Lt Grey','Light Grey'),
('Green Camo','Green Camo'),
('Smoke Blue - Lt Blue','Smoke Blue - Light Blue'),
('Sky Blue','Sky Blue'),
('Stormy Weather','Stormy Weather'),
('BERMUDA - LT WASH','Bermuda - Light Wash'),
('HARBOR - MED WASH','Harbor - Medium Wash'),
('Burgundy','Burgundy'),
('Dutch Wash- Med','Dutch Wash- Medium'),
('Light Olive','Light Olive'),
('Americana- MdBlue','Americana- MdBlue'),
('Sodalite Blue','Sodalite Blue'),
('Crumble-MD BLU','Crumble-Medium BLU'),
('Charcoal Hthr','Charcoal Heather'),
('Sage','Sage'),
('Carbon- Blck','Carbon- Black'),
('Mineral- Lt Blue','Mineral- Light Blue'),
('Heather Grey','Heather Grey'),
('Daiquiri Green','Daiquiri Green'),
('CASPAIN - LT WASH','Caspain - Light Wash'),
('Blue Fog','Blue Fog'),
('SEA FLOOR - MED WASH','Sea Floor - Medium Wash'),
('Grape Wine','Grape Wine'),
('Blue Radiance','Blue Radiance'),
('Iceberg Green','Iceberg Green'),
('BUENOS AIRES - LT WASH','Buenos Aires - Light Wash'),
('Oyster Mushroom','Oyster Mushroom'),
('PYRITE-MED DARK WASH','PYRITE-Medium Dark Wash'),
('Red','Red'),
('ISLAND BREEZE','Island Breeze'),
('Cream Tonal Grizzly Camo','Cream Tonal Grizzly Camo'),
('Falcon','Falcon'),
('Navy Camo','Navy Camo'),
('Glacier','Glacier'),
('VERNAULK - LT WASH','Vernaulk - Light Wash'),
('Steel Grey','Steel Grey'),
('Deep Teal','Deep Teal'),
('Wither Fade Ashen Camo','Wither Fade Ashen Camo'),
('Vallarta Blue','Vallarta Blue'),
('Raindrops','Raindrops'),
('Forget-Me-Not','Forget-Me-Not'),
('DEEP BLACK','Deep Black'),
('Espresso','Espresso'),
('Naval Academy','Naval Academy'),
('Skyline- Md Lt','Skyline- Medium Light'),
('Medusa-Dk Blue','Medusa-Dark Blue'),
('Tonal Grey Camo','Tonal Grey Camo'),
('Sahara Camo','Sahara Camo'),
('T20 Oceanic Blues','T20 Oceanic Blues'),
('GORDON - LT WASH','Gordon - Light Wash'),
('Sun Kissed Coral','Sun Kissed Coral'),
('Dark Olive','Dark Olive'),
('Ultimate Grey','Ultimate Grey'),
('Autumn Fade Grizzly Camo','Autumn Fade Grizzly Camo'),
('T16 Vtg Blk/Oyst Mushroom','T16 Vtg Black/Oyst Mushroom'),
('New Wheat- Md Dark','New Wheat- Medium Dark'),
('HAMMOCK','Hammock'),
('DRESS BLUES','Dress Blues'),
('Gunmetal','Gunmetal'),
('Lavender','Lavender'),
('Medm Hthr Gry','Medium Heather Grey'),
('Woodland Camo','Woodland Camo'),
('CubanSnd- Md Wash','CubanSnd- Medium Wash'),
('Blackberry','Blackberry'),
('Rust-Dk Blue','Rust-Dark Blue'),
('Roasted Cashew','Roasted Cashew'),
('T1 Black','T1 Black'),
('FOREST NIGHT','Forest Night'),
('Paradise Green','Paradise Green'),
('Heather Gray','Heather Grey'),
('Morning Dew','Morning Dew'),
('FLEETWOOD - MED WASH','Fleetwood - Medium Wash'),
('Peach Echo','Peach Echo'),
('CLOUD DANCER','Cloud Dancer'),
('Blk/Chrc Hthr','Black/Charcoal Heather'),
('Sandlot - Med Wash','Sandlot - Medium Wash'),
('Pink','Pink'),
('Lt Blue','Light Blue'),
('Drought Wash - Med Light','Drought Wash - Medium Light'),
('Fair Aqua','Fair Aqua'),
('Tibetan Red','Tibetan Red'),
('Blue Bleached','Blue Bleached'),
('Kelp','Kelp'),
('Sand','Sand'),
('Red/Black','Red/Black'),
('WALNUT','Walnut'),
('Off White','Off White'),
('Mushroom- Lt Grey','Mushroom- Light Grey'),
('BKB','BKB'),
('Elderberry','Elderberry'),
('Crystal Pink','Crystal Pink'),
('Sea Otter','Sea Otter'),
('Simple Sage GD','Simple Sage GD'),
('Sangria','Sangria'),
('GRAPE WINE MANTA','Grape Wine Manta'),
('Stone','Stone'),
('MOONLESS NIGHTS MANTA','Moonless Nights Manta'),
('TD ForgetMeNot/Dp Teal','TD ForgetMeNot/Dp Teal'),
('Creek - Md Lt Wash','Creek - Medium Light Wash'),
('Grey Ashen Camo','Grey Ashen Camo'),
('BRUSHED ALLOY','Brushed Alloy'),
('skyway','Skyway'),
('Black/White','Black/White'),
('Redwoods - Dark Wash','Redwoods - Dark Wash'),
('Beige','Beige'),
('Beach Wash - Lt Wash','Beach Wash - Light Wash'),
('Skylar-LtBlue','Skylar-LtBlue'),
('EATON - LT WASH','Eaton - Light Wash'),
('Media Park- Drk Wash','Media Park- Dark Wash'),
('GoldenOak','GoldenOak'),
('Black/Gray','Black/Grey'),
('Purple Rose','Purple Rose'),
('Aruba- Md Wash','Aruba- Medium Wash'),
('Blue','Blue'),
('Tan','Tan'),
('Sediment - Lt Wash','Sediment - Light Wash'),
('Hematite - Washed Black','Hematite - Washed Black'),
('River Lee - Dark Wash','River Lee - Dark Wash'),
('Blanc de Blanc','Blanc de Blanc'),
('Assorted','Assorted'),
('Typhoon','Typhoon'),
('Yellow Cream','Yellow Cream'),
('Black Hthr','Black Heather'),
('Seashell','Seashell'),
('Medium Wash','Medium Wash'),
('T15 Vtg Black/Peach Echo','T15 Vtg Black/Peach Echo'),
('Indigo Marled','Indigo Marled'),
('Blue Stone - Med Wash','Blue Stone - Medium Wash'),
('Sand Marled','Sand Marled'),
('Crow - Washed Blk','Crow - Washed Black'),
('Surf Spray','Surf Spray'),
('Royal Blue','Royal Blue'),
('Horizon','Horizon'),
('Gateway - Med Wash','Gateway - Medium Wash'),
('Robin - Md Blue','Robin - Medium Blue'),
('Navy Hthr','Navy Heather'),
('Sandstone','Sandstone'),
('Cole - Med Wash','Cole - Medium Wash'),
('Cobalt - Dk Blue','Cobalt - Dark Blue'),
('Chocolate Malt','Chocolate Malt'),
('Slate/Off White','Slate/Off White'),
('Willow - Dk Blue','Willow - Dark Blue'),
('SANTORINI - LT WASH','Santorini - Light Wash'),
('Cloud Cream','Cloud Cream'),
('Azul - Md Blue','Azul - Medium Blue'),
('Dark Brown','Dark Brown'),
('Burgundy/White','Burgundy/White'),
('Black/Red','Black/Red'),
('Skylar - Lt Blue','Skylar-LtBlue'),
('Manila - Lt Wash w Tint','Manila - Light Wash w Tint'),
('Teal','Teal'),
('Palms- Md Lt Wash','Palms- Medium Light Wash'),
('WASHED CHARCOAL','Washed Charcoal'),
('Periwinkle- Lt Wash','Periwinkle- Light Wash'),
('TD Elderberry/Grape Wine','TD Elderberry/Grape Wine'),
('Bark - Grey w Tint','Bark - Grey w Tint'),
('Camel','Camel'),
('LBL','LBL'),
('ISLAND BREEZE LT WASH','Island Breeze Light wash'),
('Flow Wash - Lt Wash','Flow Wash - Light Wash'),
('Military Olive','Military Olive'),
('Oxblood Camo','Oxblood Camo'),
('Saltwater - Med Wash','Saltwater - Medium Wash'),
('Copper','Copper'),
('Black/ Off White','Black/ Off White'),
('Sandlot','Sandlot'),
('TD Black','TD Black'),
('Lt Pink','Light Pink'),
('Jade','Jade'),
('BLACK WATER CAMO','Black Water Camo'),
('Night Camo','Night Camo'),
('Yellow','Yellow'),
('Black Shadow GD','Black Shadow GD'),
('WASHED Olive','WASHED Olive'),
('OCEAN HUT','Ocean Hut'),
('CAVE - Lt Wash','CAVE - Light Wash'),
('IBIZA - MD WASH','Ibiza - Medium Wash'),
('BAYOU - MED WASH','Bayou - Medium Wash'),
('Sea shell','Seashell'),
('MARINE- MD WASH','Marine- Medium Wash'),
('Eaton - Med Wash','Eaton - Medium Wash'),
('Sbltd Blk Camo','Sbltd Black Camo'),
('LIGHT WASH','Light Wash'),
('T18 Black/Lavender','T18 Black/Lavender'),
('Obsidian','Obsidian'),
('Yellow/Black','Yellow/Black'),
('Dusk--Med Blue','Dusk--Medium Blue'),
('Marine Camo','Marine Camo'),
('Mineral Red','Mineral Red'),
('Blue Shadow','Blue Shadow'),
('CANNES - MED WASH','Cannes - Medium Wash'),
('Mist Blue- Lt Wash','Mist Blue- Light Wash'),
('OxBloodCamo','Oxblood Camo'),
('Mykonos','Mykonos'),
('Bottle Green','Bottle Green'),
('WHT','WHT'),
('BPK','BPK'),
('Blush','Blush'),
('Dark Slate','Dark Slate'),
('CARBON- Dk Wash','CARBON- Dark Wash'),
('Forget Me Not','Forget-Me-Not'),
('Chrcl Hthr','Charcoal Heather'),
('NVY','Navy'),
('LASSO WASH - DK WASH','Lasso Wash - Dark Wash'),
('Agate','Agate'),
('Nightfall','Nightfall'),
('Steel','Steel'),
('KHK','KHK'),
('TD26 Black/White','TD26 Black/White'),
('Coronet Blue','Coronet Blue'),
('Midnight','Midnight'),
('OWT','OWT'),
('Blue Tint','Blue Tint'),
('H.G','H.G'),
('TD Sodalite Blue','TD Sodalite Blue'),
('FIN GD','Fin Gd'),
('ET SURFBOARD','Et Surfboard'),
('White/Black','White/Black'),
('Algae - Dark Wash','Algae - Dark Wash'),
('LemonDrp','LemonDrp'),
('Black Grave Garden','Black Grave Garden'),
('TD Sky Blue','TD Sky Blue'),
('Fuchsia','Fuchsia'),
('Blue Island - Md Lt Wash','Blue Island - Medium Light Wash'),
('REVISED SURF HUT','Revised Surf Hut'),
('TD Olive','TD Olive'),
('HERITAGE SURF','Heritage Surf'),
('Atlantic Blue','Atlantic Blue'),
('SHADOW GREEN','Shadow Green'),
('Graphite','Graphite'),
('SURFER SUPPLY','Surfer Supply'),
('Blue Camo','Blue Camo'),
('Blue/Coral','Blue/Coral'),
('Indigo','Indigo'),
('Tonal Black Camo','Tonal Black Camo'),
('Ibiza - Med Wash','Ibiza - Medium Wash'),
('MELTFIELD - Med Wash w Tint','MELTFIELD - Medium Wash w Tint'),
('Sea Blue','Sea Blue'),
('IVY- Dk Wash','IVY- Dark Wash'),
('Tropical Peach','Tropical Peach'),
('Saint Lucia- Med Wash','Saint Lucia- Medium Wash'),
('Eclipse','Eclipse'),
('YLW','YLW'),
('Imperial Blue','Imperial Blue'),
('SURF HUT','Surf Hut'),
('RUST - DK Blue','Rust-Dark Blue'),
('Ronto Wash','Ronto Wash'),
('Mahogany - Black w Tint','Mahogany - Black w Tint'),
('IRON BLUE - LT WASH','Iron Blue - Light Wash'),
('Iron Gate','Iron Gate'),
('MAGIC MAUVE','Magic Mauve'),
('Luna-Lt Wash','Luna-Light Wash'),
('Lt. Grey Hthr','Light Grey Heather'),
('Autumn Grizzly Camo','Autumn Grizzly Camo'),
('Very Peri','Very Peri'),
('BLACK / YELLOW','Black / Yellow'),
('ULTRAMARINE - MED WASH','Ultramarine - Medium Wash'),
('Zinc','Zinc'),
('Black/Egret','Black/Egret'),
('Turqouise','Turqouise'),
('Black/Salsa','Black/Salsa'),
('Black/Shaved Chocolate','Black/Shaved Chocolate'),
('THUNDERBOLT - DARK WASH','Thunderbolt - Dark Wash'),
('BlK/Blk','Black/Black'),
('Blk/Charcoal','Black/Charcoal'),
('T9 Navy','T9 Navy'),
('BLUE FANG - LT WASH','Blue Fang - Light Wash'),
('BLUE HAWK - DARK WASH','Blue Hawk - Dark Wash'),
('Storm','Storm'),
('STONE BLOCK GD','Stone Block Gd'),
('STEEL BLUE - LT WASH','Steel Blue - Light Wash'),
('Steam Wash - Lt Wash','Steam Wash - Light Wash'),
('Static - Blk Acid Wash','Static - Black Acid Wash'),
('Starlight Blue','Starlight Blue'),
('Spring Water - Lt Wash','Spring Water - Light Wash'),
('CADET BLUE - MED WASH','Cadet Blue - Medium Wash'),
('Charcoal Blk','Charcoal Black'),
('CHESTNUT','Chestnut'),
('Apricot','Apricot'),
('Whitecap','Whitecap'),
('FRAGILE OCEAN','Fragile Ocean'),
('OYSTER','Oyster'),
('OXFORD - MED WASH','Oxford - Medium Wash'),
('Olive Gradient Camo','Olive Gradient Camo'),
('Green Pumpkin','Green Pumpkin'),
('ICE FIELD - Light Wash w Tint','ICE FIELD - Light Wash w Tint'),
('WASHED BROWN','Washed Brown'),
('Ink Teal','Ink Teal'),
('Navy/Off White','Navy/Off White'),
('Cappuccino','Cappuccino'),
('Panther - Black','Panther - Black'),
('CALM FRONT - Light Wash','CALM FRONT - Light Wash'),
('Blanco','Blanco'),
('Chinois Green','Chinois Green'),
('Bonsai - Dark Wash w Tint','Bonsai - Dark Wash w Tint'),
('BYRON BAY - MED WASH','Byron Bay - Medium Wash'),
('Gray Storm','Grey Storm'),
('Blue Stone Med Wash','Blue Stone - Medium Wash'),
('Tsunami','Tsunami'),
('Ash Grey','Ash Grey'),
('Twill GD','Twill GD'),
('Miami - Lt Blue','Miami - Light Blue'),
('Overcast - Lt.Blue','Overcast - Lt.Blue'),
('Aloe','Aloe'),
('Blue Jean','Blue Jean'),
('Charcoal/Grey','Charcoal/Grey'),
('Nv/Lt HthrGry','Nv/Light HthrGry'),
('WASHED Black','WASHED Black'),
('Caviar Wash','Caviar Wash'),
('T4 Pink / Blue','T4 Pink / Blue'),
('Caribbean - Med Wash','Caribbean - Medium Wash'),
('Abyss','Abyss'),
('Ocean Teal','Ocean Teal'),
('Heather Navy','Heather Navy'),
('Taupe Grey','Taupe Grey'),
('TD Ginger','TD Ginger'),
('Aqua','Aqua'),
('Moisture - Med Wash','Moisture - Medium Wash'),
('Tea Hunters Camo','Tea Hunters Camo'),
('Lt Grey Cali Bear','Light Grey Cali Bear'),
('SOUTH COAST','South Coast'),
('Starlght Blue','Starlght Blue'),
('Burgndy/Off White','Burgundy/Off White'),
('Burgndy/Chrcl','Burgundy/Charcoal'),
('NewCastle-DK Wsh','NewCastle-Dark Wash'),
('STEAM WASH-LT WASH','Steam Wash - Light Wash'),
('Neptune - Med Wash','Neptune - Medium Wash'),
('Brown Camo','Brown Camo'),
('BRIG SURF','Brig Surf'),
('Boreal Blue - Med Wash w Tint','Boreal Blue - Medium Wash w Tint'),
('Blue Tide - Dark Wash w Tint','Blue Tide - Dark Wash w Tint'),
('Hailstorm - Dark Wash','Hailstorm - Dark Wash'),
('Sulphur Wash- Dk Grey','Sulphur Wash- Dark Grey'),
('Surf - Lt Wash','Surf - Light Wash'),
('SURF CITY','Surf City'),
('Blue Fog Topography','Blue Fog Topography'),
('Blue Bleach','Blue Bleach'),
('T19 Oceanic Greens','T19 Oceanic Greens'),
('T7 Spiral lav/aqua','T7 Spiral lav/aqua'),
('Moonless Nights Topography','Moonless Nights Topography'),
('Blk/Lt. Hthr Gry','Black/Light Heather Grey'),
('Moon Mist - Grey Wash','Moon Mist - Grey Wash'),
('Misty Bay - Lt Wash','Misty Bay - Light Wash'),
('THALIA','Thalia'),
('Mist Drift - Lt Wash','Mist Drift - Light Wash'),
('Tonal Green Camo','Tonal Green Camo'),
('Mint','Mint'),
('ALEGRIA-Md Dark','ALEGRIA-Medium Dark'),
('Blacksands - Blk Wash wTint','Blacksands - Black Wash wTint'),
('Trench Water - Dark Wash w Tint','Trench Water - Dark Wash w Tint'),
('Trunks','Trunks'),
('Twilight','Twilight'),
('Black/Birch','Black/Birch'),
('Hudson Wash','Hudson Wash'),
('VEIL - DARK WASH','Veil - Dark Wash'),
('Black Check','Black Check'),
('Black Cali Bear','Black Cali Bear'),
('Black Blessed Madonna','Black Blessed Madonna'),
('Lt Grey/Charcoal','Light Grey/Charcoal'),
('Blac','Blac'),
('Vista','Vista'),
('Peach Parfait','Peach Parfait'),
('Pepper','Pepper'),
('PEPPER - ACID GREY','PEPPER - Acid Grey'),
('Everglades - Med Wash','Everglades - Medium Wash'),
('PLACID - LT WASH','Placid - Light Wash'),
('POND - MED WASH','Pond - Medium Wash'),
('ELKMONT TRADING','Elkmont Trading'),
('Eclipse - Med Wash','Eclipse - Medium Wash'),
('Navy Chevron','Navy Chevron'),
('DULL GOLD GD','Dull Gold Gd'),
('Driftwood - Med Wash','Driftwood - Medium Wash'),
('Dk Teal','Dark Teal'),
('Fossil - Med Grey','Fossil - Medium Grey'),
('River and Roads','River and Roads'),
('VNK','VNK'),
('Deep Black GD','Deep Black GD'),
('Rocky - Med Grey','Rocky - Medium Grey'),
('Wavey','Wavey'),
('Volt - Med Wash w Tint','Volt - Medium Wash w Tint'),
('Baby Pink','Baby Pink'),
('Currents - Lt Wash','Currents - Light Wash'),
('Saltwater Sky - Lt Wash w Tint','Saltwater Sky - Light Wash w Tint'),
('Salty''s Surf Shop','Salty''s Surf Shop'),
('Opal Grey','Opal Grey'),
('Sandcastle - Lt Wash','Sandcastle - Light Wash'),
('GOR','GOR'),
('Sapphire','Sapphire'),
('Sea Breeze- Lt Wash','Sea Breeze- Light Wash'),
('Sea Mist - Lt Wash','Sea Mist - Light Wash'),
('Olv/ChrclHthr','Olv/ChrclHthr'),
('Cinder - Lt Grey','Cinder - Light Grey'),
('Medium Blue','Medium Blue'),
('Sea Spray - Lt Wash w Tint','Sea Spray - Light Wash w Tint'),
('Seal - Lt Grey','Seal - Light Grey'),
('Shadow Wash Black','Shadow Wash Black'),
('Gray Wolf - Lt Gray','Grey Wolf - Light Grey'),
('Oceanside - Med Wash','Oceanside - Medium Wash'),
('Slate','Slate'),
('Snow','Snow'),
('Green Mix','Green Mix'),
('Agave Green','Agave Green'),
('Alpine Green','Alpine Green'),
('Artemis','Artemis'),
('Autumn Camo','Autumn Camo'),
('Black Storm','Black Storm'),
('Black/Black','Black/Black'),
('Black/Teal','Black/Teal'),
('Blanc de Blanc Lake Camo','Blanc de Blanc Lake Camo'),
('Blue Mix','Blue Mix'),
('Blue Navy','Blue Navy'),
('Brown Mix','Brown Mix'),
('BUR','BUR'),
('Burgundy Mix','Burgundy Mix'),
('Char Grn','Char Green'),
('Charcoal Marled','Charcoal Marled'),
('Charcoal Mix','Charcoal Mix'),
('CHR','CHR'),
('Coronet Blue Lake Camo','Coronet Blue Lake Camo'),
('Dark Pine','Dark Pine'),
('DARK WASH','Dark Wash'),
('Dazzling Blue/Cloud Dancer','Dazzling Blue/Cloud Dancer'),
('DUSK','DUSK'),
('Falcon Lake Camo','Falcon Lake Camo'),
('Forget-Me-Not Whales','Forget-Me-Not Whales'),
('FUS','FUS'),
('Green','Green'),
('Green Navy','Green Navy'),
('Green Pumpkin Lake Camo','Green Pumpkin Lake Camo'),
('HOBIE SURF','Hobie Surf'),
('Hthr Chrcl/Yellow','Heather Charcoal/Yellow'),
('Ice Melt','Ice Melt'),
('Ice Water','Ice Water'),
('JACKS SURFBOARDS','Jacks Surfboards'),
('KRAKEN','Kraken'),
('Lava','Lava'),
('Lyons Blue','Lyons Blue'),
('Maroon','Maroon'),
('Med Blue','Medium Blue'),
('MNT','MNT'),
('Moonrock','Moonrock'),
('Mysters Seas','Mysters Seas'),
('Navy/White/Stormy','Navy/White/Stormy'),
('New Lands - Md Lt Wash','New Lands - Medium Light Wash'),
('Oasis- Med Wash','Oasis- Medium Wash'),
('Oatmilk','Oatmilk'),
('Ocean Tide','Ocean Tide'),
('Off White/Burgundy','Off White/Burgundy'),
('Off White/Royal','Off White/Royal'),
('Orange','Orange'),
('ORG','ORG'),
('PINK OMBRE WASH','Pink Ombre Wash'),
('Pumice Stone','Pumice Stone'),
('PUR','PUR'),
('Raspberry Mandarin','Raspberry Mandarin'),
('RYB','RYB'),
('SangrOmni/Blk','SangrOmni/Black'),
('SEAPORT - MED WASH','Seaport - Medium Wash'),
('Seaweed - Dark Wash','Seaweed - Dark Wash'),
('SHOREBREAK','Shorebreak'),
('Slate Blue','Slate Blue'),
('Sterling','Sterling'),
('SURF, WIND & FIRE','Surf, Wind & Fire'),
('T8 Rainbow Sherbet','T8 Rainbow Sherbet'),
('Tea','Tea'),
('Tur','Tur'),
('WAVE RIDING VEHICLES','Wave Riding Vehicles'),
('Shiitake/Black','Shiitake/Black'),
('Brick','Brick'),
('Black/Tan','Black/Tan'),
('Trey Lavender','Trey Lavender'),
('Black/Olive','Black/Olive'),
('Purple','Purple'),
('Storm Blue/Apricot','Storm Blue/Apricot'),
('STORM CAMO','Storm Camo'),
('Orion','Orion'),
('Black/Lt Grey','Black/Light Grey'),
('Black/Black Marl','Black/Black Marled'),
('Blueberry','Blueberry'),
('Emerald/Grey','Emerald/Grey'),
('Shadow Wash- Dk','Shadow Wash- Dark'),
('Capri Blue','Capri Blue'),
('Undertow','Undertow'),
('Real Teal','Real Teal'),
('Sunny Daze','Sunny Daze'),
('Canyon Sunset','Canyon Sunset'),
('Peach','Peach'),
('Smokey- Drk Grey','Smokey- Dark Grey'),
('Moonless Nights Lake Camo','Moonless Nights Lake Camo'),
('Drk Trpcl Gry','Dark Tropical Grey'),
('DOUBLE DUFF - LT WASH','Double Duff - Light Wash'),
('Aminism','Aminism'),
('Desert Sage','Desert Sage'),
('Shamrock Green/Off White','Shamrock Green/Off White'),
('DEEP BLUE','Deep Blue'),
('Light Khaki','Light Khaki'),
('DAWN','DAWN'),
('Heather Grey/Slate','Heather Grey/Slate'),
('T17 Black/Discharge','T17 Black/Discharge'),
('Sonar','Sonar'),
('Kauai','Kauai'),
('Lt Hthr Gry','Light Heather Grey'),
('Spa Blue','Spa Blue'),
('NvySpaceDye','NvySpaceDye'),
('Oatmeal','Oatmeal'),
('Sparky / Dk Hthr Gry','Sparky / Dark Heather Grey'),
('Dark Khaki','Dark Khaki'),
('Winston Wash','Winston Wash'),
('Navy/Peach','Navy/Peach'),
('Charcoal Clear Camo','Charcoal Clear Camo'),
('SHIITAKE/ OFF WHITE','Shiitake/ Off White'),
('BlddStone','BlddStone'),
('Merlot','Merlot'),
('Sailor Wash','Sailor Wash'),
('Navy Oil','Navy Oil'),
('Salsa/Black','Salsa/Black'),
('Salt Haze - Med Wash w Tint','Salt Haze - Medium Wash w Tint'),
('HONEY FLSH','Honey Flash'),
('Pink/Blue','Pink/Blue'),
('Shiitake/Birch','Shiitake/Birch'),
('Wither Fade','Wither Fade'),
('Coal - Dark Grey','Coal - Dark Grey'),
('WHITE/LT. HEATHER GREY','White/Light Heather Grey'),
('Cloud Blue','Cloud Blue'),
('Brown Clear Camo','Brown Clear Camo'),
('Gry/Blck','Grey/Black'),
('White Camo','White Camo'),
('White/Blue','White/Blue'),
('Orchid','Orchid'),
('Og Camo','Og Camo'),
('Chocolate','Chocolate'),
('Thyme','Thyme'),
('Fountain Blue','Fountain Blue'),
('Skylark - Lt Wash','Skylark - Light Wash'),
('Stn Splattr','Stn Splattr'),
('Blanco Lilac','Blanco Lilac'),
('Caviar- Drk Black','Caviar- Dark Black'),
('03SF-Charcoal','03SF-Charcoal'),
('Lt Lavender','Light Lavender'),
('Nvy/MdHthrGry','Navy/MdHthrGry'),
('CREAM','Cream'),
('Coral Cobalt','Coral Cobalt'),
('Fiesta','Fiesta'),
('Oxblood','Oxblood'),
('Estate Blue','Estate Blue'),
('Army Green Camo','Army Green Camo'),
('TrueGrnCamo','TrueGrnCamo'),
('Heather Sea Blue','Heather Sea Blue'),
('Copen Blue Wash','Copen Blue Wash'),
('Stormy','Stormy'),
('Sangria Omni','Sangria Omni'),
('PROOF LAB','Proof Lab'),
('Maelstrom','Maelstrom'),
('Jet Blck','Jet Black'),
('BROOKS - MED WASH','Brooks - Medium Wash'),
('Blue Slate','Blue Slate'),
('Raspberry Wine','Raspberry Wine'),
('Malibu','Malibu'),
('High Waters - Dark Wash','High Waters - Dark Wash'),
('Blue Radience','Blue Radience'),
('WOODLAND CAM','Woodland Cam'),
('Sunset','Sunset'),
('Black Oil','Black Oil'),
('CLOVER','Clover'),
('Red Heathr','Red Heather'),
('Red/Beige','Red/Beige'),
('Nieve','Nieve'),
('Sbltd Grn Camo','Sbltd Green Camo'),
('Reef','Reef'),
('Drk Peach Msty Plms','Dark Peach Misty Palms'),
('Chrcl Hthr/Blck','Charcoal Heather/Black'),
('Chain','Chain'),
('SURF SUPPLIES','Surf Supplies'),
('Delphinium Blue','Delphinium Blue'),
('Bad Lands - Md Wash','Bad Lands - Medium Wash'),
('Riviera','Riviera'),
('Chocolate/Tan','Chocolate/Tan'),
('Olive Heather','Olive Heather'),
('Burgundy/Gold','Burgundy/Gold'),
('Peaks','Peaks'),
('Crimson Stripe','Crimson Stripe'),
('Light HG/Charcoal','Light HG/Charcoal'),
('Medium Grey','Medium Grey'),
('Chocolate Torte/Shaved Chocolate','Chocolate Torte/Shaved Chocolate'),
('GUAVA','Guava'),
('Grey Camo','Grey Camo'),
('Blood','Blood'),
('Wither Fade Camo','Wither Fade Camo'),
('Hthr Navy','Heather Navy'),
('Blanco- Lt White Wash','Blanco- Light White Wash'),
('OCEANIC - Lt Wash','OCEANIC - Light Wash'),
('Lt Kelp','Light Kelp'),
('Hthr Chrcoal','Heather Charcoal'),
('Serene','Serene'),
('Chateau Gray','Chateau Grey'),
('CHARCOAL/ORANGE','Charcoal/Orange'),
('Shiitake Hunters Camo','Shiitake Hunters Camo'),
('Olive Vine','Olive Vine'),
('olive/off white','Olive/Off White'),
('Harbor - Med Wash-32','Harbor - Medium Wash'),
('Naval Academy/BlncDeBlnc','Naval Academy/BlncDeBlnc'),
('Omen','Omen'),
('Skydiver Blue/White','Skydiver Blue/White'),
('Open Sea - Lt Wash w Tint','Open Sea - Light Wash w Tint'),
('Navy Blue','Navy Blue'),
('Zuma - Lt Wash','Zuma - Light Wash'),
('Honey','Honey'),
('Snorlax - Med Wash','Snorlax - Medium Wash'),
('Burgundy/Charcoal','Burgundy/Charcoal'),
('Soft Serve','Soft Serve'),
('Gun Metal','Gunmetal'),
('Navy Sky','Navy Sky'),
('Steam Wash','Steam Wash'),
('Heritage','Heritage'),
('Frqncy Strp','Frqncy Stripe'),
('Frost','Frost'),
('Ice Blue','Ice Blue'),
('FOG - Grey','FOG - Grey'),
('FLOHANA','Flohana'),
('Storm Gry','Storm Grey'),
('navy/black','Navy/Black'),
('Pastel Lght Pink','Pastel Lght Pink'),
('Mocha Heather','Mocha Heather'),
('Sunwashed Blue - Lt Wash wTint','Sunwashed Blue - Light Wash wTint'),
('IBIZA-Med','Ibiza'),
('Blue Mist','Blue Mist'),
('Navy/Light Heather Gry','Navy/Light Heather Grey'),
('SURFERS SUPPLIES','Surfers Supplies'),
('Navy/Navy','Navy/Navy'),
('BlkSpaceDye','BlkSpaceDye'),
('T6 Lavender/blue','T6 Lavender/blue'),
('Monaco Blue','Monaco Blue'),
('Alchemy','Alchemy'),
('PFD','PFD'),
('Navy/Peony','Navy/Peony'),
('TD 13 BLUE/ORCHID','Td 13 Blue/Orchid'),
('Hunter','Hunter'),
('White / Black','White/Black'),
('ET SURFBOARDS','Et Surfboards'),
('PNK','PNK'),
('Estate Blue Omni/ Blk','Estate Blue Omni/ Black'),
('Neon Mint heather','Neon Mint heather'),
('New Lands- Md Lt','New Lands- Medium Light'),
('PUMICE - Med Grey','PUMICE - Medium Grey'),
('TibetanRed/MoonlssNights','TibetanRed/MoonlssNights'),
('Gry Strm/ChrclHthr','Grey Storm/ChrclHthr'),
('Newcastle - Dk Wash','NewCastle-Dark Wash'),
('Tonal Khaki Camo','Tonal Khaki Camo'),
('Tree Camo','Tree Camo'),
('True Blue','True Blue'),
('True Wash- Drk','True Wash- Dark'),
('WhtCapGrey/Tibetan Red','WhtCapGrey/Tibetan Red'),
('Estate','Estate'),
('Ziggy','Ziggy'),
('Ensign','Ensign'),
('Gry Statc/Blk Strm','Grey Static/Black Storm'),
('Black Wash','Black Wash'),
('Valentine','Valentine'),
('Black Slub','Black Slub'),
('Black Sands','Black Sands'),
('Dusty Plum','Dusty Plum'),
('Gry Mrl/Blk','Grey Marled/Black'),
('DkSprng/MdGry','DkSprng/MdGry'),
('River Blue','River Blue'),
('Autumn','Autumn'),
('Deathstar','Deathstar'),
('Aster','Aster'),
('Asphalt Wash','Asphalt Wash'),
('Robin','Robin'),
('ASH','ASH'),
('Lt Blue/Off White','Light Blue/Off White'),
('Rose Red','Rose Red'),
('Nugget','Nugget'),
('Royal/Off White','Royal/Off White'),
('MdmGryHthr/ChrlHthr','MdmGryHthr/ChrlHthr'),
('Dark Peach','Dark Peach'),
('Nvy Snow','Navy Snow'),
('LT GREY/BLUE','Light Grey/Blue'),
('Mercury','Mercury'),
('JYNX - DARK WASH','Jynx - Dark Wash'),
('Juniper','Juniper'),
('Arnav - Dark Wash','Arnav - Dark Wash'),
('Washed Stone','Washed Stone'),
('Oatml Marl','Oatml Marled'),
('IRON & WINE','Iron & Wine'),
('Dark Gray','Dark Grey'),
('Dark Denim Wash','Dark Denim Wash'),
('Saint Lucia-Med Wash','Saint Lucia- Medium Wash'),
('Harbour Blue','Harbour Blue'),
('Green Hthr Camo','Green Heather Camo'),
('Cream Grizzly Camo','Cream Grizzly Camo'),
('Coral','Coral'),
('Coastal Blue - Lt Wash w Tint','Coastal Blue - Light Wash w Tint'),
('Green Camo/Med Hthr Gry','Green Camo/Medium Heather Grey'),
('Gray Storm/Charcoal','Grey Storm/Charcoal'),
('Sbltd Nvy Camo','Sbltd Navy Camo'),
('Scratched Black','Scratched Black'),
('Climbing Ivy','Climbing Ivy'),
('Military Green','Military Green'),
('City Wash- Md Dark','City Wash- Medium Dark'),
('Citrus Yellow','Citrus Yellow'),
('Army Green','Army Green'),
('Chocolate Plum','Chocolate Plum'),
('Gray Snow','Grey Snow'),
('Snd Camo4','Snd Camo4'),
('Marine Wash','Marine Wash'),
('WAVECREST - Med Wash w Tint','WAVECREST - Medium Wash w Tint'),
('Maui - Light Wash','Maui - Light Wash'),
('MD Grey Marled','Medium Grey Marled'),
('Indigo Rip','Indigo Rip'),
('Medium Denim Wash','Medium Denim Wash'),
('IcebrgGreen/MnlssNight','IcebrgGreen/MnlssNight'),
('Hthr Navy-M/5','Heather Navy'),
('Millie Wash','Millie Wash'),
('Honey / Mustard','Honey / Mustard'),
('Wheat','Wheat'),
('Heather Sea Blue-M/5','Heather Sea Blue'),
('Monument','Monument'),
('Moonless Nights/Lavndr','Moonless Nights/Lavndr'),
('Moonwashed Sand - Lt Wash','Moonwashed Sand - Light Wash'),
('Mossy Olive','Mossy Olive'),
('Harbor - Med Wash-38','Harbor - Medium Wash'),
('Harbor - Med Wash-36','Harbor - Medium Wash'),
('Harbor - Med Wash-34','Harbor - Medium Wash'),
('Mystic- Med Wash','Mystic- Medium Wash'),
('Nantucket - Med Wash','Nantucket - Medium Wash'),
('Harbor - Med Wash-30','Harbor - Medium Wash'),
('Harbor - Med Wash-29','Harbor - Medium Wash'),
('Gunmetal/Royal Heather','Gunmetal/Royal Heather'),
('Navy Camo CA','Navy Camo CA'),
('Navy Nautical','Navy Nautical'),
('Navy-M/10','Navy'),
('Navy-M/5','Navy'),
('Navy/Blue','Navy Blue'),
('Navy/White','Navy/White'),
('Neon Yellow Heather','Neon Yellow Heather'),
('New Kelly Hth Green','New Kelly Heather Green'),
('Nickel','Nickel'),
('Grey Snow/Chrc Hethtr','Grey Snow/Charcoal Hethtr'),
('Nocturnal','Nocturnal'),
('Norse','Norse'),
('Nvy/Heritage Blue','Navy/Heritage Blue'),
('White Navy','White Navy'),
('Aqua Medium Light Wash','Aqua Medium Light Wash'),
('# 3 Atlantic','# 3 Atlantic'),
('Ocean Blue Med Wash','Ocean Blue Medium Wash'),
('Ocean Camo/Charcoal','Ocean Camo/Charcoal'),
('Green Combo','Green Combo'),
('Off White/Black','Off White/Black'),
('White/Green','White/Green'),
('GRAPHITE HEATHER','Graphite Heather'),
('Grapewine/Elderberry','Grapewine/Elderberry'),
('OliveSpaceDye','OliveSpaceDye'),
('OlvCamo','OlvCamo'),
('Onyx Wash','Onyx Wash'),
('Golden Oak Geo Camo','Golden Oak Geo Camo'),
('Outerbank - Lt Wash w Tint','Outerbank - Light Wash w Tint'),
('GNC','GNC'),
('Glacier-XXL','Glacier'),
('Glacier-XLG','Glacier'),
('Glacier-SML','Glacier'),
('Glacier-MED','Glacier'),
('Oxford Blue','Oxford Blue'),
('Glacier-LRG','Glacier'),
('Pastel Lght Blue','Pastel Lght Blue'),
('Pastel Turqouise','Pastel Turqouise'),
('Falcon-XXL','Falcon'),
('Falcon-XLG','Falcon'),
('Falcon-SML','Falcon'),
('Falcon-MED','Falcon'),
('Falcon-LRG','Falcon'),
('Faded Salmon','Faded Salmon'),
('Pink Wash','Pink Wash'),
('Pond - Med Wash-29','Pond - Medium Wash'),
('Pond - Med Wash-30','Pond - Medium Wash'),
('Pond - Med Wash-32','Pond - Medium Wash'),
('Pond - Med Wash-34','Pond - Medium Wash'),
('Pond - Med Wash-36','Pond - Medium Wash'),
('Pond - Med Wash-38','Pond - Medium Wash'),
('Apollo - Med Wash w Tint','Apollo - Medium Wash w Tint'),
('Wht/MedHthr','Wht/MedHthr'),
('ANTIQUE CHERRY RED','Antique Cherry Red'),
('Dubai - Dark Wash','Dubai - Dark Wash'),
('Red/Light Heather Gry','Red/Light Heather Grey'),
('Red/Off White','Red/Off White'),
('Daybreak Sky - Med Wash w Tint','Daybreak Sky - Medium Wash w Tint'),
('Royal','Royal'),
('Royal Hthr','Royal Heather'),
('Ruby Wine','Ruby Wine'),
('Dark Olive Marled','Dark Olive Marled'),
('RUST - DK Blue-29','Rust-Dark Blue'),
('RUST - DK Blue-30','Rust-Dark Blue'),
('RUST - DK Blue-32','Rust-Dark Blue'),
('RUST - DK Blue-34','Rust-Dark Blue'),
('RUST - DK Blue-36','Rust-Dark Blue'),
('RUST - DK Blue-38','Rust-Dark Blue'),
('Dark Ivy','Dark Ivy'),
('Dark Green Omni/Black','Dark Green Omni/Black'),
('Sahara - Med Wash w Tint','Sahara - Medium Wash w Tint'),
('Sailing Wash','Sailing Wash'),
('Salt Lake - Med Wash','Salt Lake - Medium Wash'),
('Dark Blue','Dark Blue'),
('Crimson - Dk Wash w Tint','Crimson - Dark Wash w Tint'),
('Cream Multi','Cream Multi'),
('Sand Rock','Sand Rock'),
('Clyde - Med Wash','Clyde - Medium Wash'),
('Sbltd Brgndy Camo','Sbltd Burgundy Camo'),
('Scrthd Blk','Scratched Black'),
('Classic Navy','Classic Navy'),
('Chrcl Hthr/LtGry Hthr','Charcoal Heather/LtGry Heather'),
('Sea Water - Med Dk Wash','Sea Water - Medium Dark Wash'),
('Seafoam','Seafoam'),
('Annie Wash','Annie Wash'),
('Seaside - Lt Wash','Seaside - Light Wash'),
('Chinese Apple','Chinese Apple'),
('Charcoal-30','Charcoal'),
('SHOCKY PINK','Shocky Pink'),
('Sierra- Lt Md Wash','Sierra- Light Medium Wash'),
('Silver','Silver'),
('Silver/Black','Silver/Black'),
('Simple Sage CBO','Simple Sage Combo'),
('Sky','Sky'),
('Charcoal Bomba','Charcoal Bomba'),
('Sky Light Wash','Sky Light Wash'),
('SKYFALL - Lt Wash','SKYFALL - Light Wash'),
('Cerulean - Med Dark Wash','Cerulean - Medium Dark Wash'),
('Celeste Wash','Celeste Wash'),
('Skyway Blue','Skyway Blue'),
('IRISH GREEN','Irish Green'),
('Spade','Spade'),
('Splash- Drk Wash','Splash- Dark Wash'),
('Burgundy Hthr','Burgundy Heather'),
('Burgundy Bomba','Burgundy Bomba'),
('Burgndy/Chrcl-M/10','Burgundy/Charcoal'),
('Burg/Off White','Burg/Off White'),
('Brown/Chrcl Hthr','Brown/Charcoal Heather'),
('Stellar','Stellar'),
('Brngdy/MHthrGry','Burgundy/MHthrGry'),
('Stone Block Cmbo','Stone Block Combo'),
('Bonzai - Dark Wash','Bonzai - Dark Wash'),
('Boardwalk','Boardwalk'),
('Blue Stone','Blue Stone'),
('Blue Moon- Md Drk Wash','Blue Moon- Medium Dark Wash'),
('Amazon - Med Wash w Tint','Amazon - Medium Wash w Tint'),
('Blk/MdHthrGry','Black/MdHthrGry'),
('Blk/Heather','Black Heather'),
('Blk Spc Dye / Blk','Black Space Dye / Black'),
('Blck/HthrGry','Black/HthrGry'),
('Blck/Brgndy','Black/Burgundy'),
('Blck Paradise-38','Black Paradise'),
('TD Navy','TD Navy'),
('Blck Paradise-36','Black Paradise'),
('TD PURPLE TEAL','Td Purple Teal'),
('Blck Paradise-34','Black Paradise'),
('Blck Paradise-32','Black Paradise'),
('Blck Paradise-30','Black Paradise'),
('Admiral Medium Wash','Admiral Medium Wash'),
('Blck Paradise-29','Black Paradise'),
('Blck Marl','Black Marled'),
('Blck Knght','Black Knight'),
('Blck Fade','Black Fade'),
('Blanco V2','Blanco V2'),
('Titanium Gry GD','Titanium Grey GD'),
('True Light Blue','True Light Blue'),
('True Red','True Red'),
('BLACK/NEON GREEN','Black/Neon Green'),
('Black/Mint','Black/Mint'),
('Black-M/10','Black'),
('Black Widow','Black Widow'),
('Typhoon- Drk Wash','Typhoon- Dark Wash'),
('Black Stone','Black Stone'),
('US Flag','US Flag'),
('Vallarta Blue Fly','Vallarta Blue Fly'),
('Black Geo Camo','Black Geo Camo'),
('Veil - Dark Wash-29','Veil - Dark Wash'),
('Veil - Dark Wash-30','Veil - Dark Wash'),
('Veil - Dark Wash-32','Veil - Dark Wash'),
('Veil - Dark Wash-34','Veil - Dark Wash'),
('Veil - Dark Wash-36','Veil - Dark Wash'),
('Veil - Dark Wash-38','Veil - Dark Wash'),
('Black City Scape','Black City Scape'),
('BKM','BKM'),
('BEACH SIDE- LT WASH','Beach Side- Light wash'),
('Vintage Lake','Vintage Lake'),
('Barcelona - Lt Wash','Barcelona - Light Wash'),
('Azure - Medium M Wash','Azure - Medium M Wash'),
('Warm Gray','Warm Grey'),
('WASHED Khaki','WASHED Khaki'),
('03-Boardwalk','03-Boardwalk'),
('LT BEIGE CAMO','Light Beige Camo'),
('Light Denim Wash','Light Denim Wash'),
('Kings Blue - Dark Wash','Kings Blue - Dark Wash'),
('Lt Gray/Black','Light Grey/Black'),
('Lt Gray/Navy','Light Grey/Navy'),
('Lt Green','Light Green'),
('Khaki Cali Bear','Khaki Cali Bear'),
('Kelly Hthr','Kelly Heather'),
('Kelly Green','Kelly Green'),
('Lt Grey Tonal Camo','Light Grey Tonal Camo'),
('Lt Grey/Black','Light Grey/Black'),
('Lt Hthr/White','Light Heather/White'),
('Lt. Hthr Gry/Black','Light Heather Grey/Black'),
('Lt. Indigo','Light Indigo'),
('LtGrySpckl','LtGrySpckl'),
('Lulu Wash','Lulu Wash'),
('Jungle Camo','Jungle Camo'),
('malt','malt');

-- lower(any spelling) -> color_master id
CREATE TEMP TABLE _clook ON COMMIT DROP AS
SELECT DISTINCT ON (k) k, id FROM (
  SELECT lower(name) AS k, id FROM color_master
  UNION ALL
  SELECT lower(m.raw) AS k, cm.id
  FROM _cmap m JOIN color_master cm ON lower(cm.name) = lower(m.canon)
) u
ORDER BY k, id;
CREATE INDEX ON _clook(k);

WITH desired AS (
  SELECT s.id AS style_id,
    (SELECT array_agg(DISTINCT e) FROM (
        SELECT jsonb_array_elements_text(COALESCE(s.attributes->'color_ids','[]'::jsonb)) AS e
        UNION
        SELECT l.id::text
        FROM ip_item_master i JOIN _clook l ON l.k = lower(btrim(i.color))
        WHERE i.style_id = s.id AND i.color IS NOT NULL AND btrim(i.color) <> ''
     ) u) AS ids
  FROM style_master s
  WHERE s.deleted_at IS NULL
    AND EXISTS (SELECT 1 FROM ip_item_master i JOIN _clook l ON l.k = lower(btrim(i.color))
                WHERE i.style_id = s.id AND i.color IS NOT NULL AND btrim(i.color) <> '')
)
UPDATE style_master s
SET attributes = jsonb_set(COALESCE(s.attributes, '{}'::jsonb), '{color_ids}', to_jsonb(d.ids)),
    updated_at = now()
FROM desired d
WHERE s.id = d.style_id
  AND COALESCE(s.attributes->'color_ids', '[]'::jsonb) <> to_jsonb(d.ids);
